### ISSUE TITLE
"WakaTime Error"

### ISSUE THREAD

**Issue by boneskull** [wakatime/vscode-wakatime#100]
Hi,

I have "WakaTime Error" in my status bar with all of my projects.  I don't see anything in the logs (`~/.wakatime.log`) and am unsure where to get more information.  "WakaTime Initializing..." appears for awhile before the error; smells a bit like a timeout.

What server(s) is it attempting to hit?

My API code is set and is correct.

**Comment by alanhamlett** [comment]
How about any errors in the VS Code Developer Console window?

It's either talking to `github.com` or `api.wakatime.com`.

**Comment by boneskull** [comment]
yeah

```
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/boneskull/.vscode/extensions/wakatime.vscode-wakatime-2.1.0/wakatime-master/wakatime/cli.py': [Errno 2] No such file or directory
```

`wakatime-master` does not exist; a `wakatime-master.zip` does, however.  

I'll unzip that and see what happens.

**Comment by boneskull** [comment]
nope, that's a 0-byte file.

I'll try uninstalling & reinstalling.

**Comment by boneskull** [comment]
that didn't fix it.  in the console I also see

```
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] ::WakaTime debug mode::
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Initializing WakaTime v2.1.0
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Looking for python at: /Users/boneskull/.vscode/extensions/wakatime.vscode-wakatime-2.1.0/python/pythonw
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Invalid python version: 
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Looking for python at: python3
extensionHost.ts:215 Extension Host
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Valid python version: Python 3.7.3

/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:235 [Extension Host] [WakaTime][DEBUG] Downloading wakatime-core...
/Users/boneskull/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1408   ERR connect ECONNREFUSED 0.0.0.0:443: Error: connect ECONNREFUSED 0.0.0.0:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

I don't know if that last line is coming out of WakaTime.  The last thing that's explicitly marked as such is "Downloading wakatime-core..."

**Comment by boneskull** [comment]
OK, so that suggests to me the domain is blocked.  Changing my DNS allows it to go through.  I'll need to figure out what exactly needs whitelisting.

**Comment by alanhamlett** [comment]
Very strange, as that comes directly from GitHub so it shouldn't be blocked if you're able to browse this issue here.

**Comment by Elite24shaikh** [comment]
hey dear programmer !
Whenever I hit ENTER to go on another line then waka time menu coming........
![Screenshot (87)](https://user-images.githubusercontent.com/72573358/102529569-15e58e00-40c6-11eb-8c0a-edd511c8f137.png)Like this see at the top....plzzz help me

**Comment by stevescilar** [comment]
Try Checking if the windows defender is blocking wakatime
