### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ryansonshine** [wakatime/vscode-wakatime#101]
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `2.1.0`
- OS Version: `Linux x64 4.10.0-38-generic`
- VSCode version: `1.33.1`

[WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt](https://github.com/wakatime/vscode-wakatime/files/3179714/WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gandarez** [comment]
renamed to `.cpuprofile` and tried to load threw an error `Can't load file. Supported file extensions: '.cpuprofile'.`

**Comment by gandarez** [comment]
Enable debug mode by opening command pallet and typing `>WakaTime: Debug`. Get the log from console.

**Comment by alanhamlett** [comment]
Fixed with fdcc609d7132786c70eb76ab6fe9aa0d394d1cc9 and released in v2.1.1.
