### ISSUE TITLE
Status bar enabled setting still showing clock icon

### ISSUE THREAD

**Issue by nikitavoloboev** [wakatime/vscode-wakatime#102]
I want to hide this icon in activity bar:

![2019-05-22 at 17 48](https://user-images.githubusercontent.com/6391776/58188939-d1132e80-7cb9-11e9-9ea3-44f23e7aa04b.png)

Can you please add a setting to do it? It adds unnecessary clutter to me and is useless. Thanks.

**Comment by alanhamlett** [comment]
Sure, it's already available with the setting `WakaTime: Status Bar Enabled` set to `false`.

**Comment by nikitavoloboev** [comment]
There is a bug then:

![2019-05-22 at 17 57](https://user-images.githubusercontent.com/6391776/58189594-16842b80-7cbb-11e9-9223-5daeea90b479.png)

**Comment by alanhamlett** [comment]
Does it disappear after relaunching vscode?

**Comment by nikitavoloboev** [comment]
It doesn't

**Comment by gandarez** [comment]
Attach your `.wakatime.cfg` please (don't forget to hide your api key)

**Comment by nikitavoloboev** [comment]
[settings]
api_key = 

status_bar_coding_activity = false
status_bar_icon = false

**Comment by alanhamlett** [comment]
Change `status_bar_icon` to `status_bar_enabled` then reload vscode. It was renamed [a while back](https://github.com/wakatime/vscode-wakatime/blob/ede1d97e2c2144fb114a562e8c2ef2ca74845135/CHANGELOG.md#208-2019-04-30) but that doesn't explain why it's not writing with the new renamed key. Can you also try toggling `WakaTime: Status Bar Enabled` true/false once?

**Comment by alanhamlett** [comment]
@nikitavoloboev can you update the extension to v2.1.2 and see if it's fixed?

**Comment by nikitavoloboev** [comment]
Sweet that worked, thanks

**Comment by Kkknight-12** [comment]
@alanhamlett thank you, I was having the same issue after I changed my time preference.
