### ISSUE TITLE
Too many languages and the pie chart doesn't show.

### ISSUE THREAD

**Issue by GitHubCloud** [wakatime/vscode-wakatime#104]
![image](https://user-images.githubusercontent.com/4325139/58618209-9e3deb80-82f4-11e9-8438-e99b0795a48d.png)

**Comment by alanhamlett** [comment]
Fixed now after refresh.

**Comment by GitHubCloud** [comment]
> Fixed now after refresh.

Not much improve..
![image](https://user-images.githubusercontent.com/4325139/58679657-1361fd00-8397-11e9-9c1d-1027c929198a.png)

I use surface book 2, resolution ratio is 3000 * 2000, scaling ratio is 200%.

**Comment by alanhamlett** [comment]
So JavaScript with jQuery says `$(window).width()` is `3000` and `$(window).height()` is `2000`? Currently we only hide languages legend with more than 15 languages, so your legend is still barely shown. We should instead see if the pie chart renders below a certain number of pixels width to show/hide the legend.

**Comment by GitHubCloud** [comment]
Because my scaling ratio is 200%, so my actual resolution ratio should be 1500 * 1000, And minus some browser address bar and some scroll bar, Display area became this width and height:
```javascript
$(window).width()
// 1483
$(window).height()
// 890
```

I think the better solution is to give me a dropdown & multiple select menu like this:
![image](https://user-images.githubusercontent.com/4325139/58788453-7e713500-861e-11e9-9116-bac4b7b965c7.png)

Via: [ElementUI](https://element.eleme.cn/#/en-US/component/select#basic-multiple-select)

**Comment by gandarez** [comment]
@GitHubCloud is that fixed for you?

**Comment by alanhamlett** [comment]
Fixed with https://github.com/wakatime/vscode-wakatime/issues/294#issuecomment-1222932881
