### ISSUE TITLE
not tracking anything

### ISSUE THREAD

**Issue by nitwhiz** [wakatime/vscode-wakatime#108]
`[Extension Host] [WakaTime][DEBUG] Looking for python at: \Python33\pythonw`

tells me I need python somewhere, where is `\PythonXX\`?

**Comment by nitwhiz** [comment]
I installed python 3.7.4, it changed nothing.
Just saw that on start, it downloads and installs python. That obviously fails without any error message.

```
console.ts:134 [Extension Host] [WakaTime][DEBUG] Downloading python...
console.ts:134 [Extension Host] [WakaTime][DEBUG] Extracting python...
console.ts:134 [Extension Host] [WakaTime][DEBUG] Finished installing python.
2
console.ts:134 [Extension Host] [WakaTime][DEBUG] Downloading wakatime-core...
console.ts:134 [Extension Host] [WakaTime][DEBUG] Extracting wakatime-core into "c:\Users\an10048\.vscode\extensions\wakatime.vscode-wakatime-2.1.2"...
console.ts:134 [Extension Host] [WakaTime][DEBUG] Finished extracting wakatime-core.
console.ts:134 [Extension Host] [WakaTime][DEBUG] WakaTime: Initialized
console.ts:134 [Extension Host] [WakaTime][DEBUG] Extracting wakatime-core into "c:\Users\an10048\.vscode\extensions\wakatime.vscode-wakatime-2.1.2"...
console.ts:134 [Extension Host] [WakaTime][DEBUG] Finished extracting wakatime-core.
console.ts:134 [Extension Host] [WakaTime][DEBUG] Looking for python at: c:\Users\an10048\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\python\pythonw
console.ts:134 [Extension Host] [WakaTime][DEBUG] Error: spawn UNKNOWN
```

**Comment by gandarez** [comment]
What's your environment/setup?

**Comment by nitwhiz** [comment]
- Windows 10
- Visual Studio 1.36.1

Do you need anything else?

**Comment by gandarez** [comment]
Is `python.exe` to environment path?

**Comment by alanhamlett** [comment]
Try deleting this folder:

`c:\Users\an10048\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\python`

Then restart vscode and see if it's working by typing in a file and checking this page:
https://wakatime.com/plugins/status

**Comment by nitwhiz** [comment]
> Is python.exe set to environment path?

That was the problem.

> Try deleting [...]

After adding python to Path, removing that python folder and restarting vsc, it works now!

Thanks ❤️
