### ISSUE TITLE
Wakatime does not start

### ISSUE THREAD

**Issue by Developer8814** [wakatime/vscode-wakatime#109]
Hello,
A few days ago install the extension, but when you try to initialize the counting mark "Wakatime Error" the label says "Wakatime: Unknow Error (3221225477)" sometimes say Error (2) , I tried the following:

* update extension
* no_ssl_verify = true
* install win-ca extension

i have the version wakatime 2.1.2 vscode 1.36.1 on Windows 10 , the wakatime log says

```
{"now": "2019/07/13 19:04:31 -0500", "version": "12.0.0", "plugin": "vscode/1.36.1 vscode-wakatime/2.1.2", "time": 1563062669.6806626, "caller": "c:\\Users\\Varg\\.vscode\\extensions\\wakatime.vscode-wakatime-2.1.2\\wakatime-master\\wakatime\\api.py", "lineno": 53, "file": "c:\\wamp64\\www\\SGCE\\controlador\\asigna_docente_grupo_sql.php", "level": "DEBUG", "message": "Sending heartbeats to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk"}
{"now": "2019/07/13 19:04:31 -0500", "version": "12.0.0", "plugin": "vscode/1.36.1 vscode-wakatime/2.1.2", "time": 1563062669.6806626, "caller": "c:\\Users\\Varg\\.vscode\\extensions\\wakatime.vscode-wakatime-2.1.2\\wakatime-master\\wakatime\\api.py", "lineno": 59, "file": "c:\\wamp64\\www\\SGCE\\controlador\\asigna_docente_grupo_sql.php", "level": "DEBUG", "message": "[{'project': 'SGCE', 'category': None, 'entity': 'C:/wamp64/www/sgce/controlador/asigna_docente_grupo_sql.php', 'type': 'file', 'branch': None, 'user_agent': 'wakatime/12.0.0 (Windows-10-10.0.17134-SP0) Python3.5.1.final.0 vscode/1.36.1 vscode-wakatime/2.1.2', 'lineno': None, 'time': 1563062669.6806626, 'lines': 51, 'dependencies': [\"'../utilerias/Conexion.php'\"], 'language': 'PHP', 'cursorpos': None, 'is_write': False}]"}
```

Please Help 
I do not know what else to do
Thank you

**Comment by gandarez** [comment]
Can you see any data into the dashboard?

**Comment by Developer8814** [comment]
Hello,

The Dashboard does not show me anything, appears empty because has not received any information.

I still can not operate the extension

**Comment by gandarez** [comment]
Are you behind a proxy or firewall?

**Comment by Developer8814** [comment]
The problem happens on my laptop in my house, it simply connects to the internet through a service provider, I do not have a configuration more than normal

**Comment by alanhamlett** [comment]
@Developer8814 those log lines from your `wakatime.log` file are debug messages (`"level": "DEBUG"`). Do you have any other log lines in that file? Specifically ones of level `WARNING` or `ERROR`?

**Comment by alanhamlett** [comment]
Also, please check and paste here any error messages found in your Developer Console window:

`Help → Toggle Developer Tools`

**Comment by Developer8814** [comment]
Hello, the wakatime.log it does not contain more lines... 

This is what Toggle Developer Tools says abour waka time 

![Captura](https://user-images.githubusercontent.com/25228805/61343896-00a36a80-a815-11e9-85ef-858303dbe661.PNG)

**Comment by alanhamlett** [comment]
Is debug mode turned on in your vscode wakatime plugin settings? To check, press `F1` then type `wakatime debug` and press `Enter`. If it's current value is `false`, turn it on with `true`.

After debug mode is turned on, let's run the command that failed manually from cmd prompt:
`c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\python\pythonw c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\wakatime-master\wakatime\cli.py --version`

and

`c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\python\pythonw c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\wakatime-master\wakatime\cli.py --file c:\wamp64\www\SGCE\controlador\delete_grupo_sql.php --plugin "vscode/1.36.1 vscode-wakatime/2.1.2" --alternate-project SGCE`

The first command should just print the wakatime-cli version, and the second command shouldn't print anything. Please paste any error messages if any are printed from the above commands.

Finally, let's check your c:\Users\Varg\.wakatime.log file which should have some more log lines now.

**Comment by Developer8814** [comment]
Hello, the result of the two commands is : 

![Captura](https://user-images.githubusercontent.com/25228805/61426973-f7340400-a8e1-11e9-9155-f1c5dbf2fb6e.PNG)
![Captura2](https://user-images.githubusercontent.com/25228805/61426975-f7340400-a8e1-11e9-9ff2-384e0407b057.PNG)

The log file say the same error

{"now": "2019/07/17 22:25:41 -0500", "version": "12.0.0", "plugin": "vscode/1.36.1 vscode-wakatime/2.1.2", "time": 1563420338.7170088, "caller": "c:\\Users\\Varg\\.vscode\\extensions\\wakatime.vscode-wakatime-2.1.2\\wakatime-master\\wakatime\\api.py", "lineno": 59, "file": "c:\\wamp64\\www\\SGCE\\controlador\\delete_alumno_sql.php", "level": "DEBUG", "message": "[{'dependencies': [\"'../utilerias/Conexion.php'\"], 'time': 1563420338.7170088, 'cursorpos': None, 'type': 'file', 'user_agent': 'wakatime/12.0.0 (Windows-10-10.0.17134-SP0) Python3.5.1.final.0 vscode/1.36.1 vscode-wakatime/2.1.2', 'lines': 45, 'project': 'SGCE', 'language': 'PHP', 'is_write': False, 'lineno': None, 'category': None, 'entity': 'C:/wamp64/www/sgce/controlador/delete_alumno_sql.php', 'branch': None}]"}

**Comment by alanhamlett** [comment]
Looks like the second command didn't get copied/pasted correctly. It's missing everything after `--file`. Can you run that one again:

`c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\python\pythonw c:\Users\Varg\.vscode\extensions\wakatime.vscode-wakatime-2.1.2\wakatime-master\wakatime\cli.py --file c:\wamp64\www\SGCE\controlador\delete_grupo_sql.php --plugin "vscode/1.36.1 vscode-wakatime/2.1.2" --alternate-project SGCE`

**Comment by Developer8814** [comment]
The command does nothing ...
![Captura](https://user-images.githubusercontent.com/25228805/61506996-a556b100-a9a9-11e9-8e4a-7d51d80dc338.PNG)


I do not know what else to do

**Comment by gandarez** [comment]
Go to dashboard and see if there's any data showing up there.

**Comment by Developer8814** [comment]
This is my Dashboard

![Captura](https://user-images.githubusercontent.com/25228805/61581802-6e3ae980-aae8-11e9-8030-a15ecc7b3d93.PNG)

**Comment by alanhamlett** [comment]
> The command does nothing

That means it worked as expected. Does your `~/.wakatime.log` now contain any new lines at the bottom of that file? The DEBUG messages you've pasted above are normal, so if there's still only DEBUG level lines in your log file then only thing I can think of is you might have two WakaTime accounts and your vscode is using the api key of a different duplicate account.

Check that your api key in vscode wakatime settings matches your api key here:
https://wakatime.com/settings/api-key

**Comment by Developer8814** [comment]
Hi, today I turned on my laptop and opened the vscode, I got a message "an extension had changed, reload your window", then the wakatime starts to work without problem, the only difference that I made is to work with brackets adobe (the brackets have wakatime extension too) before opening the vscode, work a few minutes and when opening the vscode were the minutes counted from the previous brackets are in the bar of the wakatime.

I do not know how or why but the problem is solved, thanks to the community for their support.

regards

**Comment by alanhamlett** [comment]
That's great! We did release an update to the plugin today around it's dependencies that might have fixed it.
