### ISSUE TITLE
WakaTime not working through corp SSL proxy

### ISSUE THREAD

**Issue by ghost** [wakatime/vscode-wakatime#11]
I get this error when I start vscode, api key is entered wakatime stays offline and the wakatime.log is empty.

```
hreadService.ts:207[Extension Host] Error: Command failed: pythonw %USERPROFILE%\.vscode\extensions\WakaTime.vscode-wakatime-1.0.6\out\wakatime-master\wakatime\cli.py --file %FILENAME% --plugin vscode/1.2.1 vscode-wakatime/1.0.6 --alternate-project %PROJECTNAME%

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by alanhamlett** [comment]
Does the WakaTime status bar item always say offline or sometimes say `WakaTime Active`?

When is the last time vscode shows in this list of your editors:
https://wakatime.com/api/v1/users/current/user_agents
( Check the `last_seen` time for vscode )

**Comment by con-ssc** [comment]
Yes always. the user_agents are empty. So I guess that means it was never online.

**Comment by con-ssc** [comment]
How is the connection to wakatime implemented? I recently had problems of "apps" trying to use port 443 because Kaspersky disrupted the connection without any feedback or error message.

**Comment by alanhamlett** [comment]
It makes a https request to remote port 443. Try disabling your firewall and see if that fixes it?

**Comment by con-ssc** [comment]
I cannot, it is an enterprise solution so I have no control over it.

**Comment by alanhamlett** [comment]
Can your Administrator add WakaTime to an approved list?

**Comment by con-ssc** [comment]
I tried that with other apps already, didn't work, we are considering disabling port traffic control.

**Comment by con-ssc** [comment]
I now get this
![image](https://cloud.githubusercontent.com/assets/8189808/18700662/c456cc14-7fd8-11e6-8c9b-104f011e968c.png)

**Comment by alanhamlett** [comment]
That is the Python part of WakaTime (https://github.com/wakatime/wakatime) now receiving an error connecting to the API. This means your plugin was able to connect to GitHub to download [wakatime-cli](https://github.com/wakatime/wakatime) but then coding activity was not able to be sent to the API.

You should have some more details as to why the connection failed in this file:
`C:\Users\stefan.schneider\.wakatime.log`

**Comment by con-ssc** [comment]
Unfortunately the log file is empty

Von: Alan Hamlett [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. September 2016 09:26
An: wakatime/vscode-wakatime <vscode-wakatime@noreply.github.com>
Cc: Stefan Schneider <Stefan.Schneider@connectiv.de>; Author <author@noreply.github.com>
Betreff: Re: [wakatime/vscode-wakatime] Wakatime Offline (#11)


That is the Python part of WakaTime (https://github.com/wakatime/wakatime) now receiving an error connecting to the API. This means your plugin was able to connect to GitHub to download wakatime-cli<https://github.com/wakatime/wakatime> but then coding activity was not able to be sent to the API.

You should have some more details as to why the connection failed in this file:
C:\Users\stefan.schneider\.wakatime.log

**Comment by bensontrent** [comment]
I'm behind a company vpn and can only connect via http connections via the command line since the VPN acts as man-in-the-middle the certificate gets rejected.

**Comment by alanhamlett** [comment]
@bensontrent we can't support http for security reasons, but you could proxy the api requests and change the `api_url` setting in your `~/.wakatime.cfg` file.

**Comment by Gobayli** [comment]
Hi Alan, wanna continue on this discussion. I encounter the same issue with atom-wakatime. And I disabled the SSL verification requirement in waka setting in Atom however, it still always shows wakatime offline. But the it works under my home internet environment. Any advice? Thanks!

**Comment by jeanpaul1304** [comment]
Same problem :/

**Comment by alanhamlett** [comment]
What proxy setting are you using in `~/.wakatime.cfg`?

**Comment by gandarez** [comment]
Closed due to lack of information.
