### ISSUE TITLE
Wakatime suddenly slowing down my editor

### ISSUE THREAD

**Issue by faurehu** [wakatime/vscode-wakatime#110]
I've been the plugin for a while now and never had any issues. For about two or three days now, my editor freezes every time I switch modes (I use the vim plugin too). I looked into the process explorer and wakatime showed up every time I switched modes, and when I disabled it, the issue was gone.

I have:
- Vim 1.8.2
- Wakatime 2.1.2
- VsCode 1.36.0

I did a system wide update last weekend so this might have to do with newer version of VsCode.

**Comment by faurehu** [comment]
Actually, it's not Wakatime's fault. The issue is still around even without Waketime enabled, which makes more sense anyway :sweat_smile: 
Please delete this thread, thanks.

**Comment by gandarez** [comment]
Thanks :)
