### ISSUE TITLE
does not trace my time when someone invites me to code using live share plugin

### ISSUE THREAD

**Issue by edilson14** [wakatime/vscode-wakatime#113]
i am using waka time and live share, some one gives me a link to code with him , but waka time does not trace that time 
why?
it is a bug or he can not do that?

**Comment by gandarez** [comment]
Are you connecting remotely to someone's else or receiving the connection?

**Comment by edilson14** [comment]
i am reciving connection form someone's else , he send-me link

**Comment by gandarez** [comment]
So you're coding remotely connected to someone's else machine, right? In this scenario your partner needs to have its own WakaTime.

**Comment by edilson14** [comment]
tanks :)
