### ISSUE TITLE
Keeps creating `.wakatime-project` file(s) in projects

### ISSUE THREAD

**Issue by hilleer** [wakatime/vscode-wakatime#114]
Hi,

I have configured **wakatime** with hidden project names (`hide_project_names = true`).

With this setting the plugin creates a `.wakatime-project` in **all projects** I work in (there is quiet a lot). Meaning I either have to add this file to all `.gitignore` files **or** disable the extension.... 

I chose the latter, unfortunately. 

Is there a secret way to resolve this or is it intentionally done this way?

**Comment by cseder** [comment]
How about putting *.wakatime* into your ~/.gitignore_global file?

**Comment by hilleer** [comment]
Thanks @cseder - that would definitely work and is probably a good workaround for now, but I still find it somewhat weird to have those files laying around in all your projects...

**Comment by cseder** [comment]
> Thanks @cseder - that would definitely work and is probably a good workaround for now, but I still find it somewhat weird to have those files laying around in all your projects...

I know, but what would be the alternative? 
If you want Wakatime to hide your real project names it has to give it some name, and keep track of what project resides where etc.
There are of course many ways to solve this, like using a local file-based database or something, but again, projects can move around and keeping track of this is easiest implemented using a local, hidden .projectname kinda file like Wakatime does.

No different from the "litter" most IDE's and even text editors do nowadays.
I have this in my `.gitignore_global` for various IDE's etc:

```
### Garbage Section ###

# VS Code / VS Codium
.vscode/
.vscode-oss/

# IntelliJ
*.iml
*.ipr
*.iws
.idea/

# Wakatime
*.wakatime*

```

**Comment by hilleer** [comment]
Ok, I accept this - I still believe other solutions would be more optimal, but that is probably more a personal preference. 

Thanks for your help, time and suggestion to solve this issue. :)

**Comment by hilleer** [comment]
Hi @cseder,

I found another concern in relation to is.

If you work with NPM and publish modules/packages, eventually you might forget that you have to add this to `.npmignore` as well. And now, as you probably have it global `.gitignore` it will be greyed out and you are likely to forget everything about it.
