### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tushardevs** [wakatime/vscode-wakatime#115]
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `2.2.0`
- OS Version: `Windows_NT x64 10.0.18875`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\TUSHAR\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gandarez** [comment]
Please attach `C:\Users\TUSHAR\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`

**Comment by copyshiroe** [comment]
[WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt](https://github.com/wakatime/vscode-wakatime/files/3700246/WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt)
@gandarez I have the same trouble too.

**Comment by gandarez** [comment]
@copyshiroe couldn't find any reference to `wakatime` in the attached log.
