### ISSUE TITLE
Support for Jupyter Notebooks (.ipynb files)

### ISSUE THREAD

**Issue by likaihz** [wakatime/vscode-wakatime#118]
When working on a Jupyter Notebook using vs code, the waketime plugin was not tracking time .

**Comment by alanhamlett** [comment]
When you turn on debug mode do you see a message:
`File does not exist; ignoring this heartbeat.`

It might be that notebooks don't persist in the file shown to vscode?

**Comment by likaihz** [comment]
> When you turn on debug mode do you see a message:
> `File does not exist; ignoring this heartbeat.`
> 
> It might be that notebooks don't persist in the file shown to vscode?

I don't see this message.  But I find in the developer tools that whenever I switch to the tab of a ipynb file, the plugin stop sending heartbeat.

**Comment by rockboynton** [comment]
I am having the same issue... any ideas?

**Comment by gandarez** [comment]
It seems that `ipynb` files are not tracked somehow. Tonight I'll try to debug and see what happens under the hood.

**Comment by salihcaan** [comment]
@gandarez Is there any update regarding this issue?

**Comment by alanhamlett** [comment]
The Notebook API is a proposed extension api still under development:
https://code.visualstudio.com/api/extension-guides/notebook

Once it's stable, we can publish the WakaTime extension with support for `vscode.notebook` events.

**Comment by chefZau** [comment]
Is there any update regarding this issue? It has been several months.

**Comment by alanhamlett** [comment]
Still waiting on vscode support for the new Notebook API before WakaTime can use it:

> The Notebook API is still proposed and under development, which means it is only available on VS Code Insiders

**Comment by emilearthur** [comment]
So I am using vscode 1.57.1 (ubuntu 20.04) and it's tracking my workspace. 
Small issue I think: It detects the language as markdown instead of python (which I am using).

**Comment by alanhamlett** [comment]
The [Notebook API was finalized](https://code.visualstudio.com/updates/v1_57#_notebook-api) in May 2021, and the [existing event handlers](https://github.com/wakatime/vscode-wakatime/blob/5b26fab4b046dd3155e8c20da0781fa93807f156/src/wakatime.ts#L324) already work with notebooks so no changes were needed to the plugin.

@emilearthur the notebooks you opened had file extension `.ipynb`?
