### ISSUE TITLE
installation vscode-wakatime issue on VS Studio 1.2.1

### ISSUE THREAD

**Issue by Abdelkrim** [wakatime/vscode-wakatime#12]
1. I followed the installation guide: https://wakatime.com/help/plugins/vscode
2. an error occured during the installation: 'C:\Users\[username]\.vscode\extensions\WakaTime.vscode-wakatime-1.0.6\package.json'

Nevertheless after the restart, I was able to input the key and wakatime was working

**Comment by alanhamlett** [comment]
Does that error happen if you uninstall then reinstall the plugin? Maybe it was a Vscode bug?

**Comment by Abdelkrim** [comment]
@alanhamlett I won't uninstall it and reinstall since it worked.
