### ISSUE TITLE
download as a .vsix file from Github

### ISSUE THREAD

**Issue by carl-parrish** [wakatime/vscode-wakatime#121]
Is there a way to downing the .vsix file from Github?

**Comment by gandarez** [comment]
Not from the repository but from the marketplace you can. There's a link `Download Extension`.
<img width="441" alt="Screen Shot 2020-01-26 at 10 11 45" src="https://user-images.githubusercontent.com/782854/73137264-4e025f00-4024-11ea-816c-9da421c774a2.png">

**Comment by carl-parrish** [comment]
Thanks eventually I figured that out.
