### ISSUE TITLE
Your Website does not immediately send the verification email

### ISSUE THREAD

**Issue by RobFosterNYC** [wakatime/vscode-wakatime#124]
I have tried many times to get the verification email and your website does not seem to want to send me the verification email no matter how many times I try.
Making it impossible for the extension to stay active in my IDE.
Which forces me to have to re-sign up to the website over and over changing my API each time.

being forced to change my API, also forces my time to be reset.
setting me back to zero time.

Please fix, as this is extremely annoying.

**Comment by alanhamlett** [comment]
The extension doesn't require email verification to stay active. The only thing that requires email verification is receiving your weekly summary email. You can actually use WakaTime forever without verifying your email.

Emails can be prone to deliverability problems by nature. WakaTime sends the verification email immediately, but that doesn't mean it shows up in your inbox right away. We should start by checking the mailserver response for those verification emails on our end. Can you reach out to support@wakatime with your WakaTime account email to debug this further?

**Comment by RobFosterNYC** [comment]
Then why am I getting 24 hours later after signing up to an account ?
**

> Invalid email or password.

**
after I have signed up for an account on the website 24 hours later when I try to log into my account, it says
Invalid email or password.
and my extension stops working, im confused by that now.
And the extension now says "" WakaTime Error ""

yesterday I re-created a brand new account with the same email address,
and now today when I want to use the extension it says " WakaTime Error "
And the website also says  "" Invalid email or password. ""
even though I alrerady created an account on the website...    So confused by that ....
.

**Comment by alanhamlett** [comment]
That's because you signed up with someone else's email address and they deleted your account. They also emailed us recently about this, wondering why an account was created on WakaTime with their email address. To prevent someone else deleting your account, make sure to sign up with your email not someone else's email.

**Comment by RobFosterNYC** [comment]
I DID NOT sign up with someone elses email as its my EMAIL.
I would appreciate it if you DIDNT accuse me of stealing or using someone else email account, as the email I used is MINE and has been mine for over 12 years or more.

**Comment by alanhamlett** [comment]
Please send support@wakatime.com an email so we can help get things sorted out regarding your WakaTime account.
