### ISSUE TITLE
Error loading Python lib (Symbol not found: _futimens)

### ISSUE THREAD

**Issue by ymoriaud** [wakatime/vscode-wakatime#125]
Wakatime version : 4.0.0
VsCode version : 1.42.1

Hi !

I noticed that my Wakatime plugin has an error since few days. Does someone have an idea on how can I fix it ? I tried the troubleshooting section, but without success.

```
[WakaTime][ERROR] Error: Command failed: /Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli --file /Users/yann/.wakatime.log --plugin "vscode/1.42.1 vscode-wakatime/4.0.0"[25783] Error loading Python lib '/Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/libpython3.8.dylib': dlopen: dlopen(/Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/libpython3.8.dylib, 10): Symbol not found: _futimens  Referenced from: /Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/libpython3.8.dylib  Expected in: /usr/lib/libSystem.B.dylib in /Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/libpython3.8.dylib
```

Let me know if you need more information.

Thanks !

**Comment by alanhamlett** [comment]
This is related to pyinstaller/pyinstaller#1191. For now, please run these commands in your Mac Terminal:

```
brew install pyenv
git clone https://github.com/wakatime/wakatime.git
cd wakatime
git checkout standalone
env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install
pipenv install
pipenv run python ./build_standalone.py
rm -r /Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/
cp -rp dist/wakatime-cli /Users/yann/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/
```

Then the plugin should start working again, no reload needed.

**Comment by alanhamlett** [comment]
@ymoriaud what's your OS X version?

**Comment by ymoriaud** [comment]
> @ymoriaud what's your OS X version?

Thanks for your help ! Here it is : MacOS Sierra 10.12.6

I will try the commands

**Comment by alanhamlett** [comment]
Scratch that, just re-install the plugin in vscode and it should work. We've released an updated wakatime-cli built for older versions of OS X to fix this.

**Comment by ymoriaud** [comment]
> Scratch that, just re-install the plugin in vscode and it should work. We've released an updated wakatime-cli built for older versions of OS X to fix this.

I tried to reinstall the plugin and it works now. Thanks !

**Comment by alanhamlett** [comment]
The fix was one line in our Travis-CI config:

wakatime/wakatime@85ec9420ef2736c58b76356f5fdb4ebae47ed073
