### ISSUE TITLE
Installed on Remote SSH keeps showing "WakaTime Initializing"

### ISSUE THREAD

**Issue by goofansu** [wakatime/vscode-wakatime#128]
wakatime extension version: 4.0.0

I'm using Remote SSH and installed wakatime extension.

After entering the API key, it keeps showing "WakaTime Initializing" but I cannot find `~/wakatime.log`. I also installed wakatime-cli but it doesn't change.

wakatime.cfg
```
[settings]
api_key = My API Key
debug = true
```

### Screenshot

<img width="626" alt="Screenshot of Code (2020-3-26, 3-43-56 PM)" src="https://user-images.githubusercontent.com/1143191/77622116-a4364480-6f78-11ea-863e-a3f321e6f11d.png">

**Comment by TimSeryakov** [comment]
I'm in exactly the same situation. VS Code on Uduntu+WSL (Windows 10).  Keeps showing "WakaTime Initializing" but I cannot find ~/wakatime.log
![Image 3](https://user-images.githubusercontent.com/59409712/78650517-b17ff700-78c7-11ea-8e30-a9e4fba85235.gif)

**Comment by goofansu** [comment]
It works now. The wakatime-cli version is v13.0.7.
