### ISSUE TITLE
WakaTime Initialzing... Cannot connect to server

### ISSUE THREAD

**Issue by PavelNen** [wakatime/vscode-wakatime#129]
WakaTime extension cannot send statistics to server from Vscode and Webstorm.

Screenshot from Vscode.
![image](https://user-images.githubusercontent.com/25934360/78163830-93db0980-7451-11ea-8cce-1cab0c67d8cb.png)

**Comment by chiehpower** [comment]
![Screenshot at 11-59-44](https://user-images.githubusercontent.com/32332200/80057743-f5c2f680-8559-11ea-9272-76c116871fe2.png)
I also met the same problem... I cannot find my vs code on dashboard of Waka Time website.
Is there any suggestion?

**Comment by alanhamlett** [comment]
Fixed in v7.0.0 of the vscode extension, now that we're using the new [wakatime-cli](https://github.com/wakatime/wakatime-cli) that downloads from GitHub Releases instead of S3.
