### ISSUE TITLE
Is it possible for WakaTime to "copy" the api key to remote container instead of reasking?

### ISSUE THREAD

**Issue by Ilyes512** [wakatime/vscode-wakatime#130]
I am using Vscode Remote: Containers and because WakaTime is a workspace extension kind it keeps asking me for the wakatime key everytime I rebuild. Is it possible to just copy this from the host instead?

**Comment by matt-seddon-ea** [comment]
If you have access to change the container's build process then you can add a to the Dockerfile to copy your config across. Something like this:
`COPY --chown=${USER_UID}:${USER_GID} .wakatime.cfg /home/${USERNAME}/`

**Comment by seawolf** [comment]
I wonder if the developers of the Wakatime extension could add _getting the API key from the ENV_.

This would allow users to add the API key as an ENV var in VSCode's dev-container settings, for the Wakatime extension could try to grab it from the container's environment on each rebuild.

**Comment by alanhamlett** [comment]
Related to #130

**Comment by alanhamlett** [comment]
Let's move this into #244.
