### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by adamsgodoy** [wakatime/vscode-wakatime#131]
- Issue Type: `Bug`
- Extension Name: `vscode-wakatime`
- Extension Version: `4.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by alanhamlett** [comment]
Closing because the error message was never pasted.
