### ISSUE TITLE
[WakaTime][ERROR] Error: Command failed

### ISSUE THREAD

**Issue by clarkezone** [wakatime/vscode-wakatime#134]
Hi I'm attempting to use Wakatime with remote WSL.  It worked for a bit but now consistently fails with this error.. any ideas?:

`[WakaTime][ERROR] Error: Command failed: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli --file /home/james/src/redacted.md --plugin "vscode/1.44.2 vscode-wakatime/4.0.0" --alternate-project redacted/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: �7@8@@@@@@��@@@@�u�u: not found/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: ��: not found/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: ��@@DDP�td�e�e@�e@ttQ�td/lib64/ld-linux-x86-64.so.2GNU: not found/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: +Pz: not found/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: cannot create E@@�u�uXHzlibdl.so.2_ITM_deregisterTMCloneTable__gmon_start___Jv_RegisterClasses_ITM_registerTMCloneTabledlsymdlopendlerrorlibz.so.1inflateinflateInit_inflateEndlibc.so.6__stpcpy_chk__xpg_basenamemkdtempfflushstrcpyfchmodreaddirsetlocalefopenwcsncpystrncmp__strdupperrorclosedirftellsignalstrncpymbstowcsforkunlinkmkdirstdingetpidkillstrtokfeofcallocstrlenmemsetdirnamermdirfseekclearerrunsetenv__fprintf_chkstdoutstrnlenfclose__vsnprintf_chkmallocstrcatrealpathraise__strncpy_chknl_langinfoopendirgetenvstderr__snprintf_chk__strncat_chkexecvpstrncat__realpath_chkfilenofwritefreadwaitpidstrchr__vfprintf_chk__strcpy_chk__xstat__strcat_chksetbufstrcmp__libc_start_mainferrorstpcpyfreeGLIBC_2.2.5GLIBC_2.3GLIBC_2.4GLIBC_2.3.4: File name too long/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: ELF: not found/home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: 1: /home/james/.vscode-server/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli: Syntax error: word unexpected (expecting ")")`

**Comment by clarkezone** [comment]
Wakatime is still borked on VSCode on ARM windows and is also borked on WSCode on ARM mac.  Time to cancel my subscription.

**Comment by alanhamlett** [comment]
Try adding this line to your `~/.wakatime.cfg` file then restarting vscode:

`standalone = false`

**Comment by clarkezone** [comment]
Thx Alan, tried that.. unfortunately made no difference.

**Comment by alanhamlett** [comment]
It would have at least changed the error message. Can you paste the new error message here?

**Comment by gandarez** [comment]
@clarkezone would you mind join our slack to chat about it? https://wakaslack.herokuapp.com/ you can poke me there

**Comment by alanhamlett** [comment]
This is fixed now that we're using the new Go wakatime-cli.
