### ISSUE TITLE
WakaTime Initializing forever

### ISSUE THREAD

**Issue by luchiago** [wakatime/vscode-wakatime#135]
I search for other issues with the same subject but I couldn't find an answer.
![image](https://user-images.githubusercontent.com/30028621/83136805-7aa3b180-a0be-11ea-9780-ad4781936e3d.png)

**Comment by gandarez** [comment]
Please check if in your `~/..wakatime.cfg` there's a proxy set.

**Comment by luchiago** [comment]
Right!
