### ISSUE TITLE
"Command not found" on vscode terminal 

### ISSUE THREAD

**Issue by sk-sahu** [wakatime/vscode-wakatime#136]
Wakatime plugin: 4.0.0

vscode:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-33-generic snap

**Comment by alanhamlett** [comment]
@sk-sahu do you mean on the dev console window, or in the VS Code Terminal shell feature?
