### ISSUE TITLE
interaction with clipoard master.

### ISSUE THREAD

**Issue by ahmad-ali14** [wakatime/vscode-wakatime#137]
I run on Windows, i use clipboard master so I can paste multiple things one after another.

while waka time is working this clipboard master stops completely on vs code.

I had to disable waka time because of this.

**Comment by alanhamlett** [comment]
Is [this](https://www.clipboardmaster.com/) the clipboard master program you're using?

**Comment by ahmad-ali14** [comment]
yes, but it is now fixed.
