### ISSUE TITLE
Host name is uppercased with Wakatime vscode extension

### ISSUE THREAD

**Issue by perlun** [wakatime/vscode-wakatime#139]
Hi,

Thanks for a great tool. :smile: A small, very small annoyance I have been noticing is in the Wakatime Daily Stats emails, some of my data is being tracked with an uppercase hostname (`VOSTRO` instead of  `vostro`). Interestingly enough, it doesn't seem to be _all_ data for that machine that is affected by this bug, but only the VS Code stats. Data collected with JetBrains Rider seems to use the lowercase `vostro` form.

On other machines, the VSCode-based data is properly using a lowercase host name, so I am not fully sure what's going on here. `vostro` is using DHCP, the other machine (where it works properly) is using a static IP address. 

Both are running Debian GNU/Linux.

Some relevant details:

```shell
$ grep vostro /etc/hosts
127.0.1.1	vostro.example.com	vostro
$ hostname
vostro
$ cat /etc/hostname 
vostro
```

(If you want to for whatever reason look into my data, here is my Wakatime profile: https://wakatime.com/@perlun)

**Comment by alanhamlett** [comment]
Is this still an issue?

**Comment by perlun** [comment]
I think this works fine now. 👍🏻 Sorry for the late feedback.
