### ISSUE TITLE
WakaTime always shows error

### ISSUE THREAD

**Issue by zj-insist** [wakatime/vscode-wakatime#14]
i used VSCode 1.9.1 and entered my API Key ,the Wakatime status still shows error

**Comment by alanhamlett** [comment]
What error message?

**Comment by rodrigo-lorenzo-leal** [comment]
Having the same problem. It says: 

> Config Parsing Error (103); Check your ~/.wakatime.log file for more details.

**Comment by alanhamlett** [comment]
Are you on Windows, Mac, or Linux? Does your `$HOME/.wakatime.cfg` file exist and look like:
```
[settings]
api_key = XXXX
```

When you edit your api key with `CMD+SHIFT+p` `wakatime` does it fix the error?

**Comment by zj-insist** [comment]
i am on mac,i created .wakatime.cfg,it works

**Comment by zj-insist** [comment]
thanks for your help~
