### ISSUE TITLE
Add disabled option to config which will end extension process if set to true

### ISSUE THREAD

**Issue by ghost** [wakatime/vscode-wakatime#141]
I work on the internal systems team at a small software company. We all develop in the same vscode devcontainer environment. 
I would like to add the wakatime extension to the container but give my team mates the option to opt-out. The way that the extension currently works would provide a bad experience for those opting out as it prompts for the API key multiple times. 

I would like to add a disabled option to the config. If this option is set to true then the extension will call process.exit. Will put up a PR for the issue.

**Comment by mattseddon** [comment]
Hi, I raised this issue and subsequently merged my accounts. Hence the ghost above.

**Comment by mattseddon** [comment]
@gandarez would you mind having a look at this and the PR?

**Comment by mattseddon** [comment]
@alanhamlett is there any chance of this being addressed?

**Comment by alanhamlett** [comment]
Great idea! We can implement this in the vscode extension first, and add to other extensions in the future.

**Comment by alanhamlett** [comment]
Released in v4.0.8.
