### ISSUE TITLE
"Command not found" when using new bash window in ubuntu

### ISSUE THREAD

**Issue by keymood** [wakatime/vscode-wakatime#146]
I installed wakatime in ubuntu by `pip3 install wakatime` and noticed that it didnt make any `.wakatime.cfg` file so i created it
```
[settings]
debug = false
api_key = my-api-key
hidefilenames = false
```
then opened new bash window and got `$ wakatime: command not found`

**Comment by alanhamlett** [comment]
Is this for VS Code on Ubuntu, or for using wakatime via command line? For just the VS Code plugin, you don't need to manually install the wakatime command line tool as that's handled by the vscode plugin automatically.

**Comment by AbdurRehman26** [comment]
Hey did you solve it ?

**Comment by iiiypuk** [comment]
Need WakaTime install in system by **sudo**.
Installing to `$HOME/.local/bin` not working.

**Comment by vectorcr** [comment]
> Need WakaTime install in system by **sudo**:
> `sudo pip3 install wakatime`
> 
> Installing to `$HOME/.local/bin` not working.

Currently running Pop_os and this resolved my issue.
