### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by rodrigo-lorenzo-leal** [wakatime/vscode-wakatime#15]
Updated Wakatime to version 1.1.13 and got that error after reloading.

I'm running VS Code Version 1.9.1 on Mac OS 10.12.3 

In the console, it says the following 
<img width="289" alt="screen shot 2017-02-17 at 11 49 03 am" src="https://cloud.githubusercontent.com/assets/16991065/23062700/25722e14-f507-11e6-894d-332cbdcb6741.png">

**Comment by joaom182** [comment]
After update Wakatime is not working, follow the logs on console:

![screen shot 2017-02-19 at 17 55 35](https://cloud.githubusercontent.com/assets/3612098/23106475/e034c970-f6cc-11e6-919c-f6bf4108d0f5.png)

**Comment by alanhamlett** [comment]
@joaom182 this was a problem with our api today, but it should sync your offline activity soon.
