### ISSUE TITLE
Fail to Download wakatime-cli 

### ISSUE THREAD

**Issue by soroushahrari** [wakatime/vscode-wakatime#157]
WakaTime wouldn't be initialized because downloading wakatime-cli was failing. This Issue got fixed by downloading and setting wakatime-cli manually, but it always going to try to update.after all, it fails anytime any network request is attempted to s3(checking latest version and downloading latest version). I faced this problem in v4.0.6.you can see the log after fixing the wakatime-cli manually. 
![Screenshot from 2020-08-25 10-24-35](https://user-images.githubusercontent.com/43000713/91152837-b574b000-e6d4-11ea-9dbd-4125ecf5511b.png)
also i tried v4.0.0 to see it has this problem or not, but after a long time it failed to download the wakatime-cli.
![Screenshot from 2020-08-25 13-10-19](https://user-images.githubusercontent.com/43000713/91152931-d1785180-e6d4-11ea-82a6-72baca4ad312.png)
again after setting the wakatime-cli manually i have this problem
![Screenshot from 2020-08-25 13-32-09](https://user-images.githubusercontent.com/43000713/91154957-6b40fe00-e6d7-11ea-8d4f-a7fa9b1850eb.png)

**Comment by soroushahrari** [comment]
> WakaTime wouldn't be initialized because downloading wakatime-cli was failing. This Issue got fixed by downloading and setting wakatime-cli manually, but it always going to try to update.after all, it fails anytime any network request is attempted to s3(checking latest version and downloading latest version). I faced this problem in v4.0.6.you can see the log after fixing the wakatime-cli manually.
> ![Screenshot from 2020-08-25 10-24-35](https://user-images.githubusercontent.com/43000713/91152837-b574b000-e6d4-11ea-9dbd-4125ecf5511b.png)
> also i tried v4.0.0 to see it has this problem or not, but after a long time it failed to download the wakatime-cli.
> ![Screenshot from 2020-08-25 13-10-19](https://user-images.githubusercontent.com/43000713/91152931-d1785180-e6d4-11ea-82a6-72baca4ad312.png)
> again after setting the wakatime-cli manually i have this problem
> ![Screenshot from 2020-08-25 13-32-09](https://user-images.githubusercontent.com/43000713/91154957-6b40fe00-e6d7-11ea-8d4f-a7fa9b1850eb.png)

I'm wandering maybe it has something to do with amazon blocking iranians so i tried this with a vpn but after a long time there was no response. by the way I'm able to download the file manually when i'm using a vpn.

**Comment by gandarez** [comment]
Is the problem solved? Is somthing related to blacklisted IPs from Iran?

**Comment by soroushahrari** [comment]
> Is the problem solved? Is somthing related to blacklisted IPs from Iran?
I checked it again,yeah the problem is IRAN.even for downloading wakatime-cli manually, i have to use a vpn :)

**Comment by fakhamatia** [comment]
@soroushahrari I download `wakatime-cli.zip` , Where do I extract?

amazon block Iran
Iran government block amazon

**Comment by soroushahrari** [comment]
> @soroushahrari I download `wakatime-cli.zip` , Where do I extract?
> 
> amazon block Iran
> Iran government block amazon

~/.vscode/extensions/wakatime.vscode-wakatime-(version)/

**Comment by GEeKkk** [comment]
> @soroushahrari I download `wakatime-cli.zip` , Where do I extract?
> 
> amazon block Iran
> Iran government block amazon

Could you please tell me where to download the zip file? I didn't find it.

**Comment by fakhamatia** [comment]
> Could you please tell me where to download the zip file? I didn't find it.

Enable `wakatime debug mode` and use `toggle develop tools`

**Comment by alanhamlett** [comment]
This should be fixed once we stop using Amazon S3 for hosting wakatime-cli artifacts.

**Comment by alanhamlett** [comment]
Try adding these lines to your `~/.wakatime.cfg` file:

```
standalone = false
alpha = true
```

**Comment by fakhamatia** [comment]
> Try adding these lines to your `~/.wakatime.cfg` file:
> 
> ```
> standalone = false
> alpha = true
> ```
> 
> Then restart VS Code. Does that fix it?

Add config and Update to Wakatime 6.0.1 and log:
![image](https://user-images.githubusercontent.com/20030910/117032401-b4415b80-ad16-11eb-9d8f-afaffba36e19.png)
![image](https://user-images.githubusercontent.com/20030910/117032404-b4d9f200-ad16-11eb-9dc6-940b56091df8.png)

This is OK? right?

**Comment by alanhamlett** [comment]
Yes! The plugin downloaded the new Go wakatime-cli from GitHub Releases instead of using AWS S3. Looks good!
