### ISSUE TITLE
Stuck on 'WakaTime Initializing...'

### ISSUE THREAD

**Issue by Destaq** [wakatime/vscode-wakatime#158]
No WakaTime data is being tracked, and in Visual Studio Code at the bottom status bar, all I see is WakaTime Initializing...

I know that this has happened before, is this is a known bug/issue at the moment, or are there steps that I can take to correct this?

**Comment by Destaq** [comment]
After over a day of failure, WakaTime seems to be back up and working for me.

**Comment by alanhamlett** [comment]
Yes, there was a known issue yesterday with a bug in a release.

Duplicate of #156, please upgrade the plugin to v4.0.6 to fix this issue:

https://github.com/wakatime/vscode-wakatime/issues/156#issuecomment-679155558
