### ISSUE TITLE
Support for tracking time spent in built-in vscode Terminal window

### ISSUE THREAD

**Issue by kkroeger93** [wakatime/vscode-wakatime#159]
Hello Community, 

unfortunately, the VSCode Plugin does not track work that has been made inside the integrated VSCode-Terminal.

According to the officially supported editor plugins for Wakatime, it's suggesting to not use both, VScode and Terminal Wakatime Plugin. 

How can we fix this issue instead?

**Comment by gandarez** [comment]
VSCode simply opens (emulates) a terminal inside it. If I understood correctly you'll have to have installed wakatime plugin for your terminal also.
