### ISSUE TITLE
sFTP not working

### ISSUE THREAD

**Issue by VladimirVecera** [wakatime/vscode-wakatime#161]
For work I use 80% sFTP approach for work on VScode. Unfortunately, sFTP wakatime does not work. Is there a fix solution when at least counting the time u wakatime over sFTP will work? Rich time is enough. I will be very happy for a functional solution.

**Comment by gandarez** [comment]
If I understood correctly you need a way to measure your time while downloading/uploading files using sFTP extension?

**Comment by VladimirVecera** [comment]
If there is no other option, it can be. Measure the time between download and upload.

**Comment by PLmbond** [comment]
I use the `ssh fs` extension to work remotely. I am having the same issue where it is unable to track time for remote files. I get the following message in the log file: 

```{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:73","func":"SendHeartbeats","level":"warning","message":"file '\\path\\to\\file.js' does not exist. ignoring this heartbeat","now":"2021-08-12T12:36:42-07:00","version":"v1.18.10"}``` 

Is there any update for this issue?

**Comment by alanhamlett** [comment]
Duplicate of #67.

**Comment by alanhamlett** [comment]
Related to #623, which added support for `ssh://` and `sftp://` remote files.
