### ISSUE TITLE
not working when using glitch extension 

### ISSUE THREAD

**Issue by xAdvitya** [wakatime/vscode-wakatime#162]
I'm using glitch extension to work on a projct and waka timer doesn't starts its only stuck on the time when I was workin on some different project which is not on glitch 

![Screenshot (440)](https://user-images.githubusercontent.com/54709416/91943241-e29b1100-ed19-11ea-8713-5aebd353945f.png)

**Comment by alanhamlett** [comment]
Is this still an issue with the latest wakatime version?
