### ISSUE TITLE
Coding Time is no longer visible in VSCode

### ISSUE THREAD

**Issue by fromage9747** [wakatime/vscode-wakatime#165]
Recently my VScode stopped showing the coding time in the VScode application like the below:

![image](https://user-images.githubusercontent.com/23147783/93585474-0f654e80-f9d1-11ea-8b2e-04a479f33ba6.png)

I now just have this:

![image](https://user-images.githubusercontent.com/23147783/93585591-3a4fa280-f9d1-11ea-9042-c10d4b26b339.png)

Wakatime is still registering the time I send coding and it is available online but it's just no longer showing in the VScode application anymore. 

When I right-click on the taskbar of VScode I have all my other options there that I can enable and disable but there is no more Wakatime.

Has something changed in a recent update?

**Comment by gandarez** [comment]
Hi,

On VSCODE type CTRL + P (⌘ + P on Mac) and type `>WakaTime: Status Bar Enabled` then set it to true. After that if you want to show your coding time type `>WakaTime: Status Bar Coding Activity` then set it to true.

**Comment by fromage9747** [comment]
@gandarez Thanks chap! I now have it back!

**Comment by mayconmesquita** [comment]
Here i pressed `CTRL + Shift + P`. Thanks man!
