### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by BudiSalah** [wakatime/vscode-wakatime#167]
- Issue Type: `Bug`
- Extension Name: `vscode-wakatime`
- Extension Version: `4.0.9`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.49.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 392,
		"activateCallTime": 3,
		"activateResolvedTime": 93,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "WakaTime.vscode-wakatime",
				"_lower": "wakatime.vscode-wakatime"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by gandarez** [comment]
What's the problem?

**Comment by BudiSalah** [comment]
The extension refuses to load, It will work thus after restarting the IDE, This happened often.

**Comment by alanhamlett** [comment]
Should be fixed on the latest plugin version.
