### ISSUE TITLE
Can Not Update

### ISSUE THREAD

**Issue by TheCynicalLiger** [wakatime/vscode-wakatime#168]
can not update although it says 4.0.9 is out

![1602791430](https://user-images.githubusercontent.com/9284733/96179719-34de6d00-0f29-11eb-8785-0502653ec253.png)

**Comment by gandarez** [comment]
It's something we can't control. The update process is done by the VSCODE.

**Comment by TheCynicalLiger** [comment]
im pretty sure its up to you what version is on the vs code store. maybe it needs a release version for it to update?

**Comment by gandarez** [comment]
I meant the version is already up to date at the marketplace. 
<img width="698" alt="Screen Shot 2020-10-19 at 14 42 47" src="https://user-images.githubusercontent.com/782854/96492053-0b675f00-1211-11eb-93da-e4bc9864c0cd.png">

**Comment by TheCynicalLiger** [comment]
oh that works if i download it and install it from the .vsix file
