### ISSUE TITLE
Wasting space on the status bar

### ISSUE THREAD

**Issue by carlosvigil** [wakatime/vscode-wakatime#17]
There's no option to disable the status bar line "WakaTime Active", it's unnecessary. I'd further suggest to have it off by default. A notification banner would be better as it can disappear quickly, and be more readily seen when *there are* connection issues.

**Comment by alanhamlett** [comment]
Fixed with fd22756be6fedf3be8311ba3acfe529b06c29a67 and released with v1.1.5.
