### ISSUE TITLE
Support for Onivim 2

### ISSUE THREAD

**Issue by sklirg** [wakatime/vscode-wakatime#173]
Hi there,

I'm using an editor which reuses the VSCode extensions (https://github.com/onivim/oni2#goals).

WakaTime reports my code usage as in VSCode while I'm using Onivim2.

Would it be possible to somehow specify the name of the editor in configuration, user-configurable (or if it could be done automagically)?

I'm not familiar with the WakaTime API or VSCode extensions so I'm not sure if this would be possible or how it would be possible.

**Comment by alanhamlett** [comment]
This line defines the editor name sent to WakaTime's API. We just need to detect Onivim2 accordingly there, and then backfill the editor for your account:
https://github.com/wakatime/vscode-wakatime/blob/6eef837accabe1e6ac2f79cb454bac1e3d166fc9/src/wakatime.ts#L54

**Comment by alanhamlett** [comment]
Added support for `Onivim 2` app name with 89e3a51baf053125be6d03e598b03afc923828f8. Will release a new extension version today.

**Comment by alanhamlett** [comment]
Release v4.0.10.

**Comment by bryphe** [comment]
Thanks @alanhamlett !

**Comment by sklirg** [comment]
Thanks a lot for the help, @alanhamlett. Onivim 2 uses the open-vsx marketplace, and this site[0] tells me that _you_ have published the plugin there before. Could I request a publish to that marketplace as well?

Happy holidays 🥰

0: https://open-vsx.org/extension/WakaTime/vscode-wakatime

**Comment by alanhamlett** [comment]
Thanks @sklirg, had forgotten about the second marketplace. Just published v4.0.10 to ovsx.
