### ISSUE TITLE
Visual Studio Code Heartbeats category field is always null

### ISSUE THREAD

**Issue by hassanelferga** [wakatime/vscode-wakatime#174]
I have noticed that the VSCode plugin is sending the Category field in Heartbeats as null. I had enabled the debug mode and noticed that it logs category=None. 
Here is a sample of the log file
{"now": "2020/12/10 13:46:03 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600762.1330833, "caller": "wakatime\\api.py", "lineno": 51, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "[{'time': 1607600762.1330833, 'entity': 'C:/Users/user/.wakatime.log', 'type': 'file', 'category': None, 'is_write': False, 'project': None, 'branch': None, 'language': None, 'dependencies': [], 'lines': 1464, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:46:05 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600762.1330833, "caller": "wakatime\\api.py", "lineno": 302, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:46:17 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600775.8370533, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:46:17 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600775.8370533, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:46:17 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600775.8370533, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607600775.8370533, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 43, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:46:19 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600775.8370533, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:46:51 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600810.6590648, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\dependencies.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:46:51 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600810.6590648, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\dependencies.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:46:51 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600810.6590648, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\dependencies.ts", "level": "DEBUG", "message": "[{'time': 1607600810.6590648, 'entity': 'D:/Work/waka vscode plugin/src/dependencies.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 500, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:46:54 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600810.6590648, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\dependencies.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:47:20 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600839.6892726, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:47:20 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600839.6892726, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:47:20 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600839.6892726, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607600839.6892726, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 43, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:47:23 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600839.6892726, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:47:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600862.2621357, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\wakatime.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:47:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600862.2621357, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\wakatime.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:47:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600862.2621357, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\wakatime.ts", "level": "DEBUG", "message": "[{'time': 1607600862.2621357, 'entity': 'D:/Work/waka vscode plugin/src/wakatime.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 558, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:47:46 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600862.2621357, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\wakatime.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:49:34 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600973.0081866, "caller": "wakatime\\logger.py", "lineno": 56, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "Traceback (most recent call last):\n  File \"wakatime\\stats.py\", line 114, in guess_lexer_using_filename\n  File \"wakatime\\stats.py\", line 334, in custom_pygments_guess_lexer_for_filename\npygments.util.ClassNotFound: no lexer for filename '.wakatime.log' found\n"}
{"now": "2020/12/10 13:49:34 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600973.0081866, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "Parsing dependencies not supported for unknown.UnknownParser"}
{"now": "2020/12/10 13:49:34 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600973.0081866, "caller": "wakatime\\api.py", "lineno": 45, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:49:34 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600973.0081866, "caller": "wakatime\\api.py", "lineno": 51, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "[{'time': 1607600973.0081866, 'entity': 'C:/Users/user/.wakatime.log', 'type': 'file', 'category': None, 'is_write': False, 'project': None, 'branch': None, 'language': None, 'dependencies': [], 'lines': 1485, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:49:36 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607600973.0081866, "caller": "wakatime\\api.py", "lineno": 302, "file": "C:\\Users\\user\\.wakatime.log", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:51:50 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601110.3963146, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:51:50 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601110.3963146, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:51:50 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601110.3963146, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607601110.3963146, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 43, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:51:52 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601110.3963146, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 13:52:56 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601176.0648081, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 13:52:57 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601176.0648081, "caller": "wakatime\\api.py", "lineno": 45, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 13:52:57 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601176.0648081, "caller": "wakatime\\api.py", "lineno": 51, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607601176.0648081, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': True, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 46, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 13:52:59 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607601176.0648081, "caller": "wakatime\\api.py", "lineno": 302, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 14:07:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602063.0499532, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 14:07:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602063.0499532, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 14:07:43 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602063.0499532, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607602063.0499532, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 46, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 14:07:44 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602063.0499532, "caller": "wakatime\\api.py", "lineno": 302, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 14:07:54 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602073.9761057, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 14:07:54 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602073.9761057, "caller": "wakatime\\api.py", "lineno": 45, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 14:07:54 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602073.9761057, "caller": "wakatime\\api.py", "lineno": 51, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607602073.9761057, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': True, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 43, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
{"now": "2020/12/10 14:07:55 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602073.9761057, "caller": "wakatime\\api.py", "lineno": 302, "is_write": true, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "{'response_code': 201, 'results': [[None, 201]]}"}
{"now": "2020/12/10 14:15:39 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602539.2985036, "caller": "wakatime\\dependencies\\__init__.py", "lineno": 145, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Parsing dependencies not supported for javascript.TypeScriptParser"}
{"now": "2020/12/10 14:15:39 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602539.2985036, "caller": "wakatime\\api.py", "lineno": 45, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "Sending heartbeats to api at http://127.0.0.1:3000/api/heartbeat"}
{"now": "2020/12/10 14:15:39 +0200", "version": "13.0.7", "plugin": "vscode/1.51.1 vscode-wakatime/4.0.9", "time": 1607602539.2985036, "caller": "wakatime\\api.py", "lineno": 51, "file": "D:\\Work\\waka vscode plugin\\src\\logger.ts", "level": "DEBUG", "message": "[{'time': 1607602539.2985036, 'entity': 'D:/Work/waka vscode plugin/src/logger.ts', 'type': 'file', 'category': None, 'is_write': False, 'project': 'waka vscode plugin', 'branch': None, 'language': 'TypeScript', 'dependencies': [], 'lines': 43, 'lineno': None, 'cursorpos': None, 'user_agent': 'wakatime/13.0.7 (Windows-10-10.0.19041-SP0) Python3.8.1.final.0 vscode/1.51.1 vscode-wakatime/4.0.9'}]"}
[.wakatime.log](https://github.com/wakatime/vscode-wakatime/files/5672693/default.wakatime.log)

**Comment by alanhamlett** [comment]
That's normal because all heartbeats default to `Coding` category after received by the api. Even if you send `"coding"` to the api, it still stores it as `null` in the backend.
