### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by whippingdot** [wakatime/vscode-wakatime#176]
Does wakatime work for vs code insiders. I installed the extension and put the API key and everything but I am doubtful that it worked. Please respond telling if it is compatible with vs code insiders or not.

**Comment by alanhamlett** [comment]
Yes, I've used it with vscode insiders. However, insiders uses new proposed apis which WakaTime might need an update to support. Do you have any error messages in you vscode console window related to wakatime?

**Comment by alanhamlett** [comment]
Just verified the current extension version is working with most recent VS Code Insiders.

**Comment by whippingdot** [comment]
Yes, it works for me. I get my stats. Just at first, I didn't get any stats.
