### ISSUE TITLE
Allow use of global wakatime-cli

### ISSUE THREAD

**Issue by notquiteamonad** [wakatime/vscode-wakatime#177]
As a [NixOS](nixos.org/) user, the binary of wakatime-cli that this extension installs doesn't work as the binary would need patching to work with NixOS's library structure. We have a patched version already for NixOS so this could probably be fixed just by checking for a global installation first and using that (or having the option to use that)

**Comment by alanhamlett** [comment]
For now, you can set the config `standalone = false` in your `~/.wakatime.cfg` that uses the source code Python version of wakatime-cli and should work with Nix. It's not a good solution for long term tho.

**Comment by samueldple** [comment]
Thanks :) That does indeed work for me. I've put together a WIP implementation that accepts a global installation of the binary which provides an alternative for systems without python installed. It needs some cleaning up from its current state and I'm not sure if I've done it in a way which fits with your goals for the API but if you think it's worth pursuing I'll be happy to see it through.

**Comment by notquiteamonad** [comment]
@alanhamlett Sorry - forgot I had marked my PR as WIP, but that should all be ready for review now.
