### ISSUE TITLE
Wakatime does not track on Azure Data Studio with specified installations on MacOS

### ISSUE THREAD

**Issue by findtravishere** [wakatime/vscode-wakatime#179]
As per the title, downloading the plugin through the VSIX file on MacOS allows wakatime to run on Azure Data Studio but the time spent querying data is not tracked within the app. 

I'm running MacOS Catalina 10.15.7 and Version: 1.25.1 of Azure Data Studio.

As per the image attached below, time tracked stays at 0 seconds in both the editor's tracking and on my Wakatime dashboard.
![image](https://user-images.githubusercontent.com/63047970/103404466-a1fbb900-4b8e-11eb-80d9-5ad73ae4a91d.png)

**Comment by alanhamlett** [comment]
Just released v5.0.0 with some Azure Data Studio improvements, but it currently doesn't work without an sql file or notebook file saved on disk.

Are you only editing tables on a remote database without ever editing local files?

**Comment by findtravishere** [comment]
Yup! I'm just connected to a postgres database and querying the files. I assume it wouldn't track unless it's saved right?

**Comment by alanhamlett** [comment]
> I assume it wouldn't track unless it's saved right?

Currently not, but it can if we start logging database connections as the project and use category `App` instead of `Coding`. The problem is I haven't found any Azure Data Studio event to listen that would tell the plugin whenever you're interacting with a database:
https://github.com/Microsoft/azuredatastudio/blob/main/src/sql/azdata.d.ts

**Comment by Infectedwafle** [comment]
Would you be able to track time editing in a new tab that may never be saved to disk?

**Comment by alanhamlett** [comment]
> Would you be able to track time editing in a new tab that may never be saved to disk?

As a workaround, we can have the vscode plugin pass wakatime-cli (the part that reads the current file and sends code stats) the path to a temp file with the contents of the unsaved file.
