### ISSUE TITLE
[WakaTime] [ERROR] Invalid API Key (104); Make sure your API Key is correct!

### ISSUE THREAD

**Issue by theophilenz** [wakatime/vscode-wakatime#18]
I've been trying to set all my information for more than an hour and I can't seem to make Wakatime working. I submitted a correct API key, restarted VSCode, even my computer. In debugging mode it's the same.

**Comment by alanhamlett** [comment]
Are there any error messages in your Vscode Developer Tools or `~/.wakatime.log` file?

[vscode-wakatime troubleshooting](https://github.com/wakatime/vscode-wakatime#troubleshooting)

**Comment by alanhamlett** [comment]
Can you manually check to make sure the `api_key` setting in `~/.wakatime.cfg` matches your key at https://wakatime.com/settings?

**Comment by theophilenz** [comment]
Yes. I did check both of them. They are the same.

**Comment by alanhamlett** [comment]
With debug mode on, what is the response code and error message printed in your `~/.wakatime.log` file?

I'm not seeing any connection from your IP to our API Servers. A proxy is probably returning a `401` response which is the response code WakaTime uses when the api key is wrong. However, in this case it's probably the proxy needing authentication to connect to the internet.

**Comment by theophilenz** [comment]
The message: 
![debug](https://cloud.githubusercontent.com/assets/21353145/25959028/705720a4-3640-11e7-8184-da7af49cd557.PNG)

I couldn't find the log file in $HOME.

**Comment by alanhamlett** [comment]
From Help -> Toggle Developer Tools, what is printed when your run this in Console:
`process.env['USERPROFILE']`

**Comment by theophilenz** [comment]
No it didn't. I was able to work that out. Thanks a lot. Probably a problem with my $HOME path and my terminal.

**Comment by alanhamlett** [comment]
We now force Python to use the same home folder as Vscode in v1.1.8, to better fix this issue.

**Comment by KipchirchirIan** [comment]
I now have this problem and I can't find any solution online that works. How was this solved @theophilenz ??

**Comment by YazanKhatib** [comment]
I am facing the same issue, It was working before and suddenly broke when I started working today @alanhamlett

**Comment by OlivierJM** [comment]
same here, it has been working just fine until today(untouched)

**Comment by ClaireBrione** [comment]
Same too. It appeared that the `api_key` disappeared from my `~/.wakatime.cfg` and I don't know how this happened, but putting it back didn't solve the problem.

**Comment by tongrow** [comment]
same. I updated api key, but it had no effect

**Comment by adekoyejoakinhanmi** [comment]
I'm currently experiencing this and this is the error it's showing:

```
[WakaTime][ERROR] Error: Command failed: /Users/adekoyejoakinhanmi/.vscode/extensions/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli 
--file /Users/adekoyejoakinhanmi/Documents/dev/Verifi/people-ui/components/Nav/index.js --plugin "vscode/1.47.2 vscode-wakatime/4.0.0" 
--alternate-project people-ui --write
```

**Comment by OlivierJM** [comment]
> same here, it has been working just fine until today(untouched)

I think issue with my connectivity once it got restored, I restarted the text editor and wakatime is now working. 
If you are having the same issue I'd recommend restarting the text editor.

**Comment by Destaq** [comment]
Yup, this has happened to me as well.

**Comment by adelchamas96** [comment]
yes it's not working for me too i tried generate new api key /reinstall the extension nothing worked. is this a problem with newer vs code version?

**Comment by shxfee** [comment]
+1

**Comment by will-r-wang** [comment]
+1 same here. I'm getting `[WakaTime] Error 104: Invalid API Key`

**Comment by xage93** [comment]
+1

**Comment by qzmlgfj** [comment]
The same here.
It happened for about 6 hours ago, with`[WakaTime][ERROR] Invalid Api Key (104);`
And I've got `Error: Command failed: c:\Users\Ant\.vscode\extensions\wakatime.vscode-wakatime-4.0.0\wakatime-cli\wakatime-cli.exe --file c:\Users\Ant\Desktop\VSCode\Markdown\MarkDownWork\blog.md --plugin "vscode/1.47.2 vscode-wakatime/4.0.0" --alternate-project MarkDownWork --config C:\Users\Ant\.wakatime.cfg --log-file C:\Users\Ant\.wakatime.log`

**Comment by will-r-wang** [comment]
cc Main Issue is: https://github.com/wakatime/vscode-wakatime/issues/143.

**Comment by kaka-ruto** [comment]
Me too, on Vim. Looks like a bug invalidated all our keys. But no worries @alanhamlett , it happens 😉

**Comment by Bailey-1** [comment]
I'm having the same issue with Xcode, VSCode and Vim all on OSX. They were all working great yesterday. [Status](https://wakatime.com/plugins/status) hasn't seen anything sense 9:00pm yesterday.

But at least I'm not the only one.

**Comment by venanciosouza** [comment]
Me too, on vs code. @alanhamlett  :/

**Comment by NicksIdeaEngine** [comment]
I have this problem via vim. I'll disable the plugin until this gets fixed. I haven't updated anything recently, but tried an update once this problem started this morning. Updates didn't resolve it.

**Comment by giancarlopro** [comment]
+1

**Comment by dlinkoln** [comment]
+1

**Comment by sixsckert** [comment]
+1

**Comment by Juniorpucket** [comment]
I think its a general fault cuz i am experiencing the same issue with VSCode.

**Comment by PabloHdzVizcarra** [comment]
I have the same problem with the api key

**Comment by rnapoli** [comment]
+1

**Comment by VivekAlhat** [comment]
I am facing the similar problem. I regenerated new key and tried with that but still same problem. It was working fine until yesterday.

**Comment by tubin** [comment]
I have the same problem with the api key

**Comment by alanhamlett** [comment]
Sorry, this was me. 😭 I broke the api key parsing last night, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Comment by OlivierJM** [comment]
> Sorry, this was me. 😭 I broke the api key parsing last night, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

I can confirm it is resolved. Thank you

**Comment by rnapoli** [comment]
Issue fixed for me.

**Comment by fruitbang** [comment]
>  `process.env['USERPROFILE']`

what i need to do if 'process.env['USERPROFILE']' returns 'undefined'?
