### ISSUE TITLE
wakatime api key not provided in windows vscode

### ISSUE THREAD

**Issue by shuhaiwen** [wakatime/vscode-wakatime#183]
in windwos10 ,Even if I type in  API key,the error info about "wakatime api key not provided" still there.
![AF9D20CA-1F52-490a-8378-A829D0F23558](https://user-images.githubusercontent.com/46131625/106987850-4f26aa00-67a9-11eb-8f53-27b6a496b9ec.png)

**Comment by jakeisnt** [comment]
Check your wakatime config file at $WAKATIME_HOME/.wakatime.cfg to make sure that that file has your API key declared; if not, add it manually.

If that still doesn't work, post the log found at $WAKATIME_HOME/.wakatime.log

**Comment by shuhaiwen** [comment]
I found the reason，my company's encryption systems cause the problem.it's not the  plugin problem.
