### ISSUE TITLE
Problem: Your service is not available in Iran!

### ISSUE THREAD

**Issue by BaseMax** [wakatime/vscode-wakatime#185]
Hi folks,

I'm Max, a software engineer, I have a technical team and one of my staff are from Iran.
He tried more then 2 weeks and finally not success to config the wakatime plugin on the vscode.

### This is while this plugin installs well in Sublime Text and works.

Finlay, I call him and remote to his desktop and check everything.
I find why the `wakatime` not works in `vscode` editor.

- https://wakatime-cli.s3-us-west-2.amazonaws.com/linux-x86-64/wakatime-cli.zip
- https://wakatime-cli.s3-us-west-2.amazonaws.com/windows-x86-64/wakatime-cli.zip

Currently, The vscode plugin need to download `wakatime-cli` file from AWS server.

### Remember AWS company blocked Iran and your plugin cannot works for Iranian.

I suggest you to upload `wakatime-cli` file to GitHub server and use that direct link, Or anywhere else.

A few screenshots to confirm the description I wrote above:

![s-Clipboard - March 26, 2021 12_04 AM](https://user-images.githubusercontent.com/2658040/112544651-e638d700-8dd4-11eb-81b5-59b78dc3d431.png)

My favorite editor is not vscode and I not use it. But I personally investigated this problem.

P.S: I did solve this problem by download the `wakatime-cli` zip file, and extract it manually in the directory.

Best wishes for your team;

Regards,
Max

**Comment by alanhamlett** [comment]
Yep, we're aware and working to fix this by hosting wakatime-cli on GitHub Releases instead of AWS.

**Comment by alanhamlett** [comment]
Try adding these lines to your `~/.wakatime.cfg` file:

```
standalone = false
alpha = true
```

Then restart VS Code. Does that fix it?

**Comment by alanhamlett** [comment]
Now the plugins download wakatime-cli directly from GitHub releases.

**Comment by BaseMax** [comment]
Super. Good to hear it, Alan.
