### ISSUE TITLE
Does Not detect Jupyter Notebooks (.ipynb files) in VS Code

### ISSUE THREAD

**Issue by uzair-ali10** [wakatime/vscode-wakatime#187]
Wakatime does not detect Jupiter notebooks. I guess it adds time of Jupiter notebooks in the "Others" category

**Comment by MovsisyanM** [comment]
You can go to the [wakatime dashboard](https://wakatime.com/dashboard), click on the "Other" in the pie chart, and add a rule for .ipynb files to be displayed as "Python" or whatever you wish

**Comment by alanhamlett** [comment]
Duplicate of #118.
