### ISSUE TITLE
Wakatime is not tracking time on VS Code (MacOS)

### ISSUE THREAD

**Issue by techwithsam** [wakatime/vscode-wakatime#188]
Am using wakatime to track time on my windows and macOS(VS Code) while it's working on windows(VS Code) just fine but always remain stagnant on macOS(VS Code). any solution to that?

**Comment by alanhamlett** [comment]
Should be fixed with v6.0.4. However, can you share the error message from your vscode dev console window with me before upgrading the plugin?
