### ISSUE TITLE
Wakatime is stuck initializing in VScode

### ISSUE THREAD

**Issue by PedroBern** [wakatime/vscode-wakatime#190]
Wakatime is initializing forever in vscode, what should I do?

![Captura de Tela 2021-05-05 às 10 34 21](https://user-images.githubusercontent.com/39778068/117149300-7df2f300-ad8d-11eb-8577-fd741e09b06c.png)

**Comment by Thefangyi** [comment]
回退到6.0.1

**Comment by Thefangyi** [comment]
go back 6.0.1

**Comment by alanhamlett** [comment]
Should be fixed with v6.0.4. However, can you share the error message from your vscode dev console window with me before upgrading the plugin?

**Comment by philippdormann** [comment]
Hi @alanhamlett 
Just experienced the same problem.
No visible errors in the extension host logs, tho...

v6.0.5 fixed it, thanks 🤙

**Comment by alanhamlett** [comment]
The problem was I forgot to create the `~/.wakatime/` directory if it wasn't already there.

**Comment by PedroBern** [comment]
6.0.5 did not fix for me @alanhamlett

**Comment by PedroBern** [comment]
ah fixed now, but I lost all my log for the day, thanks!
