### ISSUE TITLE
WAKATIME Error in VSCODE

### ISSUE THREAD

**Issue by haroldao** [wakatime/vscode-wakatime#196]
![image](https://user-images.githubusercontent.com/36776278/118844125-ffd53700-b8ca-11eb-8fc5-812966b6dbad.png)

**Comment by alanhamlett** [comment]
Please upgrade the extension to v10.0.0 to fix the error.

**Comment by haroldao** [comment]
> Please upgrade the extension to v10.0.0 to fix the error.

Done ! Issue fixed thanks 🚀

**Comment by alanhamlett** [comment]
What was the error message from your `~/.wakatime.log` file from before the fix?

**Comment by haroldao** [comment]
> What was the error message from your `~/.wakatime.log` file from before the fix?

I haven't checked (sorry)😅😪

**Comment by alanhamlett** [comment]
You can get the error again by adding this line to your `~/.wakatime.cfg` file and reloading vscode:

    legacy_python_cli = false

Then the error will show up in your vscode dev console window, or in your `~/.wakatime.log` file.
