### ISSUE TITLE
No releases to download VSIX file

### ISSUE THREAD

**Issue by kanatkubash** [wakatime/vscode-wakatime#199]
I wanted to use wakatime with Azure Data Studio
Only way to use currently is to download VSIX build , but I cannot see any releases nor tags
Where to get one ?

**Comment by alanhamlett** [comment]
You can download the vsix releases here:

https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime

**Comment by kanatkubash** [comment]
Yes, but I think you cant download specific version from marketplace

**Comment by alanhamlett** [comment]
Yes, you can click `Download` next to a specific version to get the vsix file. For ex:

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/WakaTime/vsextensions/vscode-wakatime/10.0.0/vspackage
