### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GianniM2045** [wakatime/vscode-wakatime#201]
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `10.0.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SUPERU~1\AppData\Local\Temp\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ericcleptonsilva** [comment]
these days I realized that he was having problems when typing code my processor drops to the speed of 0.78 being that it has a speed of 2.30, I did the test with two code editors Android Estudio and VsCode.
passing only report this problem

**Comment by alanhamlett** [comment]
Is this still an issue with the latest version?
