### ISSUE TITLE
Wakatime initialized but not logging code 

### ISSUE THREAD

**Issue by PedroBern** [wakatime/vscode-wakatime#202]
Wakatime was initialized but not logging code today on VSCode.

**Comment by alanhamlett** [comment]
Which version of the plugin, and is this still happening today on v12.0.0?

If it's fixed in v12.0.0 then it's from yesterday's Go wakatime-cli launch, and we could use your help testing if it's fixed. To help, please add this line to your `~/.wakatime.cfg` file and relaunch vscode, then let us know if the error is gone:

    legacy_python_cli = false

**Comment by PedroBern** [comment]
@alanhamlett It's working today, thanks for the response. But it was the second day I lost my logs because of whatever reason in less than 30 days (#190). My company is considering canceling the pro/team plan if it happens again and look for some other solution.

**Comment by alanhamlett** [comment]
Totally understand, and we won't be launching the new wakatime-cli again without fixing this bug.

Some good news: your lost time should be saved on your machine and can be synced by downloading wakatime-cli:
https://github.com/wakatime/wakatime-cli/releases/tag/v1.7.4

Extracting the zip, then running the program from command line with:

`wakatime-cli-windows-amd64.exe --no-ssl-verify --sync-offline-activity 9000`

**Comment by PedroBern** [comment]
@alanhamlett thanks for the solution, whats the command for mac m1?

**Comment by alanhamlett** [comment]
You would need this file:
https://github.com/wakatime/wakatime-cli/releases/download/v1.7.4/wakatime-cli-darwin-arm64.zip

Then extract the binary and run it with:
`./wakatime-cli-darwin-arm64 --no-ssl-verify --sync-offline-activity 9000`
