### ISSUE TITLE
WakaTime Offline

### ISSUE THREAD

**Issue by G1Joshi** [wakatime/vscode-wakatime#206]
For the past few days, I am facing the following error with WakaTime in VS Code.

**WakaTime: working offline... coding activity will sync next time we are online**

Even I am connected to internet and the speed is quite good.

**Comment by alanhamlett** [comment]
Can you turn on debug mode in VS Code (CMD + Shift + P, type `WakaTime Debug`, set to `true`). Then check your `~/.wakatime.log` file for error messages? (CMD + Shift + P, type `WakaTime config file`)

**Comment by G1Joshi** [comment]
@alanhamlett I follow the abovementioned steps and here is what I got

{"now": "2021/05/16 15:59:09 +0530", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621160937.4765837, "level": "WARNING", "message": "{'OSError': 'Could not find a suitable TLS CA certificate bundle, invalid path: C:\\\\Users\\\\Jeevan\\\\.wakatime\\\\wakatime-cli\\\\certifi\\\\cacert.pem', 'traceback': 'Traceback (most recent call last):\\n  File \"wakatime\\\\api.py\", line 98, in send_heartbeats\\n  File \"lib\\\\site-packages\\\\requests\\\\sessions.py\", line 578, in post\\n  File \"lib\\\\site-packages\\\\requests\\\\sessions.py\", line 530, in request\\n  File \"lib\\\\site-packages\\\\requests\\\\sessions.py\", line 643, in send\\n  File \"lib\\\\site-packages\\\\requests\\\\adapters.py\", line 416, in send\\n  File \"lib\\\\site-packages\\\\requests\\\\adapters.py\", line 227, in cert_verify\\nOSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\\\\Users\\\\Jeevan\\\\.wakatime\\\\wakatime-cli\\\\certifi\\\\cacert.pem\\n'}"}

How to handle this warning?

**Comment by alanhamlett** [comment]
First, to sync your coding stats run this command:
`C:\Users\Jeevan\.wakatime\wakatime-cli\wakatime-cli --no-ssl-verify --sync-offline-activity 99999`

Then add this line to your `~/.wakatime.cfg` file and restart vscode:
`legacy_python_cli = false`

If you're still getting an error in your wakatime.log file, the fastest solution is we do a Zoom call so I can help get it working.

**Comment by G1Joshi** [comment]
Thanks @alanhamlett for your kind help.
It's working fine now :)
