### ISSUE TITLE
`vscode-wakatime` on FreeBSD tries to run Linux binary

### ISSUE THREAD

**Issue by wonhyukchoi** [wakatime/vscode-wakatime#207]
Maybe this is one of those "wontfix" issues, but I just wanted to document the behavior of `vscode-wakatime` for FreeBSD users.

First, `wakatime-cli` works great for `vim`.
However, `wakatime-vscode` returns "wakatime error" when using it with the [VS Code port](https://www.freshports.org/editors/vscode).

After the following the debugging instructions, I've found that this line is causing the issue:
```sh
$ home/wonhyuk/.wakatime/wakatime-cli/wakatime-cli --today --plugin "vscode/1.56.2 vscode-wakatime/12.0.0"
ELF interpreter /lib64/ld-linux-x86-64.so.2 not found, error 2
Abort trap
```
Seems like somehow the `wakatime-vscode` extension for the VS Code port on FreeBSD tries to run Linux binaries.

I am using `FreeBSD 13.0-STABLE` on a x86-64 machine.

**Comment by alanhamlett** [comment]
What if you use the new cli, with this line added to your `~/.wakatime.cfg` file?

`legacy_python_cli = false`

Then restart VS Code and let me know if it uses the `wakatime-cli-freebsd-amd64` binary and if it's uploading activity correctly?

**Comment by wonhyukchoi** [comment]
Yup, this solves the issue! This is great because I didn't even expect this to get resolved.
Thanks @alanhamlett .
