### ISSUE TITLE
WakaTime reads the language as "Other" for Python

### ISSUE THREAD

**Issue by Fifirex** [wakatime/vscode-wakatime#209]
Hey!
I recently started with the Dashboard, and I was working on a file that had no extension in the name but was a Python script.

My VScode detects that, but when I look at my Dashboard it reads it as "Other":

![Screenshot 2021-06-28 at 4 07 02 PM](https://user-images.githubusercontent.com/75205458/123623411-05f3f700-d82b-11eb-8d78-20e405bb3ca7.png)

This is the file on VScode:

![Screenshot 2021-06-28 at 4 09 42 PM](https://user-images.githubusercontent.com/75205458/123623616-49e6fc00-d82b-11eb-9413-25c02479d086.png)

**Comment by alanhamlett** [comment]
Fixed with a server-side rule.
