### ISSUE TITLE
Config Parser Error (103) check your wakatime.log file for more detail

### ISSUE THREAD

**Issue by titusfx** [wakatime/vscode-wakatime#21]
My wakatime.log file is empty

when I click on toggle developer tools

 [WakaTime] [ERROR] Error: Command failed: pythonw 
...\.vscode\extensions\WakaTime.vscode-wakatime-1.1.12\out\wakatime-master\wakatime\cli.py --file afile.ts --plugin vscode/1.13.0 vscode-wakatime/1.1.12 --alternate-project  --write --config .wakatime.cfg --logfile  \.wakatime.log

.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] [WakaTime] [ERROR] Config Parsing Error (103); Check your ~/.wakatime.log file for more details.

**Comment by alanhamlett** [comment]
Can you delete your `C:\Users\username\.wakatime.cfg` file and restart Vscode?

**Comment by titusfx** [comment]
Fixed!!! Thanks, the problem is that I lost several months of tracking work, I never look to the "footbar" of vscode. I believe errors like that should have an cache tracking or something.
In any case, thanks

**Comment by MrDesjardins** [comment]
I noticed the same error "wakatime error" in the bottom bar with a tooltip mentioning to look at the .wakatime.log. This file is empty. 

I removed the .cfg file and it worked again after entering the API key.
