### ISSUE TITLE
Makes whole VSCode completely unusable

### ISSUE THREAD

**Issue by Willy-JL** [wakatime/vscode-wakatime#211]
I haven't used vscode much in the last weeks but today I opened it and everything was taking ages to process, extensions were not doing what they were supposed to do, and I couldn't add any newlines to any file! Sure I could write other characters, but I couldn't press enter at all! Opening files took ages and other extensions in the sidebar were hanging.
Seeing other similar issues googling I'm guessing this is somehow related to internet connection, but it's unacceptable for it to completely stop me from even using the damn program if there are connection issues or if I use a VPN (which I do on the daily)!

Please fix this thing, this is ridiculous!

**Comment by alanhamlett** [comment]
If you turn off wifi on your computer does it fix the issue? That will tell us if it's related to slow internet.

**Comment by Willy-JL** [comment]
Disconnected my VPN (Mullvad if it matters) and unplugged the ethernet cord and still happens (I started VSCode after unplugging)

**Comment by alanhamlett** [comment]
Then it's probably not network related.

**Comment by alanhamlett** [comment]
Can book a time on my calendar so we can debug this on Zoom?

https://calendly.com/alan-hamlett/30min

**Comment by alanhamlett** [comment]
Closing until we have more info.

**Comment by MarcelHerzkoenig** [comment]
If I completely disable Mullvad and the daemon, VSCode works. If not, I get XHR-Errors when trying to load extensions
