### ISSUE TITLE
Add separate README for Azure Data Studio

### ISSUE THREAD

**Issue by Charles-Gagnon** [wakatime/vscode-wakatime#213]
Currently the ADS marketplace shows the VS Code README : 

![image](https://user-images.githubusercontent.com/28519865/125839139-730a7d75-77c8-40c5-bb13-515ce1575602.png)

This is confusing, especially since the instructions for installing the extension won't work in Azure Data Studio.

If you have a separate README just for ADS then we can update our gallery to point to that instead so the correct instructions can be displayed there.

**Comment by gandarez** [comment]
https://github.com/microsoft/azuredatastudio/pull/18405
