### ISSUE TITLE
Coding time gap

### ISSUE THREAD

**Issue by itkhansunny** [wakatime/vscode-wakatime#217]
I select "Last week" at my login profile and also in my public profile but why show the **coding time gap** there please explain 

![Screenshot_3](https://user-images.githubusercontent.com/3222972/126219604-64368199-6e6c-4059-a6f1-359ece0dda7d.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/3222972/126219614-3cd73dd5-d792-4e08-9b55-e6dc498ef3e7.jpg)

**Comment by alanhamlett** [comment]
Last week on your public profile actually means https://wakatime.com/dashboard?preset=Last%207%20Days%20from%20Yesterday
