### ISSUE TITLE
Data is not reported in win10 system

### ISSUE THREAD

**Issue by WuChenDi** [wakatime/vscode-wakatime#221]
System: win10

Description: I downloaded and used the plug-in on vscode, but did not report the data, the network test works

![image](https://user-images.githubusercontent.com/31385662/128852690-d44f2608-f16b-49cc-9de5-0d3a2e9aa83e.png)

**Comment by alanhamlett** [comment]
How about with v15.0.0?

**Comment by WuChenDi** [comment]
> How about with v15.0.0?

Thank you. It can be used in v15.0.0
