### ISSUE TITLE
Project-detection doesn't work

### ISSUE THREAD

**Issue by mawoka-myblock** [wakatime/vscode-wakatime#222]
Hello everyone!
## My Problem
I am working in a folder called `sth` (for example) and the project gets tracked as `mawoka`. I have the following folder structure on Linux, where the problem occurs: `/home/mawoka/Mawoka/sth` and, how I said, it gets tracked as project `mawoka` but it should be `sth`. Btw: the rest seams to be tracked correctly.

**Comment by alanhamlett** [comment]
Which folder is the root of your Git repo?

**Comment by mawoka-myblock** [comment]
The git-repo was in `/home/mawoka` but I think, it should only check one parent-folder for a git-repo and not 2 or more

**Comment by alanhamlett** [comment]
It looks in all parent folders and stops when it finds a `.git` folder, which is the root of the Git repo.

**Comment by mawoka-myblock** [comment]
I see but I think it makes more sense if it scans only one parent foler
