### ISSUE TITLE
Wakatime gets marked as a Trojan virus for me

### ISSUE THREAD

**Issue by LFGaming** [wakatime/vscode-wakatime#224]
Hi,
The wakatime plugin for vscode (at least that one, don;t know if there are more that have this) gets marked as a Trojan virus for my computer. If you guys could fix this then that would be awesome, since I now can't keep my stats anymore...
This is only since the last update, or at least recently, since earlier this week it did not have this problem.
Screenshot of my virus scanner below.
![image](https://user-images.githubusercontent.com/38732192/130335065-2c47ee24-a30a-430e-91f8-82b1fd14b500.png)

Thanks,
LFGaming

**Comment by alanhamlett** [comment]
Related to https://github.com/wakatime/wakatime-cli/discussions/512.

**Comment by alanhamlett** [comment]
We've submitted the wakatime-cli binary to Windows Defender as a false positive, so hopefully soon it stops being blocked.

**Comment by LFGaming** [comment]
Ah, then ill close this comment and wait a bit. thanks
