### ISSUE TITLE
Data has been disappeared (27-29 August) on dashBoard.

### ISSUE THREAD

**Issue by yeasin50** [wakatime/vscode-wakatime#227]
I think it is missing since today or last day. 

Here is a screenshot from `.wakatime.log` file 

![Screenshot 2021-09-01 113947](https://user-images.githubusercontent.com/46500228/131618998-044afb21-02d1-4046-81ba-6d3ace600c0b.png)

**Comment by alanhamlett** [comment]
What's the number printed when you run this command (replacing `darwin-amd64` with your platform and arch):

`~/.wakatime/wakatime-cli-darwin-amd64 --offline-count`

**Comment by yeasin50** [comment]
I'm using windows10, and ran
 `~/.wakatime/wakatime-cli-windows-amd64 --offline-count`
 
 and getting output `0`

**Comment by alanhamlett** [comment]
Since there aren't any offline stats in the new wakatime-cli, you can try syncing the old wakatime-cli with this command:
`~/.wakatime/wakatime-cli/wakatime-cli --sync-offline-activity 1000`

**Comment by yeasin50** [comment]
thanks it worked
