### ISSUE TITLE
Data has disappeared since 9.3 on dashborad

### ISSUE THREAD

**Issue by lixk28** [wakatime/vscode-wakatime#232]
My dashboard shows there's no coding activity since 9/3.
![2021-09-07_23-39-38](https://user-images.githubusercontent.com/57862491/132373058-dcdeb02d-9f8a-4b48-a8ad-a08cf6f5df5e.png)

Wakatime plugin reports an error on the bottom left status bar. The error has been existing for a few days, but the plugin still works until 9/3.
![2021-09-07_23-42-03](https://user-images.githubusercontent.com/57862491/132373582-f81f5a0e-2928-4b3c-a0e4-d8e437d02af9.png)

Here's a screenshot from my `.wakatime.log` file:
![2021-09-07_23-33-02](https://user-images.githubusercontent.com/57862491/132372265-2cf7bbfc-2afb-483f-93b6-530fc728da43.png)

I tried the command mentioned in #227, but it throw an error:
![2021-09-07_23-38-25](https://user-images.githubusercontent.com/57862491/132372975-1b39d3f0-ff4f-4c43-b4a3-5c91c9ba34b8.png)

Environment:
- OS: Ubuntu 20.04.3 LTS x86_64
- VSCode Version: 1.60.0
- VSCode-Wakatime Version: 17.0.0

**Comment by alanhamlett** [comment]
The error message shown says your `~/.wakatime.cfg` file is corrupted. Can you please paste it's contents here, **with your api key removed**?

To fix this, clear out your `~/.wakatime.cfg` file so it's contents have only `[settings]` on the first line and `apikey = <yourkey>` on the second line. Then reload vscode and it should work again.

**Comment by lixk28** [comment]
It worked, thanks a lot!
