### ISSUE TITLE
McAfee reports a trojan virus alert to me.

### ISSUE THREAD

**Issue by lu1770** [wakatime/vscode-wakatime#233]
McAfee reports a trojan virus alert to me. 
![image](https://user-images.githubusercontent.com/5009902/132436384-870ad1ee-f8ff-45c0-b53b-b229b30b2cb4.png)
It appears that wakatime download an executable program for me.

**Comment by alanhamlett** [comment]
Yes, it downloads the open-source [wakatime-cli](https://github.com/wakatime/wakatime-cli) which is used by all the WakaTime plugins for common components, such as sending code stats to the API.

I think there's no way around this, besides manually allowing it if you have the ability to.

**Comment by alanhamlett** [comment]
Since McAfee deleted wakatime-cli, to get WakaTime working again please manually download and extract the windows zip file for the latest release into `C:\Users\<user>\.wakatime\` from [the releases page](https://github.com/wakatime/wakatime-cli/releases).

**Comment by kumartul** [comment]
There is no issue. You can download it without any tension
