### ISSUE TITLE
Initialization failed on Windows

### ISSUE THREAD

**Issue by zhtjtcz** [wakatime/vscode-wakatime#240]
My Wakatime hasn’t been working properly since August. This is the output from the log file：

```
{"now": "2021/10/11 22:16:31 +0800", "version": "13.0.7", "plugin": "Python/2021.2.2 Python-wakatime/13.1.0", "time": 1633961766.42, "caller": "wakatime\\api.py", "lineno": 302, "file": "my file", "level": "DEBUG", "message": "{'response_code': 202, 'results': [[{'data': {'id': '3bbbae0a-6294-4b3c-9c9c-61a7ddda1cdf'}}, 201]]}"}
```

I have installed the latest version, but nothing works. So how can I fix it?

**Comment by alanhamlett** [comment]
How about with the latest version?

**Comment by alanhamlett** [comment]
Also, try turning on debug mode to get some more logs since that log is from August from when the plugin was working.

**Comment by zhtjtcz** [comment]
I solved this problem by changing the proxy settings on my computer. Now it’s working properly.
