### ISSUE TITLE
error with WakaTime in VS Code

### ISSUE THREAD

**Issue by StupnikovVG** [wakatime/vscode-wakatime#243]
For the past few weeks, I am facing the following error with WakaTime in VS Code.

WakaTime: working offline... coding activity will sync next time we are online.
Here is wakatime log file
[wakatime error.txt](https://github.com/wakatime/vscode-wakatime/files/7520421/wakatime.error.txt)

**Comment by BiosElement** [comment]
I've been having a similar issue, for some reason it seems like the DNS isn't working with VSCode, but works elsewhere...

**Comment by alanhamlett** [comment]
Does it always show `working offline` or does it sync to the dashboard sometimes?

**Comment by StupnikovVG** [comment]
> Do you have a firewall or corporate proxy that could be blocking the connections to the WakaTime API?

In my case, it really was a proxy that began to block the connection. The sysadmin fixed it and now it works. Thanks.

**Comment by jokereven** [comment]
i meet this problem in my vscode in arhc of windows' a little time age it's okay to use but about one week age it's not work, i find this problem by wakatime debug i find it's my wsl proxy to cause, i only use all_proxy like "sock5:ip:port" i add http_proxy and https_proxy to my arch wsl okay, peace.
