### ISSUE TITLE
Support Remote Development

### ISSUE THREAD

**Issue by kigrup** [wakatime/vscode-wakatime#244]
Wakatime doesn't track time when you work through ssh with the "Remote Development" official extension pack. Would be nice to have this feature since I spend a lot with remote projects.

**Comment by alanhamlett** [comment]
Related to #161, #130, #117 and #67.

**Comment by alanhamlett** [comment]
Related to #623, which added support for `ssh://` and `sftp://` remote files.

**Comment by gandarez** [comment]
Can it be closed?

**Comment by alanhamlett** [comment]
I think so. @kigrup does the `Remote Development` extension work for you now with WakaTime?

**Comment by kigrup** [comment]
Works perfectly, thanks!
