### ISSUE TITLE
Add support of processing(.pde) files

### ISSUE THREAD

**Issue by Mongar23** [wakatime/vscode-wakatime#245]
Currently when working on a `.pde` file is logged as `other` programming language. It would be nice to see that it would be logged as `processing` of `java`.

**Comment by gandarez** [comment]
@alanhamlett what do you think of adding `Processing` lexer to Chroma and then rely on wakatime-cli when detecting `*.pde` files?

**Comment by alanhamlett** [comment]
> @alanhamlett what do you think of adding `Processing` lexer to Chroma and then rely on wakatime-cli when detecting `*.pde` files?

Great idea!

**Comment by gandarez** [comment]
Lexer added to Chroma https://github.com/wakatime/chroma/commit/e15e6988abf4d062b69a0ba7b239207b61637bca
