### ISSUE TITLE
Add Environment Variable for api_url

### ISSUE THREAD

**Issue by jimmybrancaccio** [wakatime/vscode-wakatime#246]
I am a Hakatime user so we specify `api_url` in the `.wakatime.cfg` file. Given that `api_key` is already implemented I can't imagine adding `api_url` would be too difficult. It would be very very much appreciated!

If any further information is necessary to implement this please don't hesitate to let me know. 😁

**Comment by alanhamlett** [comment]
We probably won't add this, because it's not a commonly used setting. We want to keep the editor config simple and only show api key, proxy, and debug checkbox. The `wakatime.cfg` has tons of options, and adding them to editor settings would be too chaotic.
