### ISSUE TITLE
WakaTime Server Down

### ISSUE THREAD

**Issue by kumartul** [wakatime/vscode-wakatime#247]
I think your server is down as I am getting an error in VS Code. It's saying that 'WakaTime api key not provided' and when I tried to visit your website, the server refused to connect. Please fix this as soon as possible

**Comment by alanhamlett** [comment]
We haven't had any downtime lately (https://status.wakatime.com/). Are you behind a corporate proxy, or does your ISP block DigitalOcean servers?

**Comment by Perlkonig** [comment]
I'm having the same problem, at least with VScode. The plugin reports "WakaTime Error" and asks for the API key, which is valid. I even reset it a few days ago to make sure. It recorded my time on the 20th and 23rd, but not the 21st, 22nd, 25th, or today, and I did at least a few hours each day. I'm able to connect to the website fine. It's just the VSCode plugin that's not working.

**Comment by alanhamlett** [comment]
> I'm having the same problem, at least with VScode. The plugin reports "WakaTime Error" and asks for the API key, which is valid. I even reset it a few days ago to make sure. It recorded my time on the 20th and 23rd, but not the 21st, 22nd, 25th, or today, and I did at least a few hours each day. I'm able to connect to the website fine. It's just the VSCode plugin that's not working.

@Perlkonig I've moved your comment into a new issue #251 since it's not related to website loading slowly.
