### ISSUE TITLE
Google Calendar Integration 

### ISSUE THREAD

**Issue by coding-famer** [wakatime/vscode-wakatime#248]
When I use Google Calendar Integration and add some events, the project will be Unknown project and the os will be Unknown os,I have no idea about where i can make a issue.

**Comment by alanhamlett** [comment]
You can [click the time on your durations chart](https://wakatime.com/faq#edit-time) to set a project. Also, you can use [custom rules](https://wakatime.com/faq#language-not-detected) to set the project by matching text in event titles.

**Comment by coding-famer** [comment]
I'd like to know how can I use custom rules, if I don't know the event name in my google calendar
