### ISSUE TITLE
Error in vscode

### ISSUE THREAD

**Issue by Jossdz** [wakatime/vscode-wakatime#25]
![image](https://user-images.githubusercontent.com/23535629/30127528-3bf67f72-9305-11e7-9d5d-70e9e3908420.png)
 i've been had some troubles using wakatime in vscode since i tried to use it in OsWindows

**Comment by gandarez** [comment]
@Jossdz is this error still happening?

**Comment by Jossdz** [comment]
I'm not sure, I already moved on macOS

**Comment by gandarez** [comment]
@Jossdz WakaTime is well tested under both Windows and MacOS and I assume this error is not happening. If you get a new error feel free to open an issue.
