### ISSUE TITLE
WakaTime Error in status bar

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vscode-wakatime#251]
I'm having the same problem, at least with VScode. The plugin reports "WakaTime Error" and asks for the API key, which is valid. I even reset it a few days ago to make sure. It recorded my time on the 20th and 23rd, but not the 21st, 22nd, 25th, or today, and I did at least a few hours each day. I'm able to connect to the website fine. It's just the VSCode plugin that's not working.

_Originally posted by @Perlkonig in https://github.com/wakatime/vscode-wakatime/issues/247#issuecomment-1001202497_

**Comment by aggietallboy** [comment]
Having substantially the same behavior (no error though)... I keep getting prompted for the API key, and it's got the correct key there prepopulated, where i can just hit enter.

I checked the settings file, and see that the key is correct there too.

So far no time getting recorded, though I've been on it ~10-12 hours past couple days.

![image](https://user-images.githubusercontent.com/10222174/154386936-ecd6ca6c-be6d-4af0-98f6-0eb07da6e83a.png)


I do keep getting this in the developer console:
[WakaTime][WARN] Unable to get api key: Error: spawn EPERM

**Comment by gandarez** [comment]
@aggietallboy are you on windows?

**Comment by alanhamlett** [comment]
@aggietallboy thanks for the error message! That shows it's caused by vscode-wakatime not wakatime-cli. Can you update to vv18.0.6 of the plugin, turn on debug mode, then share your vscode dev console logs when it happens again?

**Comment by steventango** [comment]
Hi, also have this issue, on Windows 11, here are the dev console logs with debug mode on:
![image](https://user-images.githubusercontent.com/18170455/154536070-1e120464-80e3-4336-92de-28c8cf4e95ee.png)

Also, Windows Security is flagging Wakatime, might be related
![image](https://user-images.githubusercontent.com/18170455/154536262-d94804ff-ec32-425b-81a3-877502ac12bf.png)

**Comment by alanhamlett** [comment]
Closing as duplicate of #262. Let's move the conversation there.

@steventango the windows security issue is https://github.com/wakatime/wakatime-cli/issues/654

**Comment by aggietallboy** [comment]
I’ll sure try!
