### ISSUE TITLE
Support hiding absolute file paths

### ISSUE THREAD

**Issue by kaushalyap** [wakatime/vscode-wakatime#253]
Currently WakaTime record absolute paths of the source files, with anonymization config it give random names to the project and track file only by file extension. Instead I suggest something like below

For project location :` .../ProjectName/ `instead of `/home/userName/Dir/ProjectName`
For file location : ` .../ProjectName/package.json `instead of `/home/userName/Dir/ProjectName/package.json`

(For Windows I suggest hiding the drive letter.)

This approach is in the middle ground since this has following benefits

- Absolute paths of projects, files are not known which results in better privacy and security.
- You can know which files you spent most time on instead of getting generic stats based on the extension

**Comment by alanhamlett** [comment]
We have a feature request for this at https://github.com/wakatime/wakatime-cli/issues/591, and hope to implement it soon.

**Comment by kaushalyap** [comment]
Actually I opened that issue, I was not able to find that when I searched here, I thought issue was deleted. very sorry my mistake
I'll close this now in favor of that. Thanks for help so far!
