### ISSUE TITLE
Ask for api when offline

### ISSUE THREAD

**Issue by Shirobachi** [wakatime/vscode-wakatime#255]
I was in train with no internet, extension ask me for API key like every 5 seconds what made almost impossible to work ;( 

May you add some option like not now or sth?

**Comment by alanhamlett** [comment]
The api key prompt [doesn't](https://github.com/wakatime/vscode-wakatime/blob/5b26fab4b046dd3155e8c20da0781fa93807f156/src/wakatime.ts#L371) depend on your network connection. So you needed to set your api key but couldn't find it because no internet?

**Comment by Shirobachi** [comment]
I am using wakatime for vscode since months. So that weird, but still it asks me I click ESC and it ask again in ~5secs..

**Comment by alanhamlett** [comment]
If somehow your `~/.wakatime.cfg` file became corrupted and the plugin couldn't read your api key, it would only stop prompting after you enter something that matches the api key format. Just clicking ESC won't prevent it from prompting again the next time it tries to send your code stats.

**Comment by Shirobachi** [comment]
I would not say it's "cool" behavior, but it's ok. Thanks!
