### ISSUE TITLE
VSCode still requiring an API key although one is set inside `.wakatime.cfg`

### ISSUE THREAD

**Issue by mainrs** [wakatime/vscode-wakatime#256]
I'd expect the extension to pick the key from the configuration file automatically without me having to enter it in again.

**Comment by alanhamlett** [comment]
It should... the vscode plugin doesn't have any other way to get your api key. Maybe your `~/.wakatime.cfg` file was corrupted, or vscode encountered an error when reading it?

**Comment by liyuhang1997** [comment]
Sometimes it pops up for no reason and I have to re-enter the API Key

**Comment by mainrs** [comment]
> Sometimes it pops up for no reason and I have to re-enter the API Key.

That’s the behavior I do encounter as well. I double checked it the files. I’ve first created the config file. I then installed the extension. And upon first launching vscode with the extension, it prompted me for the key. Even though the key was present in the confit file.

**Comment by alanhamlett** [comment]
Please send your `~/.wakatime.log` file to support@wakatime.com. What I'm looking for is an error message saying either `failed to read in config` or `invalid api key`. That will tell us if it's asking for your api key because it couldn't read the cfg file, or because the API returned an unauthorized response.

You might need to [turn on debug mode](https://github.com/wakatime/vscode-wakatime#troubleshooting) for the error message to be logged.

**Comment by alanhamlett** [comment]
Also, the next time it asks for your api key before entering it can you send the contents of `~/.wakatime.cfg` to support@wakatime.com? Maybe the cfg file is getting corrupted somehow.

**Comment by liyuhang1997** [comment]
> 请将您的`~/.wakatime.log`文件发送至[support@wakatime.com](mailto:support@wakatime.com)。我正在寻找的是一条错误消息，上面写着`failed to read in config`or `invalid api key`。这将告诉我们它是否因为无法读取 cfg 文件而请求您的 api 密钥，或者因为 API 返回了未经授权的响应。
> 
> 您可能需要[打开调试模式](https://github.com/wakatime/vscode-wakatime#troubleshooting)才能记录错误消息。
> 
> 编辑：另外，下次它在输入之前询问您的 api 密钥时，您可以将 ~/.wakatime.cfg 的内容发送到[support@wakatime.com](mailto:support@wakatime.com)吗？也许cfg文件以某种方式损坏。

`.wakatime.cfg`
```
[internal]
backoff_at      = 2022-01-30T17:18:01+08:00
backoff_retries = 1
```

**Comment by alanhamlett** [comment]
Do you also use Atom with WakaTime? We just [fixed a bug](https://github.com/wakatime/atom-wakatime/blob/987398a6a027834c1fd667ce70202ac9d3fcefe9/HISTORY.rst#1109-2022-01-30) in the atom-wakatime plugin that might have been corrupting your `~/.wakatime.cfg` file in certain cases. If you delete your `~/.wakatime.cfg` file and restart vscode does it start working again?

**Comment by mrgnhnt96** [comment]
I am having this issue as well, it is very annoying. If you try to ignore it, it will pop up every time a file is saved, opened, or closed. It forces you to add the key to stop being bothered by it. Sometimes it will last for a few days without asking again, other times it will ask after a couple of hours

**Comment by alanhamlett** [comment]
@jeetsdev what's the contents of your `~/.wakatime.cfg` file? Please remove your api key before sharing the file.

**Comment by jeetsdev** [comment]
> @jeetsdev what's the contents of your `~/.wakatime.cfg` file? Please remove your api key before sharing the file.

Here it is- 
```
[internal]
backoff_at      = 2022-02-02T09:18:55+05:30
backoff_retries = 1

[settings]
api_key = "my API key"
```

**Comment by alanhamlett** [comment]
That's valid and shouldn't cause the `failed to load command parameters: failed to load api params: failed to load api key` error. Maybe this is a bug in wakatime-cli instead of vscode.

**Comment by l3szcz** [comment]
Yesterday I was encountering the same bug as @mrgnhnt96. I input my key multiple times, disable and enabled wakatime extension (from the command palette) and nothing worked. The extension kept asking me for the api key. Today it's working again with no additional changes on my side 🤷‍♂️

**Comment by alanhamlett** [comment]
Can you try with the latest release just now v18.0.5?

If it's still asking for your api key after updating the plugin, please add a comment here with your:

* OS (Win/Linux/Mac)
* contents of your `~/.wakatime.cfg` file (with api key removed)
* any error messages seen in your vscode [dev console window](https://github.com/wakatime/vscode-wakatime#troubleshooting)
* any logs found in `~/.wakatime.log` around the time the bug occurred

**Comment by l3szcz** [comment]
> Can you try with the latest release just now v18.0.5?
> 
> If it's still asking for your api key after updating the plugin, please add a comment here with your:
> 
> * OS (Win/Linux/Mac)
> * contents of your `~/.wakatime.cfg` file (with api key removed)
> * any error messages seen in your vscode [dev console window](https://github.com/wakatime/vscode-wakatime#troubleshooting)
> * your full log file at `~/.wakatime.log`

@alanhamlett over the past 5 days it seems to bo working correctly. Not once I was asked for the api token and everything is tracked properly.
