### ISSUE TITLE
Jupyter Notebook is labeled as "other"

### ISSUE THREAD

**Issue by mhmmd-ysf** [wakatime/vscode-wakatime#258]
As the title said, my time spent on ipynb files is labeled as "other" despite I've put custom rules (I saw it as other, then I tried to change it into python to see if it's working).
The thing is, it worked just fine last year, then I spent a year not touching any jupyter notebook project until recently when I found out it's not working anymore. Did I miss something?

![Screenshot 2022-01-26 083756](https://user-images.githubusercontent.com/46883609/151088967-b60eac02-3c3a-4c83-8a2f-368f7c1124ba.jpg)
![Screenshot 2022-01-26 083717](https://user-images.githubusercontent.com/46883609/151088983-bd2abe62-3153-43b7-ba84-d28694e6c229.jpg)

**Comment by alanhamlett** [comment]
Your screenshot shows `equals`, but it should be `ends with`. I've fixed it on our end so you can just delete that rule now and it should work without it.
