### ISSUE TITLE
wakatime can't send details

### ISSUE THREAD

**Issue by Koushikphy** [wakatime/vscode-wakatime#259]
Waka time in vscode doesn't work. when I open the vscode for the first time it shows (in the devtools console)
```
[Extension Host] [WakaTime][ERROR] Error: Command failed: /home/user/.wakatime/wakatime-cli-linux-amd64 --today --plugin "vscode/1.63.2 vscode-wakatime/18.0.4"
```

when I open a particular file it shows this error
```
 ERR [Extension Host] [WakaTime][ERROR] Error: Command failed: /home/user/.wakatime/wakatime-cli-linux-amd64 --entity /home/user/index.js --plugin "vscode/1.63.2 vscode-wakatime/18.0.4" --lineno 1 --cursorpos 1 --lines-in-file 533 --alternate-project MyProject
```
Please help me to debug and fix this issue.

NOTE: I'm on my institute network, and it uses proxy with username/password authentication for internet

**Comment by alanhamlett** [comment]
Is your proxy configured in `~/.wakatime.cfg`?

**Comment by Koushikphy** [comment]
Okay, so my username has a space in it, I usually use `%20` in place of space in proxy configuration files like `/etc/apt/apt.conf`, but here wakatime complains it as

```python
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found:
```

**Comment by alanhamlett** [comment]
So it works without the `%20` in your proxy url?
