### ISSUE TITLE
Conflict with Markdown+Math plugin

### ISSUE THREAD

**Issue by lmatt-bit** [wakatime/vscode-wakatime#26]
Is there any special logic to deal dollar sign in markdown doc? If wakatime plugin is enabled, then the math equation(starts and ends with two continuous dollars) won't be able to display correctly. 

More details please refer to [this issue](https://github.com/goessner/mdmath/issues/33)

**Comment by alanhamlett** [comment]
There's nothing in WakaTime that would conflict with [Markdown+Math](https://github.com/goessner/mdmath). Can you double check to make sure it's related to WakaTime being enabled?

**Comment by lmatt-bit** [comment]
Sure, i have tested this for many times. The math equation is correctly showing when i disabled the WakaTime plugin. You can have a try with using below markdown. 

```md
# Test

$$
h_t = f (x_t, h_{t-1})
$$
```

**Comment by alanhamlett** [comment]
Found the problem, and fixed in v1.1.16. Thanks!

**Comment by goessner** [comment]
Thanks for fixing .. !

Why not conditionally overwriting / polyfilling via ..

```js
String.prototype.startsWith = String.prototype.startsWith || function(searchString, position) { ... }
```
see [mdn](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)  ... I am simply expecting above method(s) being implemented in modern node/browser.

**Comment by alanhamlett** [comment]
It's safer to not overwrite built-ins at all, so using a util function works fine.
