### ISSUE TITLE
Track WSL as windows instead of Linux 

### ISSUE THREAD

**Issue by brycerohrer** [wakatime/vscode-wakatime#263]
I want to show that my development on wsl is different than my actual linux machine.

**Comment by alanhamlett** [comment]
We're now detecting WSL as Windows on the dashboards.

**Comment by alanhamlett** [comment]
Yea, that makes sense. @brycerohrer another way to show wsl is different from Linux would be the Machine breakdown here:
https://wakatime.com/blog/52-segment-your-code-time

If that works for you we can change WSL back to Linux.

**Comment by alanhamlett** [comment]
WakaTime now supports two new operating systems:

* Unix
* WSL

This solves the problem of detecting WSL as Windows vs Linux.
