### ISSUE TITLE
Show details at hover when disabled "Status Bar Coding Activity"

### ISSUE THREAD

**Issue by renbaoshuo** [wakatime/vscode-wakatime#265]
![Snipaste_2022-03-21_19-13-50](https://user-images.githubusercontent.com/47095648/159250057-ba540ed5-16a3-450a-9a91-51ef45e67c23.png)

I hope to have an option to show coding activities at hover:

![Snipaste_2022-03-21_19-13-05](https://user-images.githubusercontent.com/47095648/159249957-25103af0-9b3c-4065-8835-1f71e527c75f.png)

**Comment by alanhamlett** [comment]
Good idea, I'll add this to the next release.

**Comment by alanhamlett** [comment]
Released in v18.0.8.
