### ISSUE TITLE
WakaTime not automatically recognising VS Code workspaces as projects

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [wakatime/vscode-wakatime#270]
As in the title -- it would be nice if they were, as it is more intentional to create a workspace than just to open a folder, and workspaces pretty much function as projects. If necessary, this could be an optional feature/setting, but it would save having to create a `.wakatime-project` for every workspace in its folder (with the same name as the workspace).

**Comment by alanhamlett** [comment]
Fixed in the latest wakatime-cli release. To get the fix, restart your vscode editor.
