### ISSUE TITLE
Wakatime not working

### ISSUE THREAD

**Issue by Lucifer25x** [wakatime/vscode-wakatime#272]
I have tried installing the Wakatime plugin many times. But wakatime doesn't seem to work.
I also tried creating new account, it didn't work for me.
It was working fine about 1 month ago. But one day it stopped working.

**Comment by alanhamlett** [comment]
After turning on debug mode, what error do you see in your vscode dev console window or `~/.wakatime.log` file?

**Comment by Lucifer25x** [comment]
> 

config files: failed to load configuration file: error parsing config file: While parsing config: key-value delimiter not found:

**Comment by alanhamlett** [comment]
Related to https://github.com/wakatime/wakatime-cli/pull/725?
