### ISSUE TITLE
"Undefined" work session start time

### ISSUE THREAD

**Issue by JoCat** [wakatime/vscode-wakatime#273]
When starting a new working session, the time value is displayed as "undefined"

![image](https://user-images.githubusercontent.com/13483132/167774428-74972f00-99d8-4be0-8808-6bb00e05a778.png)

Plugin version: `v18.1.2`
VS Code info:
> Version: 1.66.2
> Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
> Date: 2022-04-11T07:49:24.808Z
> Electron: 17.2.0
> Chromium: 98.0.4758.109
> Node.js: 16.13.0
> V8: 9.8.177.11-electron.0
> ОС: Linux x64 5.13.0-40-generic

**Comment by KrishAgarwal2811** [comment]
same for me i have the latest vs code version and latest extension version

**Comment by alanhamlett** [comment]
Fixed in v18.1.3.
