### ISSUE TITLE
error parsing config file: error creating new key: empty key name

### ISSUE THREAD

**Issue by JamesLi-dev** [wakatime/vscode-wakatime#274]
![image](https://user-images.githubusercontent.com/26141443/168408714-07dd4793-b979-4e91-9a4c-d6a2a1955969.png)

help！！vsCode wakatime is Can't work
problems after updating 18.1.4

**Comment by alanhamlett** [comment]
What's the contents of your `~/.wakatime.cfg`?

**Comment by JamesLi-dev** [comment]
![image](https://user-images.githubusercontent.com/26141443/168718077-f41dfefb-c069-4ad5-85f9-91ce5cfd0410.png)
this is ~/.wakatime.cfg

**Comment by alanhamlett** [comment]
How about the contents of your `~/.wakatime-internal.cfg` file if it exists?

Does it fix things if you delete that file?

**Comment by JamesLi-dev** [comment]
![image](https://user-images.githubusercontent.com/26141443/168787173-503c7085-3912-44a4-9058-31573a35d439.png)
This is ~/.wakatime-internal.cfg file

**Comment by JamesLi-dev** [comment]
After I deleted this file, I solved it. Thank you

**Comment by JamesLi-dev** [comment]
After I deleted this file, I solved it. Thank you
