### ISSUE TITLE
Regression: not able to configure via environment variable in v18.1.5 with GitPod

### ISSUE THREAD

**Issue by clouedoc** [wakatime/vscode-wakatime#277]
See [reproduction repository here](https://github.com/clouedoc/wakatime-gitpod-repro)

## Error message

![Capture d’écran 2022-06-17 à 21 52 46](https://user-images.githubusercontent.com/13921610/174392732-8a8ae223-0a9e-44b7-98a5-0ae957cb91ed.png)

## Reproduction

CLI version: `v1.49.0`
Extension version: `v18.1.5`

1. Create a gitpod.io account
2. Add the WAKATIME_API_KEY variable here: https://gitpod.io/variables (with value from https://wakatime.com/api-key)
3. Open this repository using GitPod
4. Edit a file to trigger WakaTime reporting
5. You will see the error message
6. Execute `> WakaTime: Api Key` and set your API key manually
7. Edit a file. Everything will work.

## Versions

v18.1.5: reproduces
v18.1.0: OK <-- I'll stay with this version until the bug is resolved
v17.1.0: OK

To test another version, edit `.gitpod.yml`

**Comment by alanhamlett** [comment]
Fixed with b7caad8b2df21cc18cc227e3e562cb0e3c65b8a8 and released in v18.1.6.

**Comment by clouedoc** [comment]
Thank you very much for fixing this bug!
