### ISSUE TITLE
Support Skript Scripting Language

### ISSUE THREAD

**Issue by AyhamAl-Ali** [wakatime/vscode-wakatime#281]
Hello!

Many users use [Skript Scripting Language](https://github.com/SkriptLang/Skript) made using Java for Minecraft coding
so it would be very nice to support that!

Thank you.

**Comment by alanhamlett** [comment]
We're now detecting `.sk` files as `Skript` language. `.java` files will still be detected as `Java`.

**Comment by AyhamAl-Ali** [comment]
Oh that's great! thank you \:)
