### ISSUE TITLE
Allow the wakatime api key to be persisted via settings sync

### ISSUE THREAD

**Issue by Milo123459** [wakatime/vscode-wakatime#283]

**Comment by randollrr** [comment]
I was about to create the very same issue.  I only work in devcontainer (for a clean python env) and I have to re-enter the api key at every mod or new container image.  If we can have it in the user/settings that will save me time.

**Comment by lablnet** [comment]
I use GitHub codespace Whenever I create new codespace I have to enter API key again and again which is just time wasting!

**Comment by alanhamlett** [comment]
I'll work on a PR for this. How about a checkbox to enable saving to vscode settings instead of the `~/.wakatime.cfg` file?

**Comment by exilvm** [comment]
+1

**Comment by wvffle** [comment]
@alanhamlett How are the works on the PR?

**Comment by exilvm** [comment]
For those who use Devcontainers, you can bind `.wakatime.cfg`:
```json
"runArgs": [
  "-v",
  "${env:HOME}/.wakatime.cfg:/root/.wakatime.cfg"
],
```

**Comment by mikebronner** [comment]
> For those who use Devcontainers, you can bind `.wakatime.cfg`:
> 
> ```json
> "runArgs": [
>   "-v",
>   "${env:HOME}/.wakatime.cfg:/root/.wakatime.cfg"
> ],
> ```

Which file is this to be added to? Trying to add it to `devcontainer.json` lints with "Property runArgs is not allowed."

**Comment by exilvm** [comment]
> > For those who use Devcontainers, you can bind `.wakatime.cfg`:
> > 
> > ```json
> > "runArgs": [
> >   "-v",
> >   "${env:HOME}/.wakatime.cfg:/root/.wakatime.cfg"
> > ],
> > ```
> 
> Which file is this to be added to? Trying to add it to `devcontainer.json` lints with "Property runArgs is not allowed."

Please check https://containers.dev/implementors/json_reference/#general-properties

**Comment by kotx** [comment]
@alanhamlett Is work still being done on a PR? If not I might be able to work on this

**Comment by alanhamlett** [comment]
> @alanhamlett Is work still being done on a PR? If not I might be able to work on this

Not yet, so go for it 👍

**Comment by kotx** [comment]
Submitted a PR!

**Comment by Mtrojan21m** [comment]
[https://www.invesco.com/qqq-etf/en/ncaa.html?gclid=CjwKCAiAuOieBhAIEiwAgjCvcgpdizueLuv5XaT0x6DIerq69R90ZAyZa5lZVwSEr9yfo7ZaQcnOuxoC3twQAvD_BwE](https://www.invesco.com/qqq-etf/en/ncaa.html?gclid=CjwKCAiAuOieBhAIEiwAgjCvcgpdizueLuv5XaT0x6DIerq69R90ZAyZa5lZVwSEr9yfo7ZaQcnOuxoC3twQAvD_BwE) #325
