### ISSUE TITLE
Time tracking Error.

### ISSUE THREAD

**Issue by pratikkabade** [wakatime/vscode-wakatime#289]
Its always showing 0 secs
![image](https://user-images.githubusercontent.com/76637730/183569575-1ebd4bf5-6c08-447c-b613-b247c6cb3c06.png)
But in dashboard it is getting updated just not in vs code

I tried 
1. Disabling and reenabling
2. Reinstalling

Issue still persists

**Comment by alanhamlett** [comment]
Should be fixed now?

**Comment by pratikkabade** [comment]
no it isnt.
could you give it another try. and whats happening

**Comment by alanhamlett** [comment]
Sure, I'll look more into it. This response is heavily cached, and we had a bottleneck in our background processing the last few days. Those issues have been fixed now, with the status bar queue normal (zero pending tasks) so it's strange it's not updated. I'll report back here after it's fixed.

**Comment by alanhamlett** [comment]
I can confirm it's fixed now. It was an error in our rate limiting for that endpoint.

**Comment by pratikkabade** [comment]
I really hate to bring this again. but still its not getting fixed on my device.

![image](https://user-images.githubusercontent.com/76637730/183873055-aa64bd52-88f2-4003-8b8d-4a5808eaed1f.png)

Is there anything i have to do from my side?

**Comment by alanhamlett** [comment]
How about now? The deployment might not have been fully finished.

**Comment by pratikkabade** [comment]
Thank you so much it is working now!
