### ISSUE TITLE
Wakatime not showing time

### ISSUE THREAD

**Issue by 11Firefox11** [wakatime/vscode-wakatime#290]
Wakatime is not showing the time.
It updates the time on the dashboard, but I can't see the time here.
I have tried to disable and then enable `Status Bar Coding Activity` from the command palatte, but it changes nothing.
Reinstall changes nothing.

![image](https://user-images.githubusercontent.com/65167877/183849939-4954faad-883b-427a-a801-956cee349cca.png)

**Comment by alanhamlett** [comment]
Same as #288 and #289. Should be fixed now?

**Comment by 11Firefox11** [comment]
Yup, it is fixed. Thanks for the fast reply.
