### ISSUE TITLE
Pie chart legend hidden when too many languages

### ISSUE THREAD

**Issue by Yaminyam** [wakatime/vscode-wakatime#294]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/31057849/185885679-904180a8-712e-4b63-a2da-da553ecd2380.png">

![image](https://user-images.githubusercontent.com/31057849/185886129-a9ac4660-c3ca-4c45-8e85-64f8cb157053.png)
Previously, the time was displayed next to the graph as shown in the picture below, but is there any reason why it suddenly disappeared?

**Comment by alanhamlett** [comment]
We hide the legend when too many languages are in the time range, or else it won't fit on the page.

**Comment by Yaminyam** [comment]
@alanhamlett If there are too many languages, wouldn't it be better to show the time of the top languages?

**Comment by alanhamlett** [comment]
Yea, that requires forking the charting library we use. I'll see if they'll accept a patch.

**Comment by alanhamlett** [comment]
We use [billboard.js](https://naver.github.io/billboard.js/) for our frontend charts, but looks like we have a solution building a custom legend so will get this issue closed today 👍

**Comment by alanhamlett** [comment]
Just released an update to the main dashboard which always shows pie chart legends.
