### ISSUE TITLE
Version 19.1.0 not working, upgrade to 19.2.0

### ISSUE THREAD

**Issue by CMiksche** [wakatime/vscode-wakatime#297]
Today my WakaTime VS Code Extension was updated to 19.1.0 and suddenly it is not working anymore.

It shows "Initialised" and no Issues in the DevTools Console but nothing gets recorded.

I downgraded to 19.0.1 and it worked again.

I tried upgrading and downgrading multiple times and the newer Version definitely has some Issue.

VS Code Version: 1.71.0, Darwin x64 21.6.0

**Comment by Dreamyplayer** [comment]
Had same issue status bar icon stucked at "wakatime: initialized"

Debug error logs says
message: `failed to run command: today fetch failed: failed fetching today from api: bad request at \"https://api.wakatime.com/api/v1/users/current/statusbar/today\`

- restart, re-install nothing works.

✨ Downgrading: v19.0.1 - fixed issue for now.

**Comment by alanhamlett** [comment]
Just rolled back the previous release in v19.2.0.

**Comment by tofupup** [comment]
Same issue running in WSL and an ubuntu based devcontainer.  VSCode 1.71.0, Plugin 19.1.0.  Downgraded to 19.0.1 and problem resolved.  I did not get any error messages when having wakatime in DEBUG, the last message would just be:

`console.ts:137 [Extension Host] [WakaTime][DEBUG] WakaTime initialized`

`~/.wakatime.log` would have an entry:

{"caller":"cmd/run.go:75","func":"cmd.Run","level":"debug","message":"command: version","now":"2022-09-09T16:37:38-05:00","version":"v1.55.1"}

but no errors.

Plugin status page showed the plugin was last seen hours before, then once downgrade started showing recent times.

**Comment by tofupup** [comment]
This appears to have resolved it for me, thanks @alanhamlett for the quick revert!
