### ISSUE TITLE
Error Reading WinReg 

### ISSUE THREAD

**Issue by kidchenko** [wakatime/vscode-wakatime#3]
Hi, How are you?

Well I instaled wakatime but it doesn't work.

See

![image](https://cloud.githubusercontent.com/assets/5432753/11338047/c48018f6-91d8-11e5-8121-74269bea3852.png)

I have Python

![image](https://cloud.githubusercontent.com/assets/5432753/11338093/2c2f1d12-91d9-11e5-9af9-05f66d295936.png)

The log file is empty.

What you think?

**Comment by alanhamlett** [comment]
Is this fixed with v1.0.0?

**Comment by technbuzz** [comment]
It was working last time i checked a week before but now again it's stuck "WakaTime initializing"

**Comment by alanhamlett** [comment]
@technbuzz is this fixed in v1.0.1?

**Comment by technbuzz** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/1523391/11564610/29ab50be-99eb-11e5-8e22-2cb82d25528b.png)
Looks like it's fixed for me :+1:

**Comment by alanhamlett** [comment]
Awesome, thanks for helping!
