### ISSUE TITLE
Incorrect branch tracking with git submodules

### ISSUE THREAD

**Issue by jelder** [wakatime/vscode-wakatime#30]
My current project uses a top-level git repository called `development` which uses in turn uses a git submodule for each of the many microservices that make up the app. WakaTime thinks that I spend all day in `development/master` but in reality, I'm moving between submodules, and between branches within submodules, all day. It would be nice if this workflow were supported better.

**Comment by alanhamlett** [comment]
Fixed with wakatime/wakatime#105

**Comment by jelder** [comment]
Amazing, thank you.
