### ISSUE TITLE
Using global cli option is not documented

### ISSUE THREAD

**Issue by cubercsl** [wakatime/vscode-wakatime#303]
As it is mentioned in https://github.com/wakatime/vscode-wakatime/issues/177 and https://github.com/wakatime/vscode-wakatime/pull/178, we can use some config to use global `wakatime-cli` provided by package manager or something else.

In this plugin, it is now use `global`, but not documented in https://github.com/wakatime/wakatime-cli/blob/v1.55.1/USAGE.md

Maybe we should try to find/use global by default like other plugins (such as vim-wakatime), and then fallback to automatically download.

**Comment by alanhamlett** [comment]
Sounds good, I'll start on a PR.

**Comment by alanhamlett** [comment]
Implemented in v20.0.0 released just now.
