### ISSUE TITLE
Reports all time as "building" when running `npm start`

### ISSUE THREAD

**Issue by Maxim-Mazurok** [wakatime/vscode-wakatime#305]
I have a typical use-case for `npm start` - it runs `vue-cli-service serve` which automatically rebuilds the project and serves it.
This is an infinitely-running task. So it reports all the time as "building", which isn't correct. I write code, it re-compiles, I check the result, and go back to code.
I do realize that this plugin probably has no way of knowing if I'm waiting for build to finish or just running the server script.
Probably the easiest thing to do would be to check if the code editor is active and/or if the terminal is shown/hidden. However, these are pretty weak indicators...
The best solution would be to somehow integrate with `vue-cli-service`...
For now, as a workaround, I'll probably resort to running `npm start` manually in the terminal instead of using npm scripts feature of VS Code.

**Comment by GlutenBoy** [comment]
I have the same problem running my API (`dotnet run --watch`) and running `vite` continually in VS Code terminals. Wakatime reports 99% of building time instead of coding. Maybe there's a work around, but I didn't find anything useful in the documentation.

**Comment by Jaeiya** [comment]
I have the same problem. I use the built-in build task for watching my typescript file changes and waka time reports basically an infinite build time if I leave my vscode running in the background. Makes this extension worthless to me.

**Comment by alanhamlett** [comment]
Would a config in your `~/.wakatime.cfg` file to disable tracking builds fix it for you?

**Comment by alanhamlett** [comment]
Possibly fixed with 02a4eaa7ca3e4c3b6f42f400445ea513d1635b96. I'll comment here after the next plugin release when it's ready to test.

**Comment by alanhamlett** [comment]
Released with v24.0.0.
