### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by onlyreddy** [wakatime/vscode-wakatime#306]
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `19.3.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/username/AppData/Local/Temp/WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alanhamlett** [comment]
Please attach the `cpuprofile.txt` file so we can see what's causing the high cpu usage.

**Comment by alanhamlett** [comment]
It's most likely due to many wakatime-cli processes forked at the same time. We'll fix this by buffering heartbeats in vscode, then only forking wakatime-cli once every ~10 seconds.

**Comment by alanhamlett** [comment]
Should be fixed with https://github.com/wakatime/wakatime-cli/pull/960.
