### ISSUE TITLE
Error when trying to use the CLI in /usr/local/bin

### ISSUE THREAD

**Issue by EetuKiiskila** [wakatime/vscode-wakatime#307]
After updating the plugin to version 20.0.0, WakaTime stopped working. At first I tried reinstalling the plugin, rebooting and changing the API key but it didn't help. ~.wakatime.log was not getting updated so I enabled debug mode and toggled developer tools. The error messages indicated that the plugin was trying to use the CLI in /usr/local/bin and there was a problem with module wakatime not being found.

I was able to get the plugin to work by renaming the CLI in /usr/local/bin to something else so that the plugin would not find it and would either use the CLI in ~/.wakatime or download a working version of the CLI to /usr/local/bin.

**Comment by alanhamlett** [comment]
Yep, in v20 we started using `wakatime-cli` from your `$PATH` if it exists. Try running `pip uninstall wakatime` if you've got an old wakatime-cli installed globally.
