### ISSUE TITLE
Simplify display of status bar

### ISSUE THREAD

**Issue by luojiego** [wakatime/vscode-wakatime#309]
Wakatime messages are **too long** since Debugging time was added. But I love wakatime so much I don't want to turn it off.
![image](https://user-images.githubusercontent.com/3175699/197775439-485c922c-9e5b-4a6c-a705-8c91021afe56.png)

**Comment by gandarez** [comment]
You might set `status_bar_hide_categories = true` in your `~/.wakatime.cfg` file.
