### ISSUE TITLE
not working, using legacy Python wakatime-cli from PATH

### ISSUE THREAD

**Issue by RaduAlbastroiu** [wakatime/vscode-wakatime#310]
Hello,

Today after the update to 1.72.2 the extensions stopped updating time. It is showing the correct time from the dashboard but every time I press cmd save it shows and error in the status bar. In the last 3h since I've noticed the error I restarted my computer, uninstall and reinstall the extensions and nothing seems to work.

Machine specs:
MacOS 12.1
Visual Studio Code 1.72.2
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0

![Screenshot 2022-10-26 at 19 14 19](https://user-images.githubusercontent.com/17261805/198080420-00701c2f-acb6-4fe5-8912-77befd5bcd9f.png)

**Comment by gandarez** [comment]
What's your vscode dev console say? Also please attach any error found at `~/.wakatime.log` file.

**Comment by RaduAlbastroiu** [comment]
Vscode console:
` ERR [Extension Host] [WakaTime][ERROR] Error: Command failed: /Users/radualbastroiu/.pyenv/shims/wakatime --entity /Users/radualbastroiu/Documents/Projects/CarsOnDemand/frontend/src/_owner/pages/CarEvents/ModalCarEvent.tsx --plugin "vscode/1.72.2 vscode-wakatime/20.0.0" --lineno 94 --cursorpos 22 --lines-in-file 116 --alternate-project CarsOnDemand --project-folder /Users/radualbastroiu/Documents/Projects/CarsOnDemand --write
usage: wakatime [-h] [--entity FILE] [--key API_KEY] [--write]
                [--plugin PLUGIN] [--time time] [--lineno INT]
                [--cursorpos INT] [--entity-type ENTITY_TYPE]
                [--category CATEGORY] [--proxy PROXY] [--no-ssl-verify]
                [--ssl-certs-file FILE] [--project PROJECT]
                [--alternate-project PROJECT] [--language LANGUAGE]
                [--local-file FILE] [--hostname HOSTNAME] [--disable-offline]
                [--hide-file-names] [--hide-project-names]
                [--hide-branch-names] [--exclude PATH]
                [--exclude-unknown-project] [--include PATH]
                [--include-only-with-project-file] [--extra-heartbeats]
                [--log-file FILE] [--api-url URL] [--timeout SECONDS]
                [--sync-offline-activity AMOUNT] [--today] [--config FILE]
                [--config-section SECTION] [--config-read KEY]
                [--config-write KEY VALUE] [--verbose] [--version]
wakatime: error: unrecognized arguments: --lines-in-file 116 --project-folder /Users/radualbastroiu/Documents/Projects/CarsOnDemand`

_please attach any error found at ~/.wakatime.log file._
I didn't find the wakatime log file, I'm using only the vscode version.

**Comment by alanhamlett** [comment]
You should uninstall the old wakatime in that pushims folder. Probably:

`pip uninstall wakatime`

**Comment by RaduAlbastroiu** [comment]
After pip uninstall it looks like it's working, Thank you @alanhamlett !
