### ISSUE TITLE
ℹ️ Feature Request

### ISSUE THREAD

**Issue by pratikkabade** [wakatime/vscode-wakatime#317]
### Wakatime profile to display language wise hours

![image](https://user-images.githubusercontent.com/76637730/206671281-b61d565a-ebaf-4538-a4ba-eb78be32dd39.png)

### really appreciate it if you take this into consideration

**Comment by alanhamlett** [comment]
Deployed this change to the website just now.

**Comment by pratikkabade** [comment]
### **hate** to bring this again but i can't see any changes. It's still the same

### im referring to this [link](https://wakatime.com/me) or more precise this [one](https://wakatime.com/@pratikkabade)

**Comment by alanhamlett** [comment]
Try hard-refreshing the page to make sure your browser isn't caching the old javascript.

**Comment by pratikkabade** [comment]
I was saying about this 
![image](https://user-images.githubusercontent.com/76637730/206701472-8a82d457-e7b3-4cb2-ac12-f0f21608ae49.png)
when we click on `any language` the above year calendar should show coding with `that respective language` on the calendar

is it clear what am i asking? And thank you for being open and flexible.

**Comment by alanhamlett** [comment]
Oh got it, we don't have that feature planned anytime soon.

**Comment by pratikkabade** [comment]
Oh i see but it would be a great feature hope to see you implement it. Anyways I appreciate it!

**Comment by pratikkabade** [comment]
@alanhamlett, is there any problem from your end because from last 2 days my activity isn't getting synced

**Comment by alanhamlett** [comment]
Not that we know of. Are there any error messages in your `~/.wakatime.log` file?

Please email support@wakatime.com to get more help with debugging your plugin.

**Comment by pratikkabade** [comment]
Sorry for delay.
I checked the file there are several logs

```
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: failed fetching today from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": retry request failed: Get \"https://143.244.210.202/api/v1/users/current/statusbar/today\": dial tcp 143.244.210.202:443: connectex: A socket operation was attempted to an unreachable host.. original error: Get \"https://api.wakatime.com/api/v1/users/current/statusbar/today\": dial tcp: lookup api.wakatime.com: no such host","now":"2022-12-22T12:15:37+05:30","os/arch":"windows/amd64","version":"v1.60.1"}
```

this one is the latest one (the most bottom one)
is this causing the issue? is so can you tell me how to fix it?

**Comment by pratikkabade** [comment]
PS. Its working now, thanks!

**Comment by alanhamlett** [comment]
`dial tcp: lookup api.wakatime.com: no such host` looks like a temporary network issue, which is probably why it's working now

**Comment by pratikkabade** [comment]
@alanhamlett is it possible to track specific website in wakatime like `localhost:8888`?

**Comment by alanhamlett** [comment]
With the [Chrome Extension](https://github.com/wakatime/chrome-wakatime), but it's not currently working very well. We're planning on fixing it starting this month.

**Comment by pratikkabade** [comment]
ok thanks!! 👍

**Comment by pratikkabade** [comment]
@alanhamlett does wakatime support [stackblitz](https://stackblitz.com/)

**Comment by alanhamlett** [comment]
> @alanhamlett does wakatime support [stackblitz](https://stackblitz.com/)

Stackblitz needs the extension to be `extensionKind` of `ui`, which we publish to Open VSX but our VS Code Marketplace extension is kind `workspace` so it isn't listed in the Stackblitz Codeflow editor.

https://github.com/stackblitz/core/issues/3#issuecomment-1416712387

**Comment by pratikkabade** [comment]
Oh I see!. 

I thought just chrome extension it could be possible for you to track stackblitz too. Nevermind, thanks!
