### ISSUE TITLE
Jupyter Notebook (.ipynb) not detected

### ISSUE THREAD

**Issue by 2-5** [wakatime/vscode-wakatime#321]
`.ipynb` files are not shown in the language list, despite `.ipynb` files being tracked.

Dashboard screenshot:
![waka](https://user-images.githubusercontent.com/3753822/212071738-906fc3e5-bcf2-4d33-ba80-aa18e3a44a6c.png)

My settings:

```ini
[settings]
hide_file_names = true
hide_branch_names = true
hide_project_names = true
hide_project_folder = true
status_bar_hide_categories = true
include_only_with_project_file = true
```

Up to date version of VS Code/Jupyter Extension/WakaTime Extension.

**Comment by alanhamlett** [comment]
Fixed for future code stats using a server-side file extension rule. To set a language for your past code stats, please use a custom rule matching that file extension and changing the language to `Jupyter Notebook`:
https://wakatime.com/faq#custom-rules
