### ISSUE TITLE
Warnings in log after 1.62.1 upgrade: "project_root_count: Can not be greater than number of folders in entity."

### ISSUE THREAD

**Issue by 2-5** [wakatime/vscode-wakatime#322]
After upgrade to 1.62.1 `.wakatime.log` is full of these warnings:

```json
{
  "caller":"cmd/heartbeat/heartbeat.go:136",
  "file":"REMOVED",
  "func":"heartbeat.SendHeartbeats",
  "level":"warning",
  "lineno":1,
  "message":"project_root_count: Can not be greater than number of folders in entity.",
  "now":"2023-01-26T18:23:15+02:00",
  "os/arch":"windows/amd64",
  "plugin":"vscode/1.74.3 vscode-wakatime/23.2.0",
  "time":1674750194.7731433,
  "version":"v1.62.1"
}
```

I also have no stats for today - 0 secs displayed in the VS Code status bar, which is wrong.

**Comment by alanhamlett** [comment]
Please turn on debug mode (`debug = true` in your `~/.wakatime.cfg` file) then email support@wakatime.com with the `entity` file path and `project_root_count` of a heartbeat that's getting that error.

**Comment by alanhamlett** [comment]
For now, we've fixed it on the server so you'r dashboard won't be empty going forward.

**Comment by alanhamlett** [comment]
Will be fixed with https://github.com/wakatime/wakatime-cli/pull/818.
