### ISSUE TITLE
Query Timeout

### ISSUE THREAD

**Issue by ChristopherHoyt** [wakatime/vscode-wakatime#323]
![Screenshot from 2023-01-28 01-09-18](https://user-images.githubusercontent.com/123533569/215249878-60025867-fce2-49fe-a908-3c00cfc6500d.png)
Query Timeout on Dashboard

TS steps taken:
logged out and back in to wakatime
restarted wakatime extension in VS code
re-entered API key
unistalled extension
reinstalled extension + entered API key
Google search
Waka time github search 

Thanks in advance for more TS ideas.

**Comment by alanhamlett** [comment]
How about now?

**Comment by alanhamlett** [comment]
Also, how long does it take from visiting the dashboard until you see that error message?

**Comment by alanhamlett** [comment]
Found the issue, fixed now.

**Comment by ChristopherHoyt** [comment]
all good now.  btw, the issue appeared immediately follwoing a browser refresh.  thanks!
