### ISSUE TITLE
Time no longer displayed in status bar after extension upgraded to 24.0

### ISSUE THREAD

**Issue by 2-5** [wakatime/vscode-wakatime#326]
After today's extension upgrade, the time stopped being displayed in the status bar:

![2023-02-02_182211](https://user-images.githubusercontent.com/3753822/216382307-50eb82da-e36d-4488-8192-7f74360101d0.png)

My config has no status bar settings:

```ini
[settings]
include_only_with_project_file = true

hide_file_names = true
hide_branch_names = true
hide_project_names = true
hide_project_folder = true
```

**Comment by alanhamlett** [comment]
We're waiting on the updated wakatime-cli release to fix this.

**Comment by alanhamlett** [comment]
After restarting vscode does it work again?
