### ISSUE TITLE
Extension visualcode does not recognize jupyter notebook

### ISSUE THREAD

**Issue by sc0v1n0** [wakatime/vscode-wakatime#328]
Good afternoon, I don't know what would be the error in my wakatime.
I installed the extension using the visual code and added the apikey, as shown in the explanation. Other than that, I didn't do anything else on wakatime. Keep doing my work, over the months. I went to look at my wakatime, I realized that the jupyter notebook was not recognized in wakatime by the visual code. I noticed because I used the jupyter notebook many times and did not count the time in it on the platform. For this, I tested the jupyter notebook in Pycharm and the time used was recognized.

My visual code is up to date, the other languages I use are recognized on the platform, but the one I use most frequently doesn't appear as in the case of jupyter notebook. I will send a print below my wakatime.
[My User Wakatime](https://wakatime.com/@__eddi__)

![image](https://user-images.githubusercontent.com/56802572/216836235-4fc21d50-7740-40bf-8e2c-3f9fb9669c0f.png)

**Comment by alanhamlett** [comment]
We do support Jupyter Notebook language and IPython. Do you happen to use the WakaTime browser extension? All activity from the Chrome extension has language `Other` and is the most common reason for such a large portion of your coding being in that `Other` language.

**Comment by sc0v1n0** [comment]
Good afternoon, I don't use the browser. I use the extension that is available in visual code.

![image](https://user-images.githubusercontent.com/56802572/216840859-5394bcad-33a8-4798-a3a5-e3a7c9afee5a.png)

I found it strange because from python it recognizes well and I can see the progress on the wakatime platform. I had used jupyter in this same extension format as the visual code, in the PyCharm tool. Up the language usage status. In the browser I can't even use it. 

![image](https://user-images.githubusercontent.com/56802572/216840984-fde818ef-c15a-4af5-98c2-045b7e879e0e.png)

This week's example. I used jupyter from monday to friday. It didn't. The feedback email of the month has arrived. It came like another language. I don't really know how to explain why this is happening. I just followed the wakatime installation basics. It was already going up the language statuses


![image](https://user-images.githubusercontent.com/56802572/216841060-095361fa-3cbc-4180-ad41-3255bfe5001c.png)

**Comment by alanhamlett** [comment]
I mean, do you use the [WakaTime Chrome extension](https://github.com/wakatime/chrome-wakatime) or the [WakaTime Google Calendar integration](https://wakatime.com/integrations)? Those two are the source of `Other` language on your profile.

**Comment by sc0v1n0** [comment]
Use of the calendar, I didn't know he recognized it as a language. But also strange the jupyter files don't show up.

**Comment by sc0v1n0** [comment]
I'm going to take it off google calendar for a while.

**Comment by sc0v1n0** [comment]
Thanks for the feedback.
