### ISSUE TITLE
Add support for the Vim Extension in vscode

### ISSUE THREAD

**Issue by nick22985** [wakatime/vscode-wakatime#330]
After installing the vim extension my code seems to send to the API constantly and causing it to have what I assume is have no timeout so when I switch from normal mode to insert mode it sends an api request that logs code. This results in a tone of second times and it not counting correctly

Extension: https://marketplace.visualstudio.com/items?itemName=vscodevim.vim
Wakatime dashboard: https://gyazo.com/17d73f2dc38bac9a6e31013951c64838

**Comment by alanhamlett** [comment]
I use the Vim extension too without issues. That's probably because cutoff at the bottom of your screenshot you have more projects displayed? My guess:

You're editing files in two different git repos, so your time is getting very fragmented between the two projects.
