### ISSUE TITLE
 Invalid Api Key (104); Make sure your Api Key is correct!

### ISSUE THREAD

**Issue by ifyour** [wakatime/vscode-wakatime#331]
I have verified that the API Key is correct, but it still shows an error.

This is the last log after enabling debug:

```json
{
  "caller": "cmd/run.go:270",
  "func": "cmd.runCmd",
  "level": "error",
  "message": "failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format",
  "now": "2023-03-27T09:44:26+08:00",
  "version": "v1.55.2"
}
```

**Comment by alanhamlett** [comment]
Version 1.55.2 is old, can you update to the latest wakatime-cli release:
https://github.com/wakatime/wakatime-cli

Vscode should be doing that for you, unless it can't connect to GitHub to check for new releases.

**Comment by alanhamlett** [comment]
That's a networking issue. Are you behind a proxy or does your ISP block some websites?

**Comment by ifyour** [comment]
After confirming, it was determined that the issue was related to the network. Therefore, I added a front-end proxy, and the problem was resolved. Thank you for your response!

VScode `Settings.json` :
```json
  "http.proxySupport": "on",
  "http.proxy": "http://127.0.0.1:1080",
```
