### ISSUE TITLE
Constant request for api key

### ISSUE THREAD

**Issue by jason490** [wakatime/vscode-wakatime#335]
I had to rollback one version due to getting constant request to put in my api key, everytime I switch files. When I first open vscode the extension doesn't request for the api key, but once I click on file the I get requested for the api key. This is on a windows machine

This doesn't happen when using WSL remote desktop nor when using ubuntu desktop.
This is on version 24.0.9

**Comment by thelostword** [comment]
I've also encountered this situation,😓

**Comment by kofmania** [comment]
Today me too.

**Comment by purequant** [comment]
Me too

**Comment by joesonshaw** [comment]
# +1😔

**Comment by MiltonChung** [comment]
+1

**Comment by DavoDC** [comment]
Duplicate: https://github.com/wakatime/vscode-wakatime/issues/336

**Comment by alanhamlett** [comment]
Fixed with c0c9356fe7fed89437729dc79d8d9c4bdf8609c1 and released in v24.0.10.
