### ISSUE TITLE
VSCode always asks for API key - another warning

### ISSUE THREAD

**Issue by ACnoway** [wakatime/vscode-wakatime#336]
just like #324 , vscode started to ask me API key even after I regenerated new key and put in for like ten times.
vscode version: 1.77.3
wakatime extension version: 24.0.9
the warnings in developer tools looks like this:
![wakatime bug](https://user-images.githubusercontent.com/91535478/231914580-1303df86-9482-4694-915e-4ec2a7f5fec8.png)
and I didn't see anything in .wakatime.log

**Comment by J-Ciro** [comment]
Same here, nothing related to Denfender.

**Comment by YatsukiRenka** [comment]
Same trouble, yesterday it was fine but happened this morning

**Comment by nekochan0122** [comment]
Same here, it happened after I update the extension.

**Comment by zhangkaihua88** [comment]
Same here

**Comment by FE-wuhao** [comment]
it start to happened from this morning

**Comment by staff0rd** [comment]
I've seen this occur before and eventually go away, however the frequency of the popup (pictured below) is extremely frustrating considering `ESC` or the correct API key doesn't resolve the issue. 

It would be pleasant if there were some kind of exponential backoff on displaying the popup, regardless of whatever the actual fix for the underlying error.

![image](https://user-images.githubusercontent.com/6289998/231924803-9b065d63-7244-4bb9-aa16-0443533eb2f2.png)

**Comment by DavoDC** [comment]
I'm getting it too. I downgraded to 24.0.7 and its working again!  
Logs said: `Unable to get api key: TypeError: Cannot read properties of undefined (reading 'includes')`
Something is going wrong with the reading of the config files, imho.

**Comment by zhanghaoranas** [comment]
I have encountered the same problem

**Comment by marlberm2014** [comment]
> I'm getting it too. I downgraded to 24.0.7 and its working again! Logs said: `Unable to get api key: TypeError: Cannot read properties of undefined (reading 'includes')` Something is going wrong with the reading of the config files, imho.

This one works, thanks.

**Comment by HanJaeJoon** [comment]
I've also encountered this.
downgrading to 24.0.7 works for me.

**Comment by DavoDC** [comment]
> This one works, thanks.
You're welcome 😊

**Comment by lukethacoder** [comment]
https://github.com/wakatime/wakatime-cli/issues/660

would say its almost related to this... but doesn't look like any antivirus is flagging any files. Must be something else.

**Comment by juliamuiruri4** [comment]
Encountering the same issue this morning and being forced to disable

**Comment by manthanank** [comment]
Same here, but by downgrading to to 24.0.7 it's working.

**Comment by CelebMunyiri** [comment]
downgrading it to 24.0.7 works for me

**Comment by mason369** [comment]
The previous usage was fine, but now there's always a pop-up prompt.
![gif](https://user-images.githubusercontent.com/93964390/231970663-000c28c4-4352-40e4-b591-3d865811ae40.gif)

**Comment by FywOoie** [comment]
downgrading to 24.0.7 works for me as well

**Comment by 0c3d7r4** [comment]
have you guys done something to the api? my plugin for vscodium seems to have stopped working yesterday at around 3pm gmt. i've always used the old one like version 4 real fine but now even the newest one does not work with the latest codium... it seems to send heartbeats but the time is always 0 minutes. it's a shame i really loved waka

**Comment by alanhamlett** [comment]
Fixed with c0c9356fe7fed89437729dc79d8d9c4bdf8609c1 and released in v24.0.10.

**Comment by Aditya7997** [comment]
Removing wakatime extension from the VS code worked for me.

**Comment by deveveloper-faran-iqbal** [comment]
I got the same issue when I upgraded my VS code, it don't even allows me to type anything. 

My fix is: Go to extensions and search for WakaTime. Just uninstall or disable it. 

Thank me later.
