### ISSUE TITLE
VS code ,API_KEY popup on 24.0.9 , working fine on 24.0.7

### ISSUE THREAD

**Issue by Arsh3686** [wakatime/vscode-wakatime#339]
Working exprience is like hell with wakatime ,API_KEY popup on 24.0.9 , working fine on 24.0.7

**Comment by alanhamlett** [comment]
Fixed with c0c9356fe7fed89437729dc79d8d9c4bdf8609c1 and released in v24.0.10.

**Comment by vishnumaiea** [comment]
I am having the same issue with the latest 24.0.9. I am getting the following prompt asking for the API key every now and then, even though I have added the key in Settings.

![image](https://user-images.githubusercontent.com/10383395/232003703-e773af0f-1cc5-441d-8fd6-acc7c8ecae5c.png)

**Comment by alanhamlett** [comment]
Please upgrade the extension to v24.0.10.
