### ISSUE TITLE
WakaTime: working offline... coding activity will sync next time we are online

### ISSUE THREAD

**Issue by ishowman** [wakatime/vscode-wakatime#342]
I can visit any website normally, but wakatime in VSCode says it is offline and can't not work.
I've used wakatime for serveral years, it's normal in the past year but not work from 2023.

**Comment by alanhamlett** [comment]
In your `~/.wakatime/wakatime.log` file what's the error message. Make sure to find the error message not related to `backoff`, which is just client-side rate limiting and doesn't show the network error because it skips connecting.

**Comment by ishowman** [comment]
@alanhamlett  Thanks for your reply.I search `backoff` in `~/.wakatime/wakatime.log` file and found this:
```
{"caller":"cmd/run.go:301","file":"e:\\codes\\cute-labors\\sell\\2.ts","func":"cmd.runCmd","is_write":true,"level":"error","lineno":104,"message":"failed to run command: sending heartbeat(s) failed: rate limited: won't send heartbeat due to backoff","now":"2023-04-17T12:15:16+08:00","os/arch":"windows/amd64","plugin":"vscode/1.77.3 vscode-wakatime/24.0.10","time":1681704916.2992156,"version":"v1.73.0"}
{"caller":"cmd/run.go:301","file":"e:\\codes\\cute-labors\\sell\\index.ts","func":"cmd.runCmd","level":"error","lineno":17,"message":"failed to run command: sending heartbeat(s) failed: rate limited: won't send heartbeat due to backoff","now":"2023-04-17T12:15:28+08:00","os/arch":"windows/amd64","plugin":"vscode/1.77.3 vscode-wakatime/24.0.10","time":1681704928.126442,"version":"v1.73.0"}
```

omg, I can not get any idea from it.

**Comment by alanhamlett** [comment]
We need the message NOT related to `backoff` so please search for lines that don't contain backoff.

**Comment by Larsundso** [comment]
I'm running into the same issue. I've condensed it down to the 1 error per type and no backoff errors

```
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","lineno":44,"message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. authentication failed at \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\"","now":"2023-04-28T09:47:44+02:00","os/arch":"linux/amd64","plugin":"vscode/1.77.3 vscode-wakatime/24.0.10","time":1682668064.4836502,"version":"v1.73.0"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","lineno":160,"message":"failed to run command: offline sync failed: failed to sync offline heartbeats: authentication failed at \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\"","now":"2023-04-14T15:17:16+02:00","os/arch":"linux/amd64","plugin":"vscode/1.77.3 vscode-wakatime/24.0.9","time":1681478235.558978,"version":"v1.73.0"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: failed fetching today from api: authentication failed at \"https://api.wakatime.com/api/v1/users/current/statusbar/today\". body: \"{\\\"error\\\":\\\"Unauthorized\\\"}\\n\"","now":"2023-04-14T15:41:50+02:00","os/arch":"linux/amd64","version":"v1.73.0"}
```
It says my API Key is invalid, though when I visit wakatime.com/api-key it is exactly the one in `~/.wakatime.cfg`

**Comment by alanhamlett** [comment]
@Larsundso try saving your api key from within vscode just to make sure, so it writes the api key to `~/.wakatime.cfg` again. I checked our logs and I'm seeing the `401 Unauthorized` error for your account yesterday but it looks like it started working again. Maybe you're using a different machine today?

**Comment by Larsundso** [comment]
Same machine but indeed did start working.
I installed another version of wakatime, then updated it back to the current one.
Also replaced the API key in VSCode with the same one from the website.
One of those solved it.

Thank you :)

**Comment by GruDev325** [comment]
I also have this issue. Wakatime worked yesterday, but today it doesn't work.
`{"caller":"cmd/run.go:301","file":"f:\\Dev_Space\\Company\\Chronos_Dex\\sc_chronos_marketplace\\contracts\\ChronosMarketplace.sol","func":"cmd.runCmd","level":"error","lineno":775,"message":"failed to run command: sending heartbeat(s) failed: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 429, want: 201/202. body: \"{\\\"error\\\": \\\"Consuming heartbeats has been disabled for account 7de44f10-09cf-4c20-8b1f-3633f80db5b0.\\\"}\"","now":"2023-07-15T14:03:41-03:00","os/arch":"windows/amd64","plugin":"vscode/1.80.1 vscode-wakatime/24.2.0","time":1689440619.960904,"version":"v1.73.1"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: file experts fetch failed: bad request: bad request at \"https://api.wakatime.com/api/v1/users/current/file_experts\"","now":"2023-07-15T14:03:59-03:00","os/arch":"windows/amd64","version":"v1.73.1"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: file experts fetch failed: api error: invalid response status from \"https://api.wakatime.com/api/v1/users/current/file_experts\". got: 404, want: 200. body: \"{\\\"error\\\": \\\"Join a team dashboard first.\\\"}\"","now":"2023-07-15T14:04:03-03:00","os/arch":"windows/amd64","version":"v1.73.1"}
{"caller":"cmd/run.go:301","file":"f:\\Dev_Space\\Company\\Chronos_Dex\\sc_chronos_marketplace\\contracts\\ChronosMarketplace.sol","func":"cmd.runCmd","level":"error","lineno":749,"message":"failed to run command: sending heartbeat(s) failed: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 429, want: 201/202. body: \"{\\\"error\\\": \\\"Consuming heartbeats has been disabled for account 7de44f10-09cf-4c20-8b1f-3633f80db5b0.\\\"}\"","now":"2023-07-15T14:06:03-03:00","os/arch":"windows/amd64","plugin":"vscode/1.80.1 vscode-wakatime/24.2.0","time":1689440762.4717875,"version":"v1.73.1"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: file experts fetch failed: api error: invalid response status from \"https://api.wakatime.com/api/v1/users/current/file_experts\". got: 404, want: 200. body: \"{\\\"error\\\": \\\"Join a team dashboard first.\\\"}\"","now":"2023-07-15T14:07:07-03:00","os/arch":"windows/amd64","version":"v1.73.1"}
{"caller":"cmd/run.go:301","file":"f:\\Dev_Space\\Company\\Chronos_Dex\\sc_chronos_marketplace\\contracts\\interfaces\\IChronosMarketplace.sol","func":"cmd.runCmd","level":"error","lineno":100,"message":"failed to run command: sending heartbeat(s) failed: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 429, want: 201/202. body: \"{\\\"error\\\": \\\"Consuming heartbeats has been disabled for account 7de44f10-09cf-4c20-8b1f-3633f80db5b0.\\\"}\"","now":"2023-07-15T14:07:07-03:00","os/arch":"windows/amd64","plugin":"vscode/1.80.1 vscode-wakatime/24.2.0","time":1689440825.8265748,"version":"v1.73.1"}
{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: file experts fetch failed: bad request: bad request at \"https://api.wakatime.com/api/v1/users/current/file_experts\"","now":"2023-07-15T14:07:33-03:00","os/arch":"windows/amd64","version":"v1.73.1"}`

**Comment by alanhamlett** [comment]
@GruDev325 fixed your issue. Your code stats should sync up soon.

**Comment by GruDev325** [comment]
Thanks

**Comment by demptd13** [comment]
> @GruDev325 fixed your issue. Your code stats should sync up soon.

Hello! I also have same erron in VS Code:

`{"caller":"cmd/run.go:341","file":"c:\\Users\\Igor\\.wakatime\\wakatime.log","func":"cmd.runCmd","level":"error","lineno":1,"message":"failed to run command: sending heartbeat(s) failed: won't send heartbeat due to backoff without proxy","now":"2024-04-25T17:10:41+03:00","os/arch":"windows/amd64","plugin":"vscode/1.83.1 vscode-wakatime/24.5.0","time":1714054241.3759532,"version":"v1.90.0"}`

How I can fix it?

**Comment by BrenoFariasdaSilva** [comment]
Hi there. I have the same problem. 
I've tried everything, such as:
1. Enable debug mode.
2. Delete the  "~/.wakatime/wakatime-internal.cfg"
3.Uninstalll the IDE and Plugin.
4. Generate a new API Key (and yes, I've updated it in the config file)
5. Delete the entire dir "rm -rf ~/.wakatime*"
6. Search for Issues similar to it.

I'm really desperate on this, as i use wakatime to prove working hours for a university project and I've been without this working probably since mid April.

Also, I've never used any VPN or proxy. It does not work on any computer of mine, on any os that i use (Windows, Mac, Linux or even Raspberry) in any network (home or university).

Here is a short part of the long log file:
```
{"caller":"pkg/offline/offline.go:55","file":"/Users/brenofarias/.wakatime/wakatime.log","func":"heartbeat.SendHeartbeats","level":"debug","lineno":1,"message":"execute offline queue with file /Users/brenofarias/.wakatime.bdb","now":"2024-06-07T10:33:49-03:00","os/arch":"darwin/arm64","plugin":"vscode/1.90.0 vscode-wakatime/24.5.0","time":1717767229.7594938,"version":"v1.90.0"}
{"caller":"pkg/backoff/backoff.go:43","file":"/Users/brenofarias/.wakatime/wakatime.log","func":"heartbeat.SendHeartbeats","level":"debug","lineno":1,"message":"execute heartbeat backoff algorithm","now":"2024-06-07T10:33:49-03:00","os/arch":"darwin/arm64","plugin":"vscode/1.90.0 vscode-wakatime/24.5.0","time":1717767229.7594938,"version":"v1.90.0"}
{"caller":"pkg/backoff/backoff.go:102","file":"/Users/brenofarias/.wakatime/wakatime.log","func":"backoff.shouldBackoff","level":"debug","lineno":1,"message":"exponential backoff tried 4 times since 2024-06-07T10:32:58-03:00, will retry again after 2024-06-07T10:37:49-03:00","now":"2024-06-07T10:33:49-03:00","os/arch":"darwin/arm64","plugin":"vscode/1.90.0 vscode-wakatime/24.5.0","time":1717767229.7594938,"version":"v1.90.0"}
{"caller":"pkg/offline/offline.go:65","file":"/Users/brenofarias/.wakatime/wakatime.log","func":"heartbeat.SendHeartbeats","level":"debug","lineno":1,"message":"pushing 1 heartbeat(s) to queue due to error","now":"2024-06-07T10:33:49-03:00","os/arch":"darwin/arm64","plugin":"vscode/1.90.0 vscode-wakatime/24.5.0","time":1717767229.7594938,"version":"v1.90.0"}
{"caller":"cmd/run.go:341","file":"/Users/brenofarias/.wakatime/wakatime.log","func":"cmd.runCmd","level":"error","lineno":1,"message":"failed to run command: sending heartbeat(s) failed: won't send heartbeat due to backoff without proxy","now":"2024-06-07T10:33:49-03:00","os/arch":"darwin/arm64","plugin":"vscode/1.90.0 vscode-wakatime/24.5.0","time":1717767229.7594938,"version":"v1.90.0"}
```

So, the main message is "failed to run command: sending heartbeat(s) failed: won't send heartbeat due to backoff without proxy"

**Comment by BrenoFariasdaSilva** [comment]
Also @alanhamlett, I've used Wakatime on JetBrains IntelliJ, but my main tool used is Visual Studio Code.
