### ISSUE TITLE
API Key per project

### ISSUE THREAD

**Issue by DDTORRES055** [wakatime/vscode-wakatime#343]
It would be great to have one API Key for work projects, and another for personal projects, etc.

I mean, that the extension supports the configuration per project.

I want to write in `.vscode/settings.json` something like this:

`
  {
      "wakatime.apiKey": "API_KEY"
  }
`

**Comment by alanhamlett** [comment]
That's supported with a `[project_api_key]` section in your `~/.wakatime.cfg` file:
https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#ini-config-file
