### ISSUE TITLE
Wakatime not updating/showing all activity in dashboard.

### ISSUE THREAD

**Issue by Coder-Manuel** [wakatime/vscode-wakatime#344]
Am experiencing this weird issue.
The coding activities just stopped updating on the web dashboard, it's as if am not doing anything, but when I go to plugin status I can actually see my IDE(s) updated as used.
Shared some screenshots.

<img width="1728" alt="Screenshot 2023-04-25 at 17 01 44" src="https://user-images.githubusercontent.com/55477248/234302026-584549e0-cbb1-418b-9a6d-16fb96141fc3.png">
As you can see in this screenshot, the time recorded is 2hr 17min for viscose which is not correct since I used vscode for the whole day and also used other ide(s) as you're going to see in the next screenshot.

### 
<img width="1728" alt="Screenshot 2023-04-25 at 17 03 11" src="https://user-images.githubusercontent.com/55477248/234302574-697eee7a-1012-4d5f-9af0-ca816362f9a4.png">
This is the plugin status page, and it clearly shows when I last used the different IDE(s).... 
I have re-installed my plugins and also wakatime-cli but nothing has changed.

More info:
[wakatime.log](https://github.com/wakatime/vscode-wakatime/files/11323360/wakatime.log)
```
wakatime-cli: v1.73.0
vs-code: v24.0.10
macos-wakatime: v0.2.4
```

**Comment by AlexHromov10** [comment]
Same exact problem. My wakatime is offline for whole week or two now. Was deleting ~/.weakatime multiple times, no effect
![image](https://user-images.githubusercontent.com/80152712/234683621-2bb08e5e-0d10-4ac3-9d35-37c849ca65fe.png)
I am clearly been wotking for the whole week, not just 2hrs))

**Comment by alanhamlett** [comment]
@Coder-Manuel yours should be working according to your attached `wakatime.log` file. Maybe it's just the dashboard cached and not updating fast enough. Does your dashboard show the correct time for April 25th now?

@AlexHromov10 are there error messages in your `~/.wakatime/wakatime.log` file?

**Comment by Coder-Manuel** [comment]
@alanhamlett 
No changes for April 25th, but since then it has started working again correctly.....
I did not do anything, just left it and the next day it started working again but the data for 25th is not updated.
I guess there's an issue but not sure where exact because this has happened for the 2nd time in a span of a week....

**Comment by FlippingBinary** [comment]
I just started using the WakaTime plugin in LunarVim yesterday, logged 5 hours which showed on the dashboard, then today it shows none of that activity and no new activity. No apparent errors in `wakatime.log` in both LunarVim on Manjaro Linux and LunarVim on Debian 11 inside WSL2. The cli seems to crash on Termux, but I'm sure that's entirely unrelated and I haven't spent any time trying to debug that yet.

**Comment by alanhamlett** [comment]
@FlippingBinary the incoming data is being saved, we're just having an issue with reads on the dashboard right now.

**Comment by alanhamlett** [comment]
The dashboard read incident is resolved now, things should be back to normal and all your code stats should be visible again.

**Comment by Coder-Manuel** [comment]
Hello @alanhamlett ...

Am experiencing this issue again....
I've tried to regenerate a new api key but no effect.

[wakatime.log]()

**Comment by alanhamlett** [comment]
@Coder-Manuel I've found the problem specific to your issue. The Terminal plugin is sending too many heartbeats, sending a heartbeat every time you type in the Terminal. We have a limit to the max number of heartbeats your dashboard will load, and it reaches that limit for you about halfway through the day. You should uninstall the Terminal plugin and this won't happen anymore.

**Comment by Coder-Manuel** [comment]
@alanhamlett ...
Noted and thanks

**Comment by thuan27** [comment]
Hello @alanhamlett 
As you can see, from this month, my wakatime didn't update anything? I don't understand because it was still working properly before
<img width="1728" alt="Screenshot 2023-05-12 at 21 24 42" src="https://github.com/wakatime/vscode-wakatime/assets/14727446/9f86ecd3-606e-48be-a36e-7eebe764b82d">
<img width="1725" alt="Screenshot 2023-05-12 at 21 24 20" src="https://github.com/wakatime/vscode-wakatime/assets/14727446/9b9330a3-01c2-4fd9-aea3-a147f346663c">

**Comment by NsdHSO** [comment]
```I got this {"caller":"cmd/run.go:301","file":"/Users/user/Documents/work/angular/open_source/forks/ngx-libs/src/styles.scss","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 429, want: 201/202. body: \"{\\\"error\\\": \\\"Consuming heartbeats has been disabled for account UUID.\\\"}\"","now":"2023-07-21T09:06:57+03:00","os/arch":"darwin/arm64","plugin":"WebStorm/2023.1.1 WebStorm-wakatime/14.1.5","time":1689919609.772,"version":"v1.73.1"} @alanhamlett
