### ISSUE TITLE
Error command failed when exec wakatime-cli-darwin-arm64

### ISSUE THREAD

**Issue by NsdHSO** [wakatime/vscode-wakatime#346]
I the developer console I got this 
`[Extension Host] [WakaTime][ERROR] Error: Command failed: /Users/user.../.wakatime/wakatime-cli-darwin-arm64 --entity /Users/user.../Documents/work/vue/vanilajs/index.html --plugin "vscode/1.77.3 vscode-wakatime/24.0.10" --lineno 33 --cursorpos 40 --lines-in-file 61 --alternate-project vanilajs --project-folder /Users/user.../Documents/work/vue/vanilajs`

This error I got in vscode but the same in webstrom.
Can someone help me with this error or solve this problem and solve it?

**Comment by alanhamlett** [comment]
Does that binary `/Users/user.../.wakatime/wakatime-cli-darwin-arm64` exist?

**Comment by NsdHSO** [comment]
yes in my computer I have 
![image](https://user-images.githubusercontent.com/37635083/235142631-7bb6b8a9-1b15-4c91-9da5-54da4a76fcec.png)

**Comment by alanhamlett** [comment]
Can you execute that program via command line with something like:

`./wakatime-cli-darwin-amd64 --version`

**Comment by NsdHSO** [comment]
I receive this ` ~/.wakatime/wakatime-cli-darwin-arm64  --version
v1.73.0`

**Comment by alanhamlett** [comment]
That looks like it's working. Let's try deleting `~/.wakatime/` folder and restarting vscode to see if that fixes it.

**Comment by NsdHSO** [comment]
I deleted it and i got this.`ERR [Extension Host] [WakaTime][ERROR] Error: Command failed: /Users/../.wakatime/wakatime-cli-darwin-arm64 --entity /Users/../Documents/work/vue/vanilajs/index.html --plugin "vscode/1.77.3 vscode-wakatime/24.0.10" --lineno 38 --cursorpos 1 --lines-in-file 61 --alternate-project vanilajs --project-folder /Users/../Documents/work/vue/vanilajs`

**Comment by alanhamlett** [comment]
That's very strange, because it ran from command line so vscode should also be able to run it. Can you jump on a Zoom call with me to debug it? Send me an email alan@wakatime.com and I'll send a Zoom meeting link.

**Comment by AstaDK** [comment]
Faced the same issue with:
Version: 1.96.0-insider
and ~/.wakatime/wakatime-cli-darwin-arm64  --version   `v1.105.2`

**Comment by NsdHSO** [comment]
IMHO we can close this issue because the issue was from some version...

**Comment by alanhamlett** [comment]
It's working now for you? Ok i'll close this issue.
