### ISSUE TITLE
waka time issue

### ISSUE THREAD

**Issue by TheoW03** [wakatime/vscode-wakatime#347]
the extension just broke.

I dont know what happened it wiped the last 7 days out. and is not recording new time coded.

(this issue is happening on both intelliJ and VS code)

![image](https://user-images.githubusercontent.com/95878514/235378764-86c12014-dfe7-446d-bded-63e193a984e7.png)

**Comment by TheoW03** [comment]
![image](https://user-images.githubusercontent.com/95878514/235378936-94f02de2-5490-4be6-8a80-97311067bf00.png)


here is the plugin status for both editors I use

**Comment by alanhamlett** [comment]
The dashboard read incident is resolved now, things should be back to normal and all your code stats should be visible again.
