### ISSUE TITLE
 24.0.10 completely broken: "command not found"

### ISSUE THREAD

**Issue by M123-dev** [wakatime/vscode-wakatime#348]
After upgrading to  24.0.10 wakatime vscode completely broke for me (Win11)

Every command I start via Ctrl + Shift + P which is from the plugin results in an error and it stopped tracking the time

![grafik](https://user-images.githubusercontent.com/39344769/235438098-c09c3ca2-7c2d-472f-8674-3fa756a9db07.png)

.
When downgrading to 23.0.9 everything started working like normal again.

**Comment by alanhamlett** [comment]
There is no v23.0.9, it went from [23.0.0 to 23.1.0](https://github.com/wakatime/vscode-wakatime/blob/master/CHANGELOG.md#2310-2023-01-11). Can you try downgrading to a different version and find where it stopped working?

**Comment by alanhamlett** [comment]
Also, try re-installing v24.0.10 because that error message in your screenshot looks like the plugin failed to install correctly.

**Comment by M123-dev** [comment]
> There is no v23.0.9, it went from [23.0.0 to 23.1.0](https://github.com/wakatime/vscode-wakatime/blob/master/CHANGELOG.md#2310-2023-01-11). Can you try downgrading to a different version and find where it stopped working?

Oh, my bad. I meant v24.0.9


> Also, try re-installing v24.0.10 because that error message in your screenshot looks like the plugin failed to install correctly.

That sadly did not work, though reinstalling VS Code (Thanks settings sync) did the trick.

Thanks for your effort 😄

**Comment by alanhamlett** [comment]
Glad it's working, wonder what the issue was but seems like it was outside the control of the wakatime plugin.
