### ISSUE TITLE
Error connecting to WakaTime

### ISSUE THREAD

**Issue by ryanvu** [wakatime/vscode-wakatime#354]
Error from vsCode Dev tool console:

` ERR [Extension Host] [WakaTime][ERROR] Error: Command failed: C:\Users\Ryan\.wakatime\wakatime-cli-windows-amd64.exe --entity c:\Users\Ryan\.wakatime\wakatime-internal.cfg --plugin "vscode/1.78.2 vscode-wakatime/24.0.10" --lineno 1 --cursorpos 1 --lines-in-file 4 --alternate-project api --project-folder c:\Users\Ryan\Desktop\Syzl\api --config C:\Users\Ryan\.wakatime.cfg --log-file C:\Users\Ryan\.wakatime\wakatime.log`

Error in .wakatime.log

{"caller":"cmd/run.go:301","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: failed fetching today from api: authentication failed at \"https://api.wakatime.com/api/v1/users/current/statusbar/today\". body: \"{\\\"error\\\": \\\"Unauthorized\\\"}\"","now":"2023-05-17T01:17:14-04:00","os/arch":"windows/amd64","version":"v1.73.1"}

![image](https://github.com/wakatime/vscode-wakatime/assets/13227428/1fa0a86a-da78-4b1f-a661-370fe52f53a7)

**Comment by alanhamlett** [comment]
What was the fix?
