### ISSUE TITLE
multiple status bar items with same id in DOM

### ISSUE THREAD

**Issue by geoffolson** [wakatime/vscode-wakatime#355]
https://github.com/wakatime/vscode-wakatime/blob/c586fff6fbcada02b298516a879c5b9561e60b56/src/wakatime.ts#L123

Using createStatusBarItem method multiple times without passing a unique identifier generates multiple elements with the same id in the DOM. For the most part this has no side-effect, but can be an issue when using customized themes.

![Screenshot 2023-06-05 at 11 06 10 PM](https://github.com/wakatime/vscode-wakatime/assets/88073601/8142ed5f-a2fc-4bd4-9c44-b09a9528dbf6)

In this example there are two extra chevrons showing with a powerline theme

![Screenshot 2023-06-05 at 11 05 21 PM](https://github.com/wakatime/vscode-wakatime/assets/88073601/3774f990-ba27-4eac-bbe5-6ea2531f48eb)

Using createStatusBarItem with a unique id would allow users to individually toggle on and off items when they right click the status bar as well. Currently can only toggle on and off all three items simultaneously with right clicking.
![Screenshot 2023-06-05 at 11 16 16 PM](https://github.com/wakatime/vscode-wakatime/assets/88073601/96d2e1d0-dd9c-49d8-ab01-48db49e119cf)

**Comment by alanhamlett** [comment]
Fixed with 0f13598fc25465265daa75d9d784596cc0e819a5.
