### ISSUE TITLE
vscode.dev & github.dev OS & host name

### ISSUE THREAD

**Issue by jerone** [wakatime/vscode-wakatime#356]
It looks like vscode.dev & github.dev is being detected as "Unknown OS" and "Unknown Hostname".

![image](https://github.com/wakatime/vscode-wakatime/assets/55841/0c17850a-2438-4a2e-9a79-da3a576dd1e0)

I would suggest to change it to "Online" or "Browser" for OS and "vscode.dev" & "github.dev" for hostname.

**Comment by alanhamlett** [comment]
Implemented with 98d429d7463676757034790dc4f20e5eba90f363 and released in v24.1.0.
