### ISSUE TITLE
Not able to use proxy format https://:@host:port

### ISSUE THREAD

**Issue by carloswm85** [wakatime/vscode-wakatime#357]
I'm behind a proxy, using the following valid address for VSCode:

![image](https://github.com/wakatime/vscode-wakatime/assets/29048235/ff3da0e8-c4c3-44fd-bc73-53d290316c57)

But Wakatime requires that I use:

![image](https://github.com/wakatime/vscode-wakatime/assets/29048235/598c835c-6dbf-4e2b-9dc0-0d47230e0927)

I tried to use the same setting I have in internet options, but that didn't work either.

![image](https://github.com/wakatime/vscode-wakatime/assets/29048235/a4836e04-9d11-4c6f-8c76-57e7d9468a4f)

What can I do?

**Comment by Tai-Zhou** [comment]
```typescript
public static validateProxy(proxy: string): string {
    if (!proxy) return '';
    let re;
    if (proxy.indexOf('\\') === -1) {
      re = new RegExp('^((https?|socks5)://)?([^:@]+(:([^:@])+)?@)?[\\w\\.-]+(:\\d+)?$', 'i');
    } else {
      re = new RegExp('^.*\\\\.+$', 'i');
    }
    if (!re.test(proxy))
      return 'Invalid proxy. Valid formats are https://user:pass@host:port or socks5://user:pass@host:port or domain\\user:pass';
    return '';
  }
```

According to the code, you can use `http://10.1.33.254:80` or `https://10.1.33.254:80` (or even `10.1.33.254:80`), depends on your server.

**Comment by carloswm85** [comment]
It seems to be that changing `https` into `http` worked in my proxyed computer.

But now, I'm getting this message in two of my computers:

![image](https://github.com/wakatime/vscode-wakatime/assets/29048235/fbcf6194-eb18-4b91-bdf7-ebd87b65f676)

I've generated a new API key, and pasted it into VSCode. Do you know what may be the problem?

Also, do you know any good alternative to WakaTime? I'd like to get a full history of my activities, but I'm not currently able to pay their service (also, I'm wondering if the history generated in this application is somewhat portable into other apps).

**Comment by Tai-Zhou** [comment]
> But now, I'm getting this message in two of my computers:
>
> I've generated a new API key, and pasted it into VSCode. Do you know what may be the problem?

Maybe you should turn on the Command Palette (`Ctrl+Shift+P`) and input `wakatime api key` and paste the key again.

> Also, do you know any good alternative to WakaTime? I'd like to get a full history of my activities, but I'm not currently able to pay their service (also, I'm wondering if the history generated in this application is somewhat portable into other apps).

Sorry I have no idea for that.

**Comment by alanhamlett** [comment]
@carloswm85 I looked into your account it it shows as receiving data from you VS Code now, so you got it working?

Closing this issue as fixed.

**Comment by carloswm85** [comment]
> @carloswm85 I looked into your account it it shows as receiving data from you VS Code now, so you got it working?
> 
> Closing this issue as fixed.

How many computers can you see? If there's 2 of them, it seems to be fixed.

**Comment by alanhamlett** [comment]
> How many computers can you see? If there's 2 of them, it seems to be fixed.

I see two, which you can check here: https://wakatime.com/api/v1/users/current/machine_names

Also, I recommend typing in vscode on the computer that wasn't working, then check this page:
https://wakatime.com/plugins/status
Within a few minutes, that page should update showing your VS Code as last seen recently.
