### ISSUE TITLE
always says invalid api key even after i regenerated

### ISSUE THREAD

**Issue by ACnoway** [wakatime/vscode-wakatime#358]
vscode version: 1.80.0

wakatime extension version: 24.2.0

console image:

![QQ截图20230710104136](https://github.com/wakatime/vscode-wakatime/assets/91535478/a4b801c6-fc95-4ef4-b3cd-5e29b4dfc75b)

I regenerated my api key but it still doesn't work

**Comment by ACnoway** [comment]
log:
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:21:22+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:23+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:25+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:34+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:42+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:49+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:51+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:52+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:22:54+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:24:54+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:24:54+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:18+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:25:18+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:25+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:25:25+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:30+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:25:30+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:32+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:25:32+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:35+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) failed: invalid api key... find yours at wakatime.com/api-key. failed to load command parameters: failed to load api params: invalid api key format","now":"2023-07-10T10:25:35+08:00","version":"v1.54.0"}
{"caller":"cmd/run.go:105","func":"cmd.Run","level":"debug","message":"command: heartbeat","now":"2023-07-10T10:25:41+08:00","version":"v1.54.0"}

**Comment by ACnoway** [comment]
checked my config file and it looks like this:
```
[settings]
api_key = waka_XXXXXXXXXXXXX
disabled = false
debug = true
proxy = https://127.0.0.1:31181
```

**Comment by alanhamlett** [comment]
The error message is in your logs:

`invalid api key format`

Copy/paste your api key from https://wakatime.com/api-key into your config file or inside vscode's `WakaTime: API Key` command prompt.
