### ISSUE TITLE
Time not getting updated as normal - Certificate has expired

### ISSUE THREAD

**Issue by AntonioIvanov** [wakatime/vscode-wakatime#360]
Hi, 

So, during the last week, I've been experiencing some issues with the extension. At first, I thought it wasn't updating the time on the dashboard, but when I checked the dashboard today, all of my progress for the week is there. However, it isn't getting updated as normal because the extension is taking longer than usual (sometimes even one day or more). Additionally, on the status bar, it always stops at 0s or 15 minutes.

on the logs i'm getting this error:

`{"caller":"cmd/run.go:301","file":"/pathtofile","func":"cmd.runCmd","level":"error","lineno":209,"message":"failed to run command: sending heartbeat(s) failed: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-06-18T06:54:34-06:00 is after 2023-09-22T07:07:04Z","now":"2024-06-18T06:54:35-06:00","os/arch":"darwin/amd64","plugin":"vscode/1.80.1 vscode-wakatime/24.2.0","time":1718715273.898933,"version":"v1.73.1"}`

so i think it was because i changed my current time since i was testing something on my application but i didn't realize that was going to affect to wakatime, i don't know how to fix this issue

Operating System: macOS 12.6.3
Wakatime Version: 24.2.0
Visual Studio Code Version: 1.80.1

Things i already tried:

- Restart vscode
- Change the api key
- Reinstall the plugin
- Change the version of plugin
- Logout and login from my account of wakatime

**Comment by alanhamlett** [comment]
The error message: `current time 2024-06-18T06:54:34-06:00 is after 2023-09-22T07:07:04Z`

Also notice the log says it things today is June 18th 2024, `"now":"2024-06-18T06:54:35-06:00"`, about 11 months in the future.

Having your computer's time set in the future breaks SSL cert verification. It might also be causing issues for other programs, not just WakaTime. To fix it, change your time back to `July 28, 2023`.

**Comment by AntonioIvanov** [comment]
Hi i already double checked that the time is back to normal and it is, so i don't know why wakatime is not updating yet
