### ISSUE TITLE
Support IPv6 proxy address

### ISSUE THREAD

**Issue by Tai-Zhou** [wakatime/vscode-wakatime#361]
It seems current proxy address validator doesn't support IPv6 address. I've also tried to modify the `.wakatime.cfg` file, but does not work. The log file shows `failed to load API parameters: invalid url \"http://[2606:4700:4700::64]:53\". Must be in format'https://user:pass@host:port' or 'socks5://user:pass@host:port' or 'domain\\\\user:pass.'` (I've replaced the real address).

https://github.com/wakatime/vscode-wakatime/blob/dce156f460930fc9156781b88bf1172d7ec8aa46/src/utils.ts#L24

**Comment by Tai-Zhou** [comment]
A workaround:
1. Add the IPv6 address to the hosts file, followed by a fake domain name.
2. Replace the address with the fake domain name.

**Comment by alanhamlett** [comment]
Fixed in v24.2.1.
