### ISSUE TITLE
Error fetching `wakatime-cli`

### ISSUE THREAD

**Issue by boxsnake** [wakatime/vscode-wakatime#369]
There seems a error when fetching `wakatime-cli` in this plugin.

![image](https://github.com/wakatime/vscode-wakatime/assets/3257783/25336e39-3ecc-409e-9190-cb7acf73cf3a)

The [API url](https://api.github.com/repos/wakatime/wakatime-cli/releases/latest) is not accessible in browser, and it shows like following:

(Redirected to [this url](https://github.com/repos/wakatime/wakatime-cli/releases/latest))

![image](https://github.com/wakatime/vscode-wakatime/assets/3257783/2265e5a1-e3fe-4d54-a611-75f5a33c5637)

**Comment by gandarez** [comment]
Are you in China? It seems to be a temporary problem. I can open https://api.github.com/repos/wakatime/wakatime-cli/releases/latest.

**Comment by boxsnake** [comment]
Similar to https://github.com/wakatime/jetbrains-wakatime/issues/268

**Comment by alanhamlett** [comment]
Closing as duplicate to https://github.com/wakatime/jetbrains-wakatime/issues/268.
