### ISSUE TITLE
Status bar event listeners

### ISSUE THREAD

**Issue by DevVali** [wakatime/vscode-wakatime#373]
Hi 👋. I would like to ask a question about the code - on what event listener(s) does the status bar get updated? 

Thank you.

**Comment by alanhamlett** [comment]
It's updated after sending heartbeat stats to the API, which means it's updated after some typing or other activity in your editor:

https://github.com/wakatime/vscode-wakatime/blob/8d101cb502f031ff7fa83cb907ba0f7e8303ed9c/src/wakatime.ts#L591
