### ISSUE TITLE
Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by DavidFrahm** [wakatime/vscode-wakatime#38]
Today I installed this plugin in VS Code for Linux, and the install went great but it wasn't reporting data. So I checked the Developer Tools and found this error in the console:

```
[Extension Host] Activating extension 'WakaTime.vscode-wakatime' failed: Cannot find module 'tough-cookie'.
```

I've been using wakatime for a long time via WebStorm, so this is the first time I've tried it with VS Code. My Linux is Ubuntu 16.04 (xenial). 

Here's a screenshot of the console:

![wakatime-vscode-console-error](https://user-images.githubusercontent.com/889791/33866786-4669d8dc-debe-11e7-8574-0045dd13a066.png)

**Comment by alanhamlett** [comment]
Can you try re-installing? The `request` library depends on tough-cookie so there was probably an error when installing dependencies for vscode-wakatime.

**Comment by DavidFrahm** [comment]
Thanks @alanhamlett, a simple reinstall did the trick.
