### ISSUE TITLE
Wakatime not working: Failed to download wakatime-cli

### ISSUE THREAD

**Issue by Harrylever** [wakatime/vscode-wakatime#382]
Hi, I'm using vscode-wakatime plugin and I always get stuck at Initializing wakatime or Wakatime Initialized, but wakatime never works.
I open up Developer tools on vscode and I get error
```
[Extension Host] [WakaTime][DEBUG] Initializing WakaTime v24.4.0
console.ts:137
[Extension Host] [WakaTime][DEBUG] Status bar icon enabled.
console.ts:137
[Extension Host] [WakaTime][DEBUG] Downloading wakatime-cli from GitHub...
log.ts:421
INFO [perf] Render performance baseline is 182ms
log.ts:421  
INFO Extension host (LocalProcess pid: 21492) is unresponsive.
log.ts:421  
INFO Extension host (LocalProcess pid: 21492) is responsive.
console.ts:137 
[Extension Host] [WakaTime][WARN] Failed to download https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip
w @ console.ts:137
console.ts:137 
[Extension Host] [WakaTime][WARN] Error: read ECONNRESET
w @ console.ts:137
[Extension Host] [WakaTime][DEBUG] WakaTime initialized
console.ts:137 
```

I have followed all the steps on the troubleshooting page, but have found no solution. Please help

**Comment by alanhamlett** [comment]
Do you have a proxy set in your `~/.wakatime.cfg` file?

**Comment by Harrylever** [comment]
> Do you have a proxy set in your `~/.wakatime.cfg` file?

No. I don't

Here is my cfg file

[settings]
api_key = xxx
debug = true

**Comment by alanhamlett** [comment]
Can you manually download that file?
https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip

If it works, unzip it to `%USERPROFILE%/.wakatime/` then rename `%USERPROFILE%/.wakatime/wakatime-cli-windows-amd64.exe` to `%USERPROFILE%/.wakatime/wakatime-cli.exe`.

**Comment by Harrylever** [comment]
Hi @alanhamlett . Thanks for the reply. It suddenly started working yesterday. Working perfectly. And I didn't change anything.
