### ISSUE TITLE
Open social media and other links on profile page in a new tab

### ISSUE THREAD

**Issue by FREDVUNI** [wakatime/vscode-wakatime#383]
Issue:
Currently, the social media links (GitHub, LinkedIn, Twitter, personal website) in the profile page open in the same tab. It would be beneficial to have them open in a new tab to improve user experience.

Suggestion:
I suggest modifying the behavior of these links to open in a new tab, allowing users to keep their and other WakaTime profile pages open.

screenshot:

![image](https://github.com/wakatime/vscode-wakatime/assets/41730664/fb48906c-9fa7-4538-a84b-0a8dc829b7c9)

**Comment by alanhamlett** [comment]
I don't like forcing new tab, because the link can always be opened in a new tab with CTRL/CMD clicking. GitHub profiles also don't open links in new tabs.
