### ISSUE TITLE
Error in VSCode(Mac)

### ISSUE THREAD

**Issue by The-Riddles** [wakatime/vscode-wakatime#39]
Hi,

I get error below when I use wakatime in IDE VSCode for mac.

I did not find this document, I do not know why.
```
pythonw: can't open file '/Users/mars/.vscode/extensions/WakaTime.vscode-wakatime-1.1.22/out/wakatime-master/wakatime/cli.py': [Errno 2] No such file or directory
```
And i just find an zip file below:
 `/Users/mars/.vscode/extensions/WakaTime.vscode-wakatime-1.1.22/out/wakatime-master.zip `

Then i tail `~/.wakatime.log` but it's empty.

I can provide more debugging information if needed.

Thanks.

**Comment by alanhamlett** [comment]
Can you try re-installing the extension? That looks like the [wakatime-cli](https://github.com/wakatime/wakatime) dependency failed to download.

**Comment by The-Riddles** [comment]
Thanks for provide url, I trying manually download `wakatime-cli` and it running success.
