### ISSUE TITLE
WakaTime Initializing forever in Remote-WSL2

### ISSUE THREAD

**Issue by ishiko732** [wakatime/vscode-wakatime#391]
I have enabled the Wakatime extension on 'WSL: Ubuntu-24.04,' but it remains stuck at the `Initializing` stage. I attempted to resolve this by cloning the repository using `git clone https://github.com/wakatime/wakatime-cli/releases/download/v1.90.0/wakatime-cli-linux-amd64.zip` and copying it to `~/.vscode-server/extensions/wakatime.vscode-wakatime-24.5.0/wakatime-cli`. I then granted permissions using `sudo chmod 755 ./wakatime-cli` but the issue persists. Additionally, I noticed that every time I reload the VS Code window, it downloads `wakatime-cli' + this.randStr() + '.zip'` in the `~/.wakatime` folder.
![image](https://github.com/wakatime/vscode-wakatime/assets/62931549/525eb210-cddb-472b-b611-0d536aec7efe)

`~/.wakatime` folder :
![image](https://github.com/wakatime/vscode-wakatime/assets/62931549/294e2973-e41c-411a-91f2-6fe9fa2f9f4a)
Additionally, if I don't manually place the `wakatime-cli` file in '~/.vscode-server/extensions/wakatime.vscode-wakatime-24.5.0/wakatime-cli', the `wakatime.log` file does not appear.

`~/.wakatime/wakatime.log`:
```
{"caller":"cmd/run.go:158","func":"cmd.Run","level":"warning","message":"one of the following parameters has to be provided: --config-read, --config-write, --entity, --offline-count, --print-offline-heartbeats, --sync-offline-activity, --today, --today-goal, --useragent, --version","now":"2024-05-26T13:31:39+08:00","os/arch":"linux/amd64","version":"v1.90.0"}
```

`~/.vscode-server/extensions/wakatime.vscode-wakatime-24.5.0` folder:
![image](https://github.com/wakatime/vscode-wakatime/assets/62931549/eaa0a5b3-6c05-4312-bb1d-71bbff50c129)

**Comment by ishiko732** [comment]
> Try to place the executable file you unzipped to `~/.wakatime/wakatime-cli` then restart VS Code. It works for me.

I tried setting up a proxy in Ubuntu and added the proxy settings in VS Code, and it started working.

**Comment by JensenJin19** [comment]
> > Try to place the executable file you unzipped to `~/.wakatime/wakatime-cli` then restart VS Code. It works for me.尝试将解压缩的可执行文件放置到`~/.wakatime/wakatime-footer，`然后重新启动VS Code。这对我很有效。
> 
> I tried setting up a proxy in Ubuntu and added the proxy settings in VS Code, and it started working.我尝试在Ubuntu中设置代理，并在VS Code中添加代理设置，它开始工作。

Thank you very much. This answer helped me a lot.

**Comment by NoNormalCreeper** [comment]
> > Try to place the executable file you unzipped to `~/.wakatime/wakatime-cli` then restart VS Code. It works for me.
> 
> I tried setting up a proxy in Ubuntu and added the proxy settings in VS Code, and it started working.

I already set up a proxy in both Windows, WSL2 and vscode, and other extensions can use proxy properly (like Copilot) but Wakatime cannot. The only files in `~/.wakatime` folder is serveral `wakatime-cli' + this.randStr() + '.zip'` which sizes are all `0`.

**Comment by alanhamlett** [comment]
@NoNormalCreeper try configuring the proxy in `~/.wakatime.cfg`?

**Comment by NoNormalCreeper** [comment]
> @NoNormalCreeper try configuring the proxy in `~/.wakatime.cfg`?

I've tried configuring. My `~/.wakatime.cfg` content:
```
[settings]
api_key = waka_xxxxxxxxxxxx
proxy = http://127.0.0.1:7890
disabled = false
```

Filling this proxy url in other plugin (e.g Copilot) config can work.

**Comment by alanhamlett** [comment]
But that's just a proxy back to your own computer... which is kind of pointless. Using an external proxy works for others probably because their ISP or country is blocking GitHub servers, which the plugins use to download wakatime-cli.

**Comment by NoNormalCreeper** [comment]
> But that's just a proxy back to your own computer... which is kind of pointless. Using an external proxy works for others probably because their ISP or country is blocking GitHub servers, which the plugins use to download wakatime-cli.

I have a program running on my local machine. It intercepts user web requests through the system's proxy settings, and then forwards the requests to different **external proxy servers** based on user-configured rules. That can work for breaking the blockade of GitHub servers. For me, setting up this proxy can help me to visit GitHub in browser, `git push`, vscode extensions, etc.

**Comment by KiritaniAyaka** [comment]
> I have a program running on my local machine in `7890` port. It intercepts user web requests through the system's proxy settings, and then forwards the requests to different **external proxy servers** based on user-configured rules. That can work for breaking the blockade of GitHub servers. For me, setting up this proxy can help me to visit GitHub in browser, `git push`, vscode extensions, etc.

Where's your proxy client running on? On NAT mode. `127.0.0.1` is actually pointing to your WSL system, not the Windows host.

If you are sure you are using NAT mode. Running `ipconfig` on Windows and check the IP address on the "Ethernet Adapter Ethernet (WSL)" label, and change the proxy configuration IP address to it.

**Comment by NoNormalCreeper** [comment]
> > I have a program running on my local machine in `7890` port. It intercepts user web requests through the system's proxy settings, and then forwards the requests to different **external proxy servers** based on user-configured rules. That can work for breaking the blockade of GitHub servers. For me, setting up this proxy can help me to visit GitHub in browser, `git push`, vscode extensions, etc.
> 
> Where's your proxy client running on? On NAT mode. `127.0.0.1` is actually pointing to your WSL system, not the Windows host.
> 
> If you are sure you are using NAT mode. Running `ipconfig` on Windows and check the IP address on the "Ethernet Adapter Ethernet (WSL)" label, and change the proxy configuration IP address to it.

My client running on Windows machine. However, I've set some WSL configs:

```
networkingMode=mirrored
dnsTunneling=true
hostAddressLoopback=true
```

Executing `curl` to `127.0.0.1:7890` command in WSL system can also get a response (`400 Bad Request` though, instead of `Connection refused`), so I think the proxy server is setting up properly.

**Comment by alanhamlett** [comment]
Does this work in WSL?

    curl --proxy http://127.0.0.1:7890 https://api.github.com/repos/wakatime/wakatime-cli/releases/latest

**Comment by ishiko732** [comment]
> My client running on Windows machine. However, I've set some WSL configs

My WSL config:
```
[experimental]
autoMemoryReclaim=gradual
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
```

**Comment by NoNormalCreeper** [comment]
> Does this work in WSL?
> 
> ```
> curl --proxy http://127.0.0.1:7890 https://api.github.com/repos/wakatime/wakatime-cli/releases/latest
> ```

Yes, it works, returning a huge json response.

**Comment by alanhamlett** [comment]
If that works then maybe we should upgrade from [request](https://www.npmjs.com/package/request) to [https.request](https://nodejs.org/api/https.html#httpsrequestoptions-callback) or [node-fetch](https://www.npmjs.com/package/node-fetch). It's just strange that proxies work for others with the current code.

**Comment by NoNormalCreeper** [comment]
> If that works then maybe we should upgrade from [request](https://www.npmjs.com/package/request) to [https.request](https://nodejs.org/api/https.html#httpsrequestoptions-callback) or [node-fetch](https://www.npmjs.com/package/node-fetch). It's just strange that proxies work for others with the current code.

Maybe, could you offer me some instructions on editing the source code? I'm not entirely sure about how differently does the different request libraries work. I could try to edit code myself, `npm run watch`, and check the behavior of the plugin.

**Comment by alanhamlett** [comment]
First before we modify the code let's look for the error message(s) to find why the proxy isn't working.

Please enable debug mode with this line in your `~/.wakatime.cfg` file:
`debug = true`

Then open your vscode dev console window to see console errors.
Next, reload vscode by running command `Developer: Reload window`.

Please paste any error messages printed in the vscode dev console here.

**Comment by NoNormalCreeper** [comment]
> First before we modify the code let's look for the error message(s) to find why the proxy isn't working.
> 
> Please enable debug mode with this line in your `~/.wakatime.cfg` file: `debug = true`
> 
> Then open your vscode dev console window to see console errors. Next, reload vscode by running command `Developer: Reload window`.
> 
> Please paste any error messages printed in the vscode dev console here.

Here's all the error messages I got from the dev tools Window, including messages from other plugins.

```
[Extension Host] [INFO] 2024-11-21T02:41:08.658Z - Translations initialized.
console.ts:137 [Extension Host] [INFO] 2024-11-21T02:41:08.676Z - Extension activated!
console.ts:137 [Extension Host] Looking for parseable documents...
console.ts:137 [Extension Host] Found no documents
console.ts:137 [Extension Host] [WakaTime][DEBUG] Initializing WakaTime v24.8.0
console.ts:137 [Extension Host] [WakaTime][DEBUG] Status bar icon enabled.
console.ts:137 [Extension Host] [WakaTime][DEBUG] Downloading wakatime-cli from GitHub...
console.ts:137 [Extension Host] [WakaTime][DEBUG] Using Proxy: http://127.0.0.1:7890
log.ts:439   ERR [Extension Host] (node:253139) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:253139) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
A @ ipc.net.ts:1022
(anonymous) @ ipc.net.ts:879
B @ event.ts:1243
fire @ event.ts:1274
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
(anonymous) @ browserSocketFactory.ts:231
B @ event.ts:1243
fire @ event.ts:1274
IPs.j.onload @ browserSocketFactory.ts:92
log.ts:439   ERR [Extension Host] (node:253139) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
console.ts:137 [Extension Host] (node:253139) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
A @ ipc.net.ts:1022
(anonymous) @ ipc.net.ts:879
B @ event.ts:1243
fire @ event.ts:1274
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
(anonymous) @ browserSocketFactory.ts:231
B @ event.ts:1243
fire @ event.ts:1274
IPs.j.onload @ browserSocketFactory.ts:92
console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, stat 'src/components'
    at statSync (node:fs:1666:25)
    at Object.n.statSync (/home/rikka/.vscode-server/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:3373)
    at Ru.searchLocalComponent (/home/rikka/.vscode-server/extensions/shenjiaolong.vue-helper-4.3.2/dist/client.js:12:2086)
    at /home/rikka/.vscode-server/extensions/shenjiaolong.vue-helper-4.3.2/dist/client.js:3:3361
    at Array.forEach (<anonymous>)
    at Ru.initLocalComponent (/home/rikka/.vscode-server/extensions/shenjiaolong.vue-helper-4.3.2/dist/client.js:3:3338)
    at /home/rikka/.vscode-server/extensions/shenjiaolong.vue-helper-4.3.2/dist/client.js:7484:3950
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
log.ts:419  INFO [perf] Render performance baseline is 16ms
log.ts:439   ERR [Extension Host] [default] Error sending telemetry FetchError: read ECONNRESET
    at fetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at pue.fetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: -104,
  erroredSysCall: 'read'
}
console.ts:137 [Extension Host] [default] Error sending telemetry FetchError: read ECONNRESET
    at fetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at pue.fetch (/home/rikka/.vscode-server/extensions/github.copilot-1.245.0/lib/src/network/helix.ts:93:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ECONNRESET',
  errno: -104,
  erroredSysCall: 'read'
}
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
A @ ipc.net.ts:1022
(anonymous) @ ipc.net.ts:879
B @ event.ts:1243
fire @ event.ts:1274
acceptChunk @ ipc.net.ts:394
(anonymous) @ ipc.net.ts:350
(anonymous) @ browserSocketFactory.ts:231
B @ event.ts:1243
fire @ event.ts:1274
IPs.j.onload @ browserSocketFactory.ts:92
log.ts:439   ERR connect ETIMEDOUT 51.104.15.252:443: Error: connect ETIMEDOUT 51.104.15.252:443
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
```

**Comment by alanhamlett** [comment]
Let's just get it working manually. Please download [the latest release](https://github.com/wakatime/wakatime-cli/releases/download/v1.105.0/wakatime-cli-linux-amd64.zip), unzip it and place the `wakatime-cli-linux-amd64` file into your WSL folder at `/home/rikka/.wakatime/wakatime-cli-linux-amd64` then copy it to `/home/rikka/.wakatime/wakatime-cli` and restart vscode.
