### ISSUE TITLE
Don't save API key in settings.json

### ISSUE THREAD

**Issue by Laurensdc** [wakatime/vscode-wakatime#395]
Setting.json is automatically synced by VSCode.
Furthermore, when using a dotfile version control system, it can get pushed to public repositories.
We need a way to have the API key not being exposed in plain text in the `settings.json` file.

**Comment by alanhamlett** [comment]
We don't save your api key to `settings.json`, it's saved to your user home folder at `~/.wakatime.cfg`.

**Comment by Laurensdc** [comment]
Ok I have no idea how my API key appeared in settings.json then, but thank you!
Verified that Wakatime still works when I delete the API key from settings, and re-setting it doesn't add it to settings.json.
