### ISSUE TITLE
Export raw data as CSV

### ISSUE THREAD

**Issue by IaVashik** [wakatime/vscode-wakatime#397]
Ability to export summary statistics and raw data for a given period as CSV

**Comment by IaVashik** [comment]
Wrong repository, meh..

**Comment by alanhamlett** [comment]
This command line tool converts our JSON export format to CSV:
https://github.com/wakatime/wakadump

**Comment by IaVashik** [comment]
> This command line tool converts our JSON export format to CSV:
> https://github.com/wakatime/wakadump

Sorry, I got confused in my tabs and opened a issue here by mistake. Anyway, thanks for the reply ^^
