### ISSUE TITLE
Make it so it says Cursor AI on the dashboard rather than visual studio code

### ISSUE THREAD

**Issue by jamiecropley** [wakatime/vscode-wakatime#399]
Make it so it says Cursor AI on the dashboard rather than visual studio code when using this editor instead, it also uses vs code extensions but does not recognise the difference.

**Comment by alanhamlett** [comment]
Yes, we did that in the release earlier today:

https://github.com/wakatime/vscode-wakatime/blob/master/CHANGELOG.md#2461-2024-08-30

Is new activity not showing as Cursor today?

**Comment by jamiecropley** [comment]
Only just seen this, sorry for slow response. Yes it works perfect! Many thanks.

**Comment by jamiecropley** [comment]
![image](https://github.com/user-attachments/assets/7f0dfaa1-5d4c-49ce-beae-7c440f6ae938)
