### ISSUE TITLE
Information Required: Idle State of Waka Time

### ISSUE THREAD

**Issue by technbuzz** [wakatime/vscode-wakatime#4]
I didn't know where to go when I have question, that's why I came here to ask
What happens if I leave my editor open for 5 hours and then come back and start using it. Do wakatime tracks those idle time? (which I don't want at all)

**Comment by alanhamlett** [comment]
Idle time isn't tracked unless you were away from your editor for less than your `timeout` setting from your Settings -> Preferences page:

https://wakatime.com/help/faq/general#what-happens-when-im-afk

**Comment by technbuzz** [comment]
Thanks I got my answers.
