### ISSUE TITLE
Wakatime Offline, coding activity will sync when online 

### ISSUE THREAD

**Issue by Spacebody** [wakatime/vscode-wakatime#40]
I have encountered this problem for several days in my editors such VSCode. And in Sublime text it is always showing "Wakatime initializing". I have no change in any setting files and I have computer accessed into the Internet but it doesn't work and no track data sync successfully to the API. Does there any problem in your servers or something else?
PS: I am in China...will the wall become cause the problem?

**Comment by alanhamlett** [comment]
Each plugin downloads [wakatime cli](https://github.com/wakatime/wakatime) from GitHub, then connects to `https://api.wakatime.com` to upload coding activity.

If connecting to GitHub fails, then your Developer Console window inside VS Code would have some error messages when you first open VS Code.

If there aren't any error messages in your Developer Console window, next try [turning on Debug mode](https://github.com/wakatime/vscode-wakatime#troubleshooting) then checking your `~/.wakatime.log` file to see connection issues when uploading coding activity.

**Comment by Spacebody** [comment]
It works now but for past few days it didn't work. The log file seems to be nothing wrong with respond code 202 or 405. I have turned the debug mode on. It is fine now. Thank you!

**Comment by alanhamlett** [comment]
Ok, make sure to turn off Debug mode when things are working since it disables async when in debug mode for some plugins.

**Comment by Spacebody** [comment]
Thanks for reminding.

**Comment by XJefferson0101** [comment]
WakaTime keep on synchronising even when I closed Sublime_Text

**Comment by AbhimanyuAryan** [comment]
@alanhamlett I have a similar problem with one of my pcs(vscode). Anyway I can find why is it happening? On the other PC it works fine
