### ISSUE TITLE
Typing BUG (not for bug label)

### ISSUE THREAD

**Issue by devmdeniz** [wakatime/vscode-wakatime#400]
When plugins like Typewriter Effect are used, wakatime continues to count the time as if I were typing. This can reduce the reliability of Wakatime. That is why I felt the need to open this issue.

Here's an example

https://github.com/user-attachments/assets/739fdf28-0dc9-48d4-96a7-71e4da01adac

**Comment by alanhamlett** [comment]
Yes, that vscode extension is simulating typing so WakaTime can't tell the difference. It's not compatible.

**Comment by devmdeniz** [comment]
> Yes, that vscode extension is simulating typing so WakaTime can't tell the difference. It's not compatible.

Kullanıcının yazması ile eklentinin yazması arasında bir fark bulabilir miyiz? Herhangi bir yolu yok mu?

**Comment by alanhamlett** [comment]
Where's a link to the plugin you're using on the marketplace, so I can see it's code?

**Comment by alanhamlett** [comment]
Let's see if it's fixed with b70816c9537228705af7ba48e58b325c77bdfcd3, released in v24.6.2 just now.

**Comment by devmdeniz** [comment]
> Let's see if it's fixed with [b70816c](https://github.com/wakatime/vscode-wakatime/commit/b70816c9537228705af7ba48e58b325c77bdfcd3), released in v24.6.2 just now.

I'm testing rn.
I'll let you know if the problem persists, Alan. Thank you for your help.

**Comment by devmdeniz** [comment]
> Let's see if it's fixed with [b70816c](https://github.com/wakatime/vscode-wakatime/commit/b70816c9537228705af7ba48e58b325c77bdfcd3), released in v24.6.2 just now.

I guess it didn't work. It still perceives me as if I'm writing code, but when I woke up today I noticed that the public leaderboard was closed but there was no warning in the Security events section. Maybe this detail can help you more.

Other than that, it seems like we can identify the user by logic errors. Is it logically possible for someone to write code for 9 hours without stopping according to wakatime's statistics? It is not possible to write code for 2 hours, let alone 9 hours (if wakatime only counts the time I write, not the time I stop, wait, think).
![image](https://github.com/user-attachments/assets/e604e565-ef0a-455a-914d-a74387be9a35)

It would not be an effective solution, but it seems to be a candidate for a temporary solution until there is a solution.

**Comment by devmdeniz** [comment]
> > I noticed that the public leaderboard was closed
> 
> Yes, that's our system detecting fake code stats so it removed you from the public leaderboard.
> 
> I have to ask, what's the point of this typewriter plugin? It seems like it has no usefulness, and since there's no way to detect automated typing vs real typing we shouldn't try to fix this further and just have a policy not to use typewriter plugins with WakaTime.

I think the purpose of Typewriter Effect is usually for people who make Tutorial videos to write their code in advance to make their videos more comfortable and then write more fluently using this plugin. It was an extension that I noticed by chance while looking for the Smooth Typing Effect setting in Visual Studio Code.
When I used it later, I realized that Wakatime was counting it as if I was writing code and I wanted to report it.

The solution you came up with seems to make a lot of sense. If I find a possible solution I will write to you again on this issue.
Thank you for your concern, Alan. Have a good day.
