### ISSUE TITLE
manually download wakatime-cli

### ISSUE THREAD

**Issue by HyberCa** [wakatime/vscode-wakatime#401]
Hi,
I have issue similar to #382. My network can’t access to GitHub so I manually downloaded the wakatime-cli, put it in %userprofile%/.wakatime/ and renamed it. However the wakatime is still stuck in Initialized. The developer tool shows that wakatime is still trying to download cli from GitHub. How can I fix it?

>Can you manually download that file?
>https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip
>
>If it works, unzip it to `%USERPROFILE%/.wakatime/` then rename `%USERPROFILE%/.wakatime/wakatime-cli-windows->amd64.exe` to `%USERPROFILE%/.wakatime/wakatime-cli.exe`.
>
>_Originally posted by @alanhamlett in https://github.com/wakatime/vscode-wakatime/issues/382#issuecomment-1925306153_

**Comment by alanhamlett** [comment]
It's trying to check the latest version from GitHub's API, to see if it needs to update your wakatime-cli.

The easiest way to fix that is:
1. [download wakatime-cli source code](https://github.com/wakatime/wakatime-cli/archive/refs/tags/v1.98.3.zip)
2. Extract the zip file
3. Open a terminal and cd to the `wakatime-cli` repo folder
4. `make install-go-modules`
5. `make`
6. Copy `bin/wakatime-cli-windows-amd64.exe` to `~/.wakatime/wakatime-cli.exe`

Now when you reload vscode it will detect the local built wakatime-cli and will skip updating.

**Comment by HyberCa** [comment]
I tried this solution but failed. Maybe because there are a lot of restrictions on my corporate computer. 
but I managed to install and run wakatime on my personal computer. I copied .wakatime folder to my corporate computer. Then it worked.

**Comment by HyberCa** [comment]
I also found that in my computer it is waistline-cli-windows-amd64.exe rather than wakatime-cli.exe.
