### ISSUE TITLE
Configure api url

### ISSUE THREAD

**Issue by ChristianJohn-Softwareentwicklung** [wakatime/vscode-wakatime#402]
The api url is hardcoded on several request. 
I want to make the api url configurable to be able to use other wakatime clones like wakapi.

**Comment by alanhamlett** [comment]
Only for the web extension, but if you're using normal VS Code then it's not hard-coded. You can change it in your `~/.wakatime.cfg` with the `api_url` key.

**Comment by chicco-carone** [comment]
> Only for the web extension, but if you're using normal VS Code then it's not hard-coded. You can change it in your `~/.wakatime.cfg` with the `api_url` key.

I'm currently using vscode-docker (linuxserver.io image) and can't find the wakatime config file in  ~/.wakatime.cfg so i can't change the api_url variable. As a feature request i would like during the initial setup to ask as an optional parameter for the api url and if it's not provided to use the default wakatime one
