### ISSUE TITLE
Ability to change URL for wakatime via settings.

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [wakatime/vscode-wakatime#403]
Since on the browser version there is no wakatime config file you cannot change the extra settings it provides including the api url. 
i think this should be added into vscode settings so that you can change them.

**Comment by NeonGamerBot-QK** [comment]
any updates on this?

**Comment by RandomSearch18** [comment]
Hi, I'm planning on working on this feature, at least adding it to the web version and possibly the non-web version too. If the maintainer(s) have any thoughts on how it should be implemented, please let me know :)

**Comment by alanhamlett** [comment]
Implemented with 44a84bf418d6546ee3aa44693fa15d715857e279.
