### ISSUE TITLE
All projects are reported with the same name

### ISSUE THREAD

**Issue by chicco-carone** [wakatime/vscode-wakatime#404]
The majority of my project are all getting counted as "chicco" from vscode even if I always open the whole folder instead of only one file. 

Log from vscode console
`[Extension Host] [WakaTime][DEBUG] Sending heartbeat: /usr/bin/wakatime-cli --entity /home/chicco/Nextcloud/Scuola/aRobe/Domotica/appunti.md --plugin "\"vscode/1.94.2 vscode-wakatime/24.6.2\"" --lineno 9 --cursorpos 43 --lines-in-file 9 --alternate-project Domotica --project-folder /home/chicco/Nextcloud/Scuola/aRobe/Domotica --write`

Screenshot from wakapi with the projects
![Screenshot_20241015_145308](https://github.com/user-attachments/assets/9bdc196f-d297-4cd8-b872-6bf836abae39)

**Comment by alanhamlett** [comment]
Do you have a `.wakatime-project` file or `.git` folder in your `chicco` folder?

**Comment by chicco-carone** [comment]
I don't have a .wakatime-project folder and a git folder just in some projects but not all. The issue for me is that i don't have any folder called chicco but the majority of my projects are getting counted under that name. Sometimes it happens for project that have a .git folder so in the project info you can find the info about the branch but it's the wrong information

**Comment by chicco-carone** [comment]
Today when opening vscode i noticed that it  gave me an issue about a repository having too many files named "chicco" and after that i noticed that for projects that didn't have a git repo it would use the root repository named chicco which was in ~/ and I didn't notice that i made it. So after removing the .git folder from my home folder it started working again and counted all project in the correct way.
