### ISSUE TITLE
Name of the project

### ISSUE THREAD

**Issue by walkero-gr** [wakatime/vscode-wakatime#41]
Hello there,
Great plugin. Thank you for creating it. 
Is there a way to set the name of the project? Currently it gets the folder name of the project, which in my situation is always named "public_html", and I can't separate the projects at wakatime. Maybe an optional variable at the project vscode file would be the best way to do it.

Thank you for your help.

**Comment by alanhamlett** [comment]
Use one of these methods to set your project names:

* wakatime.cfg project map
* `.wakatime-project` file in your project folder

[More info here](https://wakatime.com/faq#rename-projects)
