### ISSUE TITLE
Wakatime Error from opening VSCode

### ISSUE THREAD

**Issue by Zes-MinKey-Young** [wakatime/vscode-wakatime#412]
My wakatime hasn't be working for nearly a year. Today I thought it was too old, but nothing changed after updating it. I've switched to debug mode and collected the error message as followed. It's really disturbing that the  `C:\Users\Administrator\.wakatime\wakatime.log` is always blank. File `C:\Users\Administrator\.wakatime.log` has stopped logging since last year, and after being deleted it never appeared again.

```
[Extension Host] [WakaTime][ERROR] Error: Command failed: C:\Users\Administrator\.wakatime\wakatime-cli-windows-amd64.exe --entity e:\zes\VSCode\kpa\kpa.code-workspace --plugin "vscode/1.70.2 vscode-wakatime/24.9.1" --lineno 12 --cursorpos 23 --lines-in-file 17 --alternate-project kpa --project-folder e:\zes\VSCode\kpa --config C:\Users\Administrator\.wakatime.cfg --log-file C:\Users\Administrator\.wakatime\wakatime.log
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x3c0300060009)
	C:/hostedtoolcache/windows/go/1.23.3/x64/src/runtime/sys_windows_amd64.s:76 +0x89 fp=0x26f960 sp=0x26f940 pc=0x120b389
rax     0x0
rbx     0x21287c0
rcx     0x21706a8
rdx     0x20
rdi     0x7fffffdd000
rsi     0x26fb58
rbp     0x26faa0
rsp     0x26f938
r8      0x21284e0
r9      0x21701ca
r10     0x2fa2e8
r11     0xc000004000
r12     0x26fba8
r13     0x0
r14     0x2127080
r15     0x3
rip     0x0
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b


[WakaTime][ERROR] Unknown Error (2); Check your C:\Users\Administrator\.wakatime\wakatime.log file for more details
```
Heartbeats API:
```
{
  "data": [],
  "end": "2024-11-24T15:59:59Z",
  "start": "2024-11-23T16:00:00Z",
  "timezone": "Asia/Shanghai"
}
```

I'm really a noob in computing so I beg detailed instructions. Thanks.

**Comment by alanhamlett** [comment]
Are you using Windows 7? A while back Go dropped support for Win7 and this seems like a related crash.

**Comment by alanhamlett** [comment]
Similar to #278, we will need to detect older operating systems and download a past version of wakatime-cli which still supported that os.

**Comment by AstaDK** [comment]
The same issue with MacOS

`[WakaTime][ERROR] Error: Command failed: /../.wakatime/wakatime-cli-darwin-arm64 --entity /../Templates/treact/public/index.html --plugin "vscode/1.85.1 vscode-wakatime/24.9.1" --lineno 13 --cursorpos 5 --lines-in-file 79 --alternate-project treact --project-folder /.../Templates/treact --write`

**Comment by AstaDK** [comment]
> The same issue with MacOS
> 
> `[WakaTime][ERROR] Error: Command failed: /../.wakatime/wakatime-cli-darwin-arm64 --entity /../Templates/treact/public/index.html --plugin "vscode/1.85.1 vscode-wakatime/24.9.1" --lineno 13 --cursorpos 5 --lines-in-file 79 --alternate-project treact --project-folder /.../Templates/treact --write`
> 
> sudo ~/.wakatime/wakatime-cli-darwin-arm64 --version ===> `v1.105.2` sudo ~/.wakatime/wakatime-cli --version ===> `v1.105.2` wakatime.vscode-wakatime version `24.9.1` Visual Studio Code - Insiders version `1.96.0-insider` Visual Studio Code version `Version: 1.85.1`
> 
> cc @alanhamlett @gandarez

More info log:

{"level":"error","now":"2024-11-21T09:49:29+07:00","caller":"cmd/run.go:344","func":"github.com/wakatime/wakatime-cli/cmd.runCmd","message":"failed to run command: sending heartbeat(s) failed: won't send heartbeat due to backoff without proxy","version":"v1.105.0","os/arch":"darwin/arm64","file":"/../cadence.ts","time":1732157369.035973,"plugin":"vscode/1.96.0-insider vscode-wakatime/24.8.0","lineno":43,"is_write":true}
{"level":"debug","now":"2024-11-21T10:07:27+07:00","caller":"cmd/run.go:106","func":"github.com/wakatime/wakatime-cli/cmd.RunE","message":"command: version","version":"v1.105.0","os/arch":"darwin/arm64"}

**Comment by gandarez** [comment]
@Zes-MinKey-Young can you join us on slack to help us testing the binary built for windows 7?

**Comment by gandarez** [comment]
@Zes-MinKey-Young ping

**Comment by alanhamlett** [comment]
@Zes-MinKey-Young the last data from your vscode was from:

* vscode-wakatime v23.1.0
* wakatime-cli v1.86.5 built for windows with go1.21.3

What Windows OS version are you using? Without more info we can't debug this further, closing until receiving more info.
