### ISSUE TITLE
Extension host terminated unexpectedly on Windows 10

### ISSUE THREAD

**Issue by tophatsteve** [wakatime/vscode-wakatime#42]
Whenever I enable the WakaTime plugin and reload the editor, I get the following error message displayed at the top of the screen:

![capture](https://user-images.githubusercontent.com/1632959/34252774-df911004-e63c-11e7-8af0-2af14e2decb6.PNG)

If I click the Developer Tools button, the following errors are shown in the console:

![capture2](https://user-images.githubusercontent.com/1632959/34252853-269969e2-e63d-11e7-84e7-355940f17351.PNG)

**Comment by Animam** [comment]
I meet this problem too.

**Comment by alexneo2003** [comment]
VS Code
`Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64`

Wakatime: 1.2.3

![image](https://user-images.githubusercontent.com/11705902/42725587-c83c8c14-878e-11e8-9916-f5e929f5871b.png)

**Comment by Nihileon** [comment]
I have solved this problem. You can check you environment variable and find if there is a ';' at the end of your path

**Comment by alanhamlett** [comment]
Then remove the `;` from the end of your path and everything works?

Would this be a bug in VS Code?

**Comment by alexneo2003** [comment]
@alanhamlett yep, this fix my problem.
Bug in my PC and me))

**Comment by mazensharkawy** [comment]
I have the same problem. However I have no trailing semi-colons in my path environment variable. I also tried adding one, just in case you meant I must have a trailing semi-colon. 
I wonder how this could be solved 
![screenshot 110](https://user-images.githubusercontent.com/24762902/42837367-349b6512-89fe-11e8-81fd-c4668c31d41a.png)
