### ISSUE TITLE
[SOLVED] wakatime offline, coding activity will sync when wakatime is online

### ISSUE THREAD

**Issue by dalvarezsmiet** [wakatime/vscode-wakatime#45]
I have this message in the status bar of VSCode since a few days. The computer has connection to Internet and I don't know what's going on.

I looked at the .wakatime.log and it's empty (0 Bytes) but the .wakatime.db is 40 KB. Settings are standard.

Any ideas on how to solve this?

**Comment by crioto** [comment]
Same situation here. Wakatime logs around 15-20 minutes in total. Most of the time status bar says it's offline and sometimes it becomes "Active" for a few seconds. 
Latest vscode on Arch Linux.

**Comment by dalvarezsmiet** [comment]
Python is not installed locally, which version should I choose: 2, or  3?

This is running in a Windows 10 with VSCode 1.20.1

**Comment by dalvarezsmiet** [comment]
SOLVED, I realized that wakatime plugin uses version snippets to accommodate to version 2 and 3, so I just went ahead and installed latest one. It's now working fine.

**Comment by alanhamlett** [comment]
Glad it's working now, upgrading the vscode-wakatime plugin fixed the issue or upgrading a different library?

**Comment by dalvarezsmiet** [comment]
Just installing python (version 3 in my case) solved the issue. Nothing inherently related with the plugin, although installation instructions should tell the user to have python installed as a prerequisite. Maybe it should be included in the README.md file...

**Comment by alanhamlett** [comment]
An embedded Python should be downloaded and used when not already installed:
https://github.com/wakatime/vscode-wakatime/blob/94885f8103b836aafc8bf5c3b59a10c7e40f49bf/src/extension.ts#L650

Maybe you had a very old version of Python installed that's not compatible with WakaTime?

**Comment by YeomanLi** [comment]
> Same situation here. Wakatime logs around 15-20 minutes in total. Most of the time status bar says it's offline and sometimes it becomes "Active" for a few seconds.
> Latest vscode on Arch Linux.

Same here, and My OS is also Arch Linux, btw, have you solved this problem?
