### ISSUE TITLE
Detect unsaved files

### ISSUE THREAD

**Issue by mpearon** [wakatime/vscode-wakatime#46]
I'm not sure what type of file type detection that vsCode offers the plugin, but would it be possible to count time spent with unsaved files?  Maybe look at the active language in the editor pane?

**Comment by mpearon** [comment]
@alanhamlett - Is this something you might look at?

**Comment by alanhamlett** [comment]
We can add a `--transient` argument to https://github.com/wakatime/wakatime and pass the language from VS Code with `--alternate-language=<language>`. However, it would need to be opt-in since most people wouldn't like seeing `Unknown Project` with only a few seconds logged before they saved the file.

**Comment by mpearon** [comment]
@alanhamlett - Is this still being considered?

**Comment by alanhamlett** [comment]
Yes, another option would be writing the first 512kb of the unsaved file to a temporary file then a new argument `--entity-temp-file` that tells [wakatime-cli][https://github.com/wakatime/wakatime] where to find the temporary file for the unsaved file. That way we use the existing language and project detection when tracking unsaved files.

**Comment by mpearon** [comment]
Evidently, I missed this question!  I'm sorry.
I'm not sure about that.  It could simply be 'Unsaved' or 'Uncommitted'.  That would give the hint that the user was working interactively, or something.

**Comment by mpearon** [comment]
@alanhamlett Is this still a consideration?

**Comment by mpearon** [comment]
Just a reminder. :)

**Comment by gandarez** [comment]
@alanhamlett any update here?

**Comment by gandarez** [comment]
Can VSCODE detect unsaved entity and set `--is-unsaved-entity` flag @alanhamlett?

**Comment by alanhamlett** [comment]
We currently do this for sql queries because they're not saved to disk. We can do this for unsaved files too.
