### ISSUE TITLE
Feature request: Get rid of "WakaTime Initialized" in status bar

### ISSUE THREAD

**Issue by perlun** [wakatime/vscode-wakatime#47]
Hi,

First, thanks for a great product & VSCode extension. I love to keep track of what I'm working on, and Wakatime helps me with that.

Now, to my problem: it takes up way too much space in the VSCode status bar.

<img width="158" alt="image" src="https://user-images.githubusercontent.com/630613/37270665-4bbf3348-25d8-11e8-8259-15735e292b9b.png">

This in itself is not a big deal, but my VSCode status bar is overly cluttered will all kinds of things. Being able to just show the icon would be much more useful for me.

Can it be done?

**Comment by alanhamlett** [comment]
Released in v1.1.23 just now.

**Comment by alanhamlett** [comment]
That's what 57878eb479d0b164774f2d8920931854e98b9302. Same as gitlense it sets the tooltip text and removes the status bar text. We also have an option to fully remove WakaTime from your status bar, by pressing `CMD + Shift + p` then changing the WakaTime Status Bar Icon setting.

<img width="595" alt="screen shot 2018-03-13" src="https://user-images.githubusercontent.com/522344/37352219-fdd634fc-2699-11e8-877f-89f4902ba2bf.png">
