### ISSUE TITLE
Wakatime: working offline but I am online

### ISSUE THREAD

**Issue by gareth-d85** [wakatime/vscode-wakatime#48]
So the icon at the bottom says I'm offline but I am online, have tried reinstalling the extension but that has not fixed it.

**Comment by alanhamlett** [comment]
Sometimes that happens if you require a proxy to connect to the internet, such as in a corporate work LAN. Does your dashboard still update today?

If not, try upgrading to v1.1.24 and that message is moved to the status bar tooltip instead of the status bar text.

**Comment by gareth-d85** [comment]
Yeah it does still update the dashboard, but I don't think I require a proxy to connect.
I will close the issue as my dash does update.
