### ISSUE TITLE
vscode-wakatime takes too long to start

### ISSUE THREAD

**Issue by sobolevn** [wakatime/vscode-wakatime#53]
![2018-05-12 15 46 57](https://user-images.githubusercontent.com/4660275/39957427-c25c79e0-55fb-11e8-9e52-dc5df9043d1b.png)

Is there anything that can be done to reduce startup timings?

**Comment by alanhamlett** [comment]
Fixed with 5bbe0fe98bf2b2c614e981abfb76ac61ed1e9c3d.

<img width="1469" alt="screen shot 2018-05-12 at 7 07 23 pm" src="https://user-images.githubusercontent.com/522344/39963134-3561569c-5618-11e8-84ff-51dec94f1d39.png">
