### ISSUE TITLE
Not registering files over a network disk (NAS in windows)

### ISSUE THREAD

**Issue by gsabater** [wakatime/vscode-wakatime#56]
Hello,

First of all, great plugin. 

Lately I have been working on a project that is located in an external disk mounted over a network location. The disk is mounted in windows in the location `\\DISKSTATION\project\`.

I can open the project in vscode and everything works fine, except that wakatime that is not registering any activity in that project. My dashboard is empty.

The wierd part is that the plugins seems to be sending heartbeats:
![keke](https://user-images.githubusercontent.com/4948172/41344893-80b6acd4-6f02-11e8-92a3-e2008ebfe8de.JPG)

Let me know if I can do something to help locate any bug.
Salut and thanks for your time.

**Comment by alanhamlett** [comment]
Let's [turn on debug mode](https://github.com/wakatime/vscode-wakatime#troubleshooting) in the WakaTime plugin settings to see which path is being sent to [wakatime-cli](https://github.com/wakatime/wakatime. What's probably happening is wakatime-cli does not think the file exists and skips actually sending the heartbeat, but normally that doesn't raise an error:
https://github.com/wakatime/wakatime/blob/3373ef39e40971eba2cfc9e40fb5a013f56d63d6/wakatime/heartbeat.py#L86

**Comment by gsabater** [comment]
@alanhamlett , enabling debug mode and opening dev tools returns this for a heartbeat.

![debug](https://user-images.githubusercontent.com/4948172/41359374-a87f180a-6f2a-11e8-976b-13db795400fe.JPG)

**Comment by alanhamlett** [comment]
And in your `~/.wakatime.log` file you see it skipping the heartbeat for that file? This is actually a duplicate of wakatime/wakatime#72.

**Comment by gsabater** [comment]
@alanhamlett Yes, looks like the file is skipped `File does not exist; ignoring this heartbeat`
Looks like a duplicate, I searched for similar issues before posting but i didn't see that one. Sorry

Closing this one.

**Comment by alanhamlett** [comment]
Thanks, let's follow up there. WakaTime should be able to read remote files if your editor can, so hopefully we can get that other issue resolved.

**Comment by alanhamlett** [comment]
This should be working with the latest release of wakatime-cli (v10.4.0):

https://github.com/wakatime/wakatime/blob/master/HISTORY.rst#1040-2018-10-03
