### ISSUE TITLE
Time is not getting tracked in windows version of vscode when my git config mail is different from wakatime account

### ISSUE THREAD

**Issue by chakrihacker** [wakatime/vscode-wakatime#57]
I am using different mail id for one project. I am not able to track the time I spent on that repo please help

**Comment by alanhamlett** [comment]
Sure, what error do you see when debug mode is turned on? https://github.com/wakatime/vscode-wakatime/blob/master/README.md#troubleshooting

**Comment by chakrihacker** [comment]
I got this in wakatime's log file 
`{"now": "2018/06/22 12:25:48 +0530", "version": "10.2.1", "plugin": "vscode/1.24.1 vscode-wakatime/1.2.2", "time": 1529650548.6563134, "caller": "C:\\Users\\chakravarthy\\.vscode\\extensions\\WakaTime.vscode-wakatime-1.2.2\\out\\wakatime-master\\wakatime\\main.py", "lineno": 51, "file": "d:\\platify\\app-react\\src\\Containers\\Gocharge\\Containers\\Home\\index.js", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
{"now": "2018/06/22 12:25:59 +0530", "version": "10.2.1", "plugin": "vscode/1.24.1 vscode-wakatime/1.2.2", "time": 1529650559.7330458, "caller": "C:\\Users\\chakravarthy\\.vscode\\extensions\\WakaTime.vscode-wakatime-1.2.2\\out\\wakatime-master\\wakatime\\main.py", "lineno": 51, "is_write": true, "file": "d:\\platify\\app-react\\src\\Containers\\Gocharge\\Containers\\Home\\index.js", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
`

File Does not exist

**Comment by chakrihacker** [comment]
Any update??

**Comment by alanhamlett** [comment]
Is `d:\` a remote network drive? That error means Python wasn't able to find the `\Containers\Home\index.js` file.

**Comment by chakrihacker** [comment]
No it's not remote drive

**Comment by alanhamlett** [comment]
This is the code in WakaTime that checks if the file exists, and writes that log message:
[wakatime/heartbeat.py#L86](https://github.com/wakatime/wakatime/blob/3373ef39e40971eba2cfc9e40fb5a013f56d63d6/wakatime/heartbeat.py#L86)

The `os.path.isfile` part must not be able to `os.stat()` that file on your `d:` drive:
https://docs.python.org/3/library/os.path.html#os.path.isfile

**Comment by chakrihacker** [comment]
I just deleted repo and cloned again. It started working, thanks for the help
