### ISSUE TITLE
Slows down the internet

### ISSUE THREAD

**Issue by GPlay97** [wakatime/vscode-wakatime#59]
Hey there,

Wakatime is a great tool. But I detected, that since I installed wakatime, my internet connection gets very bad - every time I focus Visual Studio Code and very often when I type. The speed then suddenly vary. From 2MBit/s to 30kbit/s or so. 

Is this a known bug? What can I do against it?

**Comment by alanhamlett** [comment]
> Is this a known bug?

I haven't seen anything like this before. Does this happen only from the same internet provider? For ex: if you go to an internet cafe does it still happen?

I can't think of any reason why WakaTime would cause your computer's internet to slow down, unless something was already misconfigured.

**Comment by GPlay97** [comment]
Thank you for your fast reply.

I will try it later with another connection.

This behavior only exists since a few days - I think since upgrading to Code 1.25

**Comment by GPlay97** [comment]
Hello @alanhamlett .

Tested it out with another connection - the problem still existed.

But now - after upgrading to 1.25.1 (the newest patch), the problem just went way. Even today - no problems.
Can't tell you, if it was just a temporary problem with Code or Wakatime - or something on my computer. But now it is just working fine.

If it's okay, I would close the issue by myself tomorrow or so, if everythings stays fine :)
