### ISSUE TITLE
Feature request: Create a pluging for Azure Data Studio

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [wakatime/vscode-wakatime#62]
### Feature request:
There is a tool called [SQL Operations Studio](https://docs.microsoft.com/en-us/sql/sql-operations-studio/what-is?view=sql-server-2017) that seems seems to share code with VSCode that it's useful for creating and executing TSQL on SQL Server, SQL Azure Database and Azure SQL Data Warehouse

Creating a plugin for SQL Operations Studio based on the current one for VSCode seems (although not sure) fairly straightforward for the contributors of this repo.

**Comment by alanhamlett** [comment]
Here's the related PR: https://github.com/Microsoft/sqlopsstudio/pull/2182

**Comment by Vaelek** [comment]
Any updates on this? the Wakatime supported IDEs page shows SQL Op Studio, though it is now Azure Data Studio, with instructions to install it from the official extensions, in which there is no Wakatime extension.

**Comment by Vaelek** [comment]
After understanding what the hold up is, and even when it is solved, the vscode extension is not entirely appropriate for Azure Data Studio use. I have forked and made it usable, and with a release so everyone doesn't have to build the vsix themselves.

https://github.com/Vaelek/vscode-wakatime

**Comment by gandarez** [comment]
Released a temporary version of VSIX package to install for Azure Data Studio.

https://github.com/wakatime/vscode-wakatime/releases/tag/v2.1.2

**Comment by gandarez** [comment]
WakaTime has been added to the list of available packages for Azure Data Studio.
<img width="366" alt="Screen Shot 2020-06-25 at 15 01 20" src="https://user-images.githubusercontent.com/782854/85774534-ee040780-b6ec-11ea-9a97-f37902f70eb3.png">

**Comment by carlosmunozrodriguez** [comment]
The install button only redirects to the VS Code version of the package, not to Azure Data Studio's one

**Comment by alanhamlett** [comment]
Redirect? It should install without leaving the editor, or that's a difference between Azure and vscode?

**Comment by gandarez** [comment]
@carlosmunozrodriguez @alanhamlett there's no marketplace already implemented for Azure Data Studio so the only way at this moment is to download the VSIX and manually install it. In this case is the same for the VSCODE. Try it and give us a feedback.

https://github.com/microsoft/azuredatastudio/pull/11097#issuecomment-649737168

https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-create-extension?view=sql-server-ver15#publish-your-extension-to-the-marketplace

**Comment by carlosmunozrodriguez** [comment]
Got it. Manually installing it does work.
