### ISSUE TITLE
Detect git branch in the current project

### ISSUE THREAD

**Issue by lamartire** [wakatime/vscode-wakatime#66]
Hello! Thanks for your awesome extension and application! 🙌 
Is there feature to divide statistics in one project context for multiple branches?
For example, I have one project and a lot of features and I want to track spent time  directly for each one.

Something like this:

```
project: example 20h
  - feature-a 10h
  - feature-b 5h
  - master 5h
```

It would be really cool! 👍

**Comment by alanhamlett** [comment]
Yes, git branch is already detected and can be filtered when viewing an individual project's dashboard on the website.

**Comment by lamartire** [comment]
Oh, really. Thank you very much and have a nice day ✨
