### ISSUE TITLE
Support remote files over network drive, ftp, or ssh

### ISSUE THREAD

**Issue by ecker00** [wakatime/vscode-wakatime#67]
I'm using an SMB share to work in Windows from a virtual Linux VM. Turned on debugging and looking in the developer console and the log file to see why none of my time is being tracked (I've put in line breaks for readability).

**VS Code dev console:**
```
[Extension Host] [WakaTime] [DEBUG] Sending heartbeat:
C:\Users\myUser\.vscode\extensions\wakatime.vscode-wakatime-1.2.3\out\python\pythonw
C:\Users\myUser\.vscode\extensions\wakatime.vscode-wakatime-1.2.3\out\wakatime-master\wakatime\cli.py
--file \\192.168.0.10\myShare\myProject\myFile.sh
--plugin "vscode/1.27.2 vscode-wakatime/1.2.3"
--alternate-project myProject
--write
--config C:\Users\myUser\.wakatime.cfg
--logfile C:\Users\myUser\.wakatime.log
```
**.wakatime.log:**
```json
{
"now": "2018/10/02 06:53:22 +0200",
"version": "10.3.0",
"plugin": "vscode/1.27.2 vscode-wakatime/1.2.3",
"time": 1538456002.735315,
"caller": "C:\\Users\\myUser\\.vscode\\extensions\\wakatime.vscode-wakatime-1.2.3\\out\\wakatime-master\\wakatime\\main.py",
"lineno": 51,
"is_write": true,
"file": "\\\\192.168.0.10\\myShare\\myProject\\myFile.sh",
"level": "DEBUG",
"message": "File does not exist; ignoring this heartbeat."
}
```

It seems that it detects that the file does not exist `\\192.168.0.10\myShare\myProject\myFile.sh`. But that path does work when entering it into Explorer, so I assume that Wakatime is not able to interpret a network path like Explorer does.

How can I get around this issue? Is there a way to ignore 'file does not exist' and track it anyway?

**Comment by ecker00** [comment]
For the record I tested making a symlink and open VS Code from that, but it still resolves to the true network path, even if Explorer operates from the symlinked path.
```
cd /Users/myUser
mklink /D myShare \\192.168.0.10\myShare
```
**File does not exist; ignoring this heartbeat.**

**Comment by alanhamlett** [comment]
Related to wakatime/wakatime#72 and wakatime/wakatime-mode#27.

**Comment by alanhamlett** [comment]
> I assume that Wakatime is not able to interpret a network path like Explorer does.

That's right, WakaTime uses Python's `os.path.isfile` to check if the file exists. I think embedding [pywin32](https://github.com/mhammond/pywin32) then using this is the solution: https://stackoverflow.com/a/45102663/1290627

**Comment by alanhamlett** [comment]
Added network drive files support for Windows in v10.4.0. If you restart VS Code it will update wakatime-cli to the latest version. Let me know if it works!

**Comment by ecker00** [comment]
Thanks for attempting a fix. I gave it another shot and checked the logs. Seems the cli is at version 10.4.1 so it has updated, but I'm still getting the same error. (Just added line breaks to the log for readability)
```
{
  "now": "2018/10/09 08:37:27 +0200",
  "version": "10.4.1",
  "plugin": "vscode/1.27.2 vscode-wakatime/1.2.3",
  "time": 1539067047.6750627,
  "caller": "C:\\Users\\myUser\\.vscode\\extensions\\wakatime.vscode-wakatime-1.2.3\\out\\wakatime-master\\wakatime\\main.py",
  "lineno": 52,
  "file": "\\\\192.168.172.128\\myShare\\myProj\\readme.md", 
  "level": "DEBUG",
  "message": "File does not exist; ignoring this heartbeat."
}
```

**Comment by glics** [comment]
Happening here as well. Windows 10 x64 1909, vscode 1.45.1, extension version 4.0.0.
Weird that it happens also when a remote folder is mapped as network drive 🤔 

```JSON
{
  "now": "2020/05/18 18:25:18 +0200",
  "version": "13.0.7",
  "plugin": "vscode/1.45.1 vscode-wakatime/4.0.0",
  "time": 1589819118.2597008,
  "caller": "wakatime\\main.py",
  "lineno": 68,
  "file": "\\\\192.168.0.222\\htdocs\\supersecretfolder\\supersecretfile.php",
  "level": "DEBUG",
  "message": "File does not exist; ignoring this heartbeat."
}
```

**Comment by alanhamlett** [comment]
Has this improved now that we're using the new Go wakatime-cli?

**Comment by ecker00** [comment]
I'm not affected by this issue anymore, so I can't confirm.  But with the way VS code handles SSH connections these days it's not been a problem for me.

**Comment by alanhamlett** [comment]
Related to wakatime/wakatime-cli#623, which added support for `ssh://` and `sftp://` remote files.
