### ISSUE TITLE
Error: command failed (missing --plugin)

### ISSUE THREAD

**Issue by psukys** [wakatime/vscode-wakatime#69]
While this doesn't seem to be reflected in VSCode's UI, after accidentally checking *developer console*, I noticed that there's wakatime seldom fails to run (copy from console log):
```
[WakaTime] [ERROR] Error: Command failed: python3 /home/psukys/.vscode/extensions/wakatime.vscode-wakatime-1.2.3/out/wakatime-master/wakatime/cli.py --file /data/Documents/Projects/TUM/Thesis/code/ops-ds2os/opsds2os/nlsm.py --plugin vscode/1.29.1 vscode-wakatime/1.2.3 --alternate-project ops-ds2os
```
Trying to run the same command in console, error is more verbose:
```
wakatime: error: unrecognized arguments: vscode-wakatime/1.2.3
```

I believe the problem is missing `--plugin` before `vscode-wakatime/1.2.3` as there's no more aforementioned error by using it.

**Comment by alanhamlett** [comment]
Fixed with e5ba51264c464af4482ae6b4ea0e6db8e0d1ad1a and released in v1.2.4.
