### ISSUE TITLE
Invalid python version

### ISSUE THREAD

**Issue by sangparksangpark** [wakatime/vscode-wakatime#72]
[Extension Host] [WakaTime] [DEBUG] Invalid python version: 
/C:/Users/Bronny James/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python3
/C:/Users/Bronny James/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
/C:/Users/Bronny James/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] [WakaTime] [DEBUG] Looking for python at: pythonw

It keeps going.  I tried deleting the files on windows and reinstalling the files.  I still get the same error.

**Comment by brunodotcom** [comment]
@sangparksangpark It's happening the same with me. I've tried to install python manually but it doesn't work.


[Extension Host] [WakaTime] [DEBUG] Initializing WakaTime v1.2.4
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: C:\Users\Bruno Rocha\.vscode\extensions\wakatime.vscode-wakatime-1.2.4\out\python\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/local/bin/python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/local/bin/python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/bin/python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/bin/python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python39\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python39\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python38\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python38\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python37\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python37\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python36\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python36\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python35\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python35\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python34\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python34\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python33\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python33\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python29\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python29\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python28\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python28\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python27\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python27\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Downloading python...
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Extracting python...
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Finished installing python.
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: C:\Users\Bruno Rocha\.vscode\extensions\wakatime.vscode-wakatime-1.2.4\out\python\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/local/bin/python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/local/bin/python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/bin/python3
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: /usr/bin/python
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python39\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python39\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python38\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python38\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python37\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python37\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python36\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python36\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python35\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python35\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python34\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python34\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python33\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python33\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python29\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python29\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python28\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python28\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \python27\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Looking for python at: \Python27\pythonw
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Downloading wakatime-core...
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Extracting wakatime-core into "C:\Users\Bruno Rocha\.vscode\extensions\wakatime.vscode-wakatime-1.2.4\out"...
console.ts:134 [Extension Host] [WakaTime] [DEBUG] Finished extracting wakatime-core.

**Comment by brunodotcom** [comment]
I'm trying to debug the extensions.js on my own. So I found this error in the process
`Error: spawn "C:\Users\Bruno Rocha\.vscode\extensions\wakatime.vscode-wakatime-1.2.4\out\python\pythonw" ENOENT`

I don't know if it's the cause, but I will continue to dig in it

**Comment by brunodotcom** [comment]
@sangparksangpark it's not a fix but solved for me changing my extensions folder to root, like "C:\vscode\extensions"

It can be done by setting the extension folder path on shortcut properties

![image](https://user-images.githubusercontent.com/20939785/49901362-2a904b00-fe48-11e8-80e4-bc4c101eb60b.png)

**Comment by gandarez** [comment]
@sangparksangpark is this still happening?
