### ISSUE TITLE
ConnectTimeout

### ISSUE THREAD

**Issue by jmluang** [wakatime/vscode-wakatime#75]
Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10195bc50>, \'Connection to api.wakatime.com timed out. (connect timeout=60)\'))\n', 'ConnectTimeout': u"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10195bc50>, 'Connection to api.wakatime.com timed out. (connect timeout=60)'))

**Comment by alanhamlett** [comment]
This might be due to Chinese ISPs blocking Digital Ocean's IP addresses, more info in wakatime/vim-wakatime#77.

**Comment by jmluang** [comment]
Add hosts record works for me too, thx. as i know DO's IP blocked by gfw on usual. please find a good way to this problem

**Comment by alanhamlett** [comment]
We're switching to GitHub releases for hosting wakatime-cli soon, which might fix this if GitHub is available on your ISP.

**Comment by alanhamlett** [comment]
Related to #185 and #157.

**Comment by alanhamlett** [comment]
Support for downloading wakatime-cli from GH Releases was added with bfbe49cf9f1e6bfe5b9f7c63a72941bd5895a7ed, and will be released soon once the wakatime-cli repo is public.
