### ISSUE TITLE
Queue heartbeats when offline

### ISSUE THREAD

**Issue by n1try** [wakatime/vscode-wakatime#76]
I was wondering if anything will be recorded while the user is offline. In [extension.ts#L304](https://github.com/wakatime/vscode-wakatime/blob/master/src/extension.ts#L304) that error case is handled, but no special logic is executed. 
For instances, in the JetBrains plugin, heartbeats are getting queued while the user is offline and sent as `extra-heartbeats` when she gets back online. But I couldn't find a similar mechanism in this plugin.

**Comment by alanhamlett** [comment]
The queue is implemented in the common wakatime-cli core library:
https://github.com/wakatime/wakatime/blob/9b2eabe5680ceebc25caf229cf29b163487976fe/wakatime/offlinequeue.py

Extra heartbeats is only a local buffer to prevent forking too many Python processes but it's not meant for storing heartbeats while coding offline.
