### ISSUE TITLE
Location for config files in Portable VS Code

### ISSUE THREAD

**Issue by jgmuchiri** [wakatime/vscode-wakatime#77]
For Portable VS Code, Wakatime sets config files in machine's user profile instead of the VS Code data directory. When you open VS Code on a new machine, you have to re-enter the key which is then set in that computer. Currently, the only is to manually move the config files each time you change computer.

In extension.js, this is explicitly specified in line 689 and 193. Expanding these functions to allow for portability would be great.
```js
getWakaHome() {
        let home = process.env.WAKATIME_HOME;
        if (home) {
            return home;
        }
        else {
            return this.getUserHomeDir();
        }
    }
```

```js
 getUserHomeDir() {
        return process.env[Dependencies.isWindows() ? 'USERPROFILE' : 'HOME'] || '';
    }
```

Currently, my settings to override this was to edit the above function to set config files to the `data/extensions-data` inside VS Code portable directory but would obviously be overwritten with update

```js
 getUserHomeDir() {
        return 'data/extensions-data';
    }
```

**Comment by gandarez** [comment]
There's an open discussion about detecting or not `PORATBLE MODE`

https://github.com/Microsoft/vscode/issues/66029

**Comment by gandarez** [comment]
PR https://github.com/wakatime/vscode-wakatime/pull/91
