### ISSUE TITLE
WakaTime not Recording -- No Errors in Developer Tools Console

### ISSUE THREAD

**Issue by ETCraig** [wakatime/vscode-wakatime#79]
I've had WakaTime for two months now and it's worked great, even have a leaderboard at my work shared among all the developers. But recently while coding I noticed it'd stopped, just after 33 minutes of recording. WakaTime 'Plugin Status' page also shows that the status is okay and recognizes the last time I used VSCode.

![screenshot 132](https://user-images.githubusercontent.com/36967801/52529529-f9998e80-2caf-11e9-826c-c83fee6bffd6.png)

**Comment by PinguinitoRAwr** [comment]
Same for me on VSCode and IDEA, [heartbeats seem to be received](https://wakatime.com/api/v1/users/current/) by the server but not processed into stats. Re-installed plugin and same thing. 

Look like the issue started at Feb 10 00:00GMT

**Comment by simonbrazell** [comment]
Same problem here, I spent the day coding only to realise none of it was tracked when I'd finished, I tried restarting VSCode, re-installing the plugin, and checked the wakatime log file, there were no errors present.

**Comment by xiezipei** [comment]
Same problem on my VSCode and IDEA. There is not recording all the day.

**Comment by PinguinitoRAwr** [comment]
My Dashboard just updated and it looks like there is no data loss... 
it was just a processing delay of ~10 hours (?)

**Comment by simonbrazell** [comment]
Yep mine too, it's all there now.

**Comment by ETCraig** [comment]
Lol just small barely noticeable delay. But yeah, mines up and running again too, I wonder what was going on.  But I guess that pretty much solves it.
