### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lucianFerb** [wakatime/vscode-wakatime#83]
- Issue Type: `Performance`
- Extension Name: `vscode-wakatime`
- Extension Version: `1.2.5`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Ferb\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by alanhamlett** [comment]
@lucianFerb could you upload that file mentioned `C:\Users\Ferb\WakaTime.vscode-wakatime-unresponsive.cpuprofile.txt`?

**Comment by gandarez** [comment]
@lucianFerb is it possible to share the `CPU Profile`?

**Comment by gandarez** [comment]
Closing due to lack of response. Please reopen this issue if needed.
