### ISSUE TITLE
how to uninstall all things?

### ISSUE THREAD

**Issue by zhangwilling** [wakatime/vscode-wakatime#85]
Recently, wakatime not work, just intiallizeing.
 i manually remove  .wakatime.db    .wakatime.log  .wakatime.cfg and uninstall wakatime plugin, then reinstall wakatime plugin. But, it not works still intiallizeing. 

i found the sqlite db was not  created.

i guess i did  not remove all things, so reinstall not worked.

**Comment by alanhamlett** [comment]
https://wakatime.com/plugins/vs-code/uninstalling

Closing as duplicate of #84.
