### ISSUE TITLE
SSLError: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vscode-wakatime#86]
ricokahler commented,

> I haven't got this to work for around 3 weeks now.
> 
> ![image](https://user-images.githubusercontent.com/10551026/54066420-634c8000-41fd-11e9-9eb8-c5e9d7c10989.png)
> 
> here's a line from the logs:
> 
> ```json
> {
>   "now": "2019/03/08 23:43:01 -0500",
>   "version": "10.8.0",
>   "plugin": "vscode/1.32.1 vscode-wakatime/1.2.12",
>   "time": 1552106580.9384892,
>   "caller": "/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/api.py",
>   "lineno": 125,
>   "file": "/Users/ricokahler/workspace/resift/src/combineLoadingStates/combineLoadingStates.ts",
>   "level": "WARNING",
>   "message": "{'SSLError': 'HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))', 'traceback': 'Traceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 589, in urlopen\\n    conn = self._get_conn(timeout=pool_timeout)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 251, in _get_conn\\n    return conn or self._new_conn()\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 827, in _new_conn\\n    raise SSLError(\"Can\\'t connect to HTTPS URL because the SSL \"\\nurllib3.exceptions.SSLError: Can\\'t connect to HTTPS URL because the SSL module is not available.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/api.py\", line 111, in send_heartbeats\\n    verify=ssl_verify)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/Users/ricokahler/.vscode/extensions/wakatime.vscode-wakatime-1.2.12/wakatime-master/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n'}"
> }
> ```

**Comment by alanhamlett** [comment]
This is the important part of that error message:

`SSL module is not available`

Are you by chance using Anaconda Python?

**Comment by ricokahler** [comment]
No, as far as I'm aware I'm using a version of python3 installed using brew. 

![image](https://user-images.githubusercontent.com/10551026/54066579-32217f00-4200-11e9-9cc0-6cea64bb7a66.png)

**Comment by gandarez** [comment]
@ricokahler try installing via homebrew the following

`brew install openssl`

**Comment by ricokahler** [comment]
oh sorry i did eventually figure this out. you’re right it was due to openssl issues but specifically this happens when you have brew on a mac and then migrate your mac’s data to another mac. that mac will have this issue. nuking brew and reinstalling openssl did fix it

**Comment by gandarez** [comment]
Thanks for the feedback.

**Comment by ricokahler** [comment]
thanks for the support! ❤️

**Comment by TryTryAgain** [comment]
For me, openssl was already installed but I had the same issue. I then issued a `brew install openssl` command and restarted vscode and I was back in business.

**Comment by Asgaroth** [comment]
I am still having this issue, removed and reinstalled `openssl` via brew, manually added a link

`ln -s /usr/local/opt/openssl/include/openssl /usr/local/include`

But I am still getting the same error in `~/.wakatime.log`

**Comment by gandarez** [comment]
@Asgaroth could please paste here the errors you got?

**Comment by TryTryAgain** [comment]
This continues to be an issue for me, seems like updates or something continue to screw it up as soon as I get it working again :(

Example log output:

```
{
    "now": "2020/01/27 12:06:58 -0600",
    "version": "13.0.3",
    "plugin": "vscode/1.41.1 vscode-wakatime/2.2.1",
    "time": 1580148417.8351018,
    "caller": "/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/api.py",
    "lineno": 125,
    "is_write": true,
    "file": "/Users/someuser/somepath/file.ext",
    "level": "WARNING",
    "message": "{'SSLError': 'HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))', 'traceback': 'Traceback (most recent call last):\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 589, in urlopen\\n    conn = self._get_conn(timeout=pool_timeout)\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 251, in _get_conn\\n    return conn or self._new_conn()\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 827, in _new_conn\\n    raise SSLError(\"Can\\'t connect to HTTPS URL because the SSL \"\\nurllib3.exceptions.SSLError: Can\\'t connect to HTTPS URL because the SSL module is not available.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/api.py\", line 111, in send_heartbeats\\n    verify=ssl_verify)\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/Users/someuser/.vscode/extensions/wakatime.vscode-wakatime-2.2.1/wakatime-master/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n'}"
}
```

**Comment by gandarez** [comment]
@TryTryAgain what's your environment? (SO, python version, etc..)

**Comment by TryTryAgain** [comment]
OS - MacOS 10.14.6
Python - 3.7.5
vscode - 1.41.1
wakatime.vscode-wakatime - 2.2.1

If there's anything else, let me know.

**Comment by vancetran** [comment]
@gandarez Having similar problems.

OS: 10.14.6
Python: 3.6.5
VS Code: 1.41.1
Wakatime: 2.2.1
OpenSSL: `openssl@1.1 1.1.1d`

**Comment by alanhamlett** [comment]
Possibly fixed with [v13.0.4 of wakatime](https://github.com/wakatime/wakatime/blob/master/HISTORY.rst#1304-2020-02-05) as long as one of the [supported SSL versions](https://www.pyopenssl.org/en/stable/install.html#supported-openssl-versions) is available on your machine:

* 1.0.1
* 1.0.2
* 1.1.0
* 1.1.1

**Comment by vancetran** [comment]
@alanhamlett  Thanks, it seems to be working again. It seems to have lost my progress for last two weeks, though. To be clear, I am not complaining and very much appreciate the free tier.

**Comment by alanhamlett** [comment]
> Spoke too soon. Seems like Wakatime now shows the time tracking data that occurred while I had this issue. No data loss! Thanks again.

Was just about to say hopefully it syncs that offline activity soon, glad it already did!

**Comment by alanhamlett** [comment]
@Asgaroth @TryTryAgain if this is still an issue for you after updating the plugin we can repoen this issue, closing for now.

**Comment by TryTryAgain** [comment]
Looks like the update still hasn't hit the marketplace. I will reopen if it's still an issue. Thanks!

**Comment by alanhamlett** [comment]
> Looks like the update still hasn't hit the marketplace. I will reopen if it's still an issue. Thanks!

Oh sorry, I meant the wakatime dependency not the plugin itself. The plugin checks for updates to https://github.com/wakatime/wakatime every time you relaunch your IDE, so it should auto-update from GitHub without the vscode plugin needing a version bump.
