### ISSUE TITLE
No recognizing .cxx files as C++ file

### ISSUE THREAD

**Issue by imdanielsp** [wakatime/vscode-wakatime#87]
I am not sure if this goes under the VSCode repo, but using VSCode (I am not sure if its specific to VSCode) I noticed that WakaTime its not recognizing .cxx files as C++ files. I don't write a lot of C and if you go to the bottom of my website, ([here](http://danielsantos.io), you can see that the pie is almost 50% C (trust me this is wrong).

**Comment by alanhamlett** [comment]
Fixed with [540557e9984ce198bf081511258547bfc48a0802](https://github.com/wakatime/wakatime/commit/540557e9984ce198bf081511258547bfc48a0802#diff-2de3aa790c0e0ca3d2203b8d27b2a36eR186) and released in v10.8.1 of the wakatime-core. If you restart VS Code it will detect and auto-update wakatime-core.

**Comment by imdanielsp** [comment]
Great, thanks!
