### ISSUE TITLE
Incorrect Language Detection 

### ISSUE THREAD

**Issue by threecgreen** [wakatime/vscode-wakatime#89]
Wakatime thinks LaTeX class files with a `.cls` extension are 'OpenEdge ABL', even though the language mode in VSCode is set to 'TeX' for these files.

![wakatime](https://user-images.githubusercontent.com/17754110/56095462-f171f100-5ea2-11e9-93d1-e64439f03bb6.png)

**Comment by alanhamlett** [comment]
Moved to wakatime/wakatime#172 since that's the repo handling language detection.
