### ISSUE TITLE
With this plugin a get the Elm language listed as other.

### ISSUE THREAD

**Issue by 7sharp9** [wakatime/vscode-wakatime#9]
I believe this was fixed in the core wakatime v6.0.5.  Maybe this plugin has not updated to that version yet?

**Comment by alanhamlett** [comment]
After relaunching Vscode is Elm detected?

**Comment by 7sharp9** [comment]
Yeah Elm is detected:
<img width="1033" alt="screen shot 2016-06-14 at 20 19 44" src="https://cloud.githubusercontent.com/assets/588746/16056444/6aebd43e-326d-11e6-9655-717ab62db5b6.png">

**Comment by 7sharp9** [comment]
Elm seems to be just added to the other category:
<img width="342" alt="screen shot 2016-06-14 at 20 21 05" src="https://cloud.githubusercontent.com/assets/588746/16056475/8dcb3a58-326d-11e6-9535-f915a25da2bb.png">

**Comment by alanhamlett** [comment]
There was a bug preventing the old wakatime-cli from getting deleted when updating, can you run this Terminal command then relaunch VSCode to make sure you have the latest wakatime-cli:
`rm -rf ~/.vscode/extensions/WakaTime.vscode-wakatime-1.0.6/out/wakatime-master/`

With the latest wakatime-cli, Elm files should be detected as long as they end with `.elm`.

**Comment by 7sharp9** [comment]
Yeah actively killing the old version seems to do the trick thanks for the suggestion :-)

**Comment by alanhamlett** [comment]
Great! Closing this issue as fixed.
