### ISSUE TITLE
"Command not found" when using anything in the plugin

### ISSUE THREAD

**Issue by vnen** [wakatime/vscode-wakatime#93]
Just installed the 2.0 version (that seems to be quite fresh) and when I tried to setup the API key within the Ctrl+Shift+P menu I got the following message:

`Error: command 'wakatime.apikey' not found`

The same happen to any other thing I try (e.g. open dashboard, open config file, status bar icon, etc.), naturally with a different command name in the error message.

Downgrading the version to 1.3.0 make it work fine.

**Comment by PixelHir** [comment]
Autoupdated - broken too, reinstallation doesn't seem to help.

**Comment by walkah** [comment]
Also doesn't seem to be reporting any usage (and no updates in wakatime.log)

**Comment by alanhamlett** [comment]
Fixed in v2.0.1.

**Comment by alanhamlett** [comment]
Fixed with ddc836e6169f91e949e3507b505806745222b040.

**Comment by sk-sahu** [comment]
Following the new update  of vscode again the same error on TERMINAL

`Error: command 'wakatime.apikey' not found`

Wakatime version: 4.0.0

## VSCODE
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic snap

**Comment by alanhamlett** [comment]
@sk-sahu if you restart vscode does it work?

**Comment by sk-sahu** [comment]
No. I tired it. But no help.

**Comment by sungle3737** [comment]
same error
