### ISSUE TITLE
Handle exceptions from execFile

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vscode-wakatime#94]
@alanhamlett you helped me solve similar issue earlier this month over the email. My wakatime stays at initializing and it found to be an issue with Python version. You have done some magic and released a new version and I installed it which resolved the issue. 

But lately, the issue popped up again  with the same reason after I updated my mac OS to 10.14.4.

[Extension Host] [WakaTime][DEBUG] Looking for python at: /Users/hanu/.vscode/extensions/wakatime.vscode-wakatime-2.0.6/python/pythonw
console.ts:134 [Extension Host] [WakaTime][DEBUG] Invalid python version: 
console.ts:134 [Extension Host] [WakaTime][DEBUG] Looking for python at: python3

So, would this require another new version or it is something to do on my side?

_Originally posted by @amruta-pani in https://github.com/wakatime/wakatime/issues/155#issuecomment-486916803_

**Comment by alanhamlett** [comment]
This is a regression with the refactoring in 66c49262c6f1769f2805b9ef15351c9b28939648 where the bug was re-introduced. It should be fixed again with b5e1bb6f2010c77e572572172128b2a9b049e6c8 and released just now in v2.0.7.

Can you update the extension to 2.0.7 and see if it's fixed?

**Comment by amruta-pani** [comment]
@alanhamlett It worked. Thanks a lot.
