### ISSUE TITLE
command 'wakatime.status_bar_icon' not found

### ISSUE THREAD

**Issue by fakhamatia** [wakatime/vscode-wakatime#97]
when i want disable wakatime icon in status bar
`command 'wakatime.status_bar_icon' not found`

**Comment by gandarez** [comment]
Which version of WakaTime is installed?

**Comment by fakhamatia** [comment]
2.0.8
Version: 1.33.1

i have same problem in ubuntu and windows

**Comment by gandarez** [comment]
Have you tried like this?
<img width="618" alt="Screen Shot 2019-05-04 at 15 40 28" src="https://user-images.githubusercontent.com/782854/57183399-fa8f2600-6e82-11e9-9db1-5d2c2698e043.png">

**Comment by fakhamatia** [comment]
![wakatime](https://user-images.githubusercontent.com/20030910/57183730-57f89680-6ec6-11e9-8806-e67de29acf2d.gif)

**Comment by gandarez** [comment]
PR https://github.com/wakatime/vscode-wakatime/pull/98 made

**Comment by alanhamlett** [comment]
Fixed and released in v2.0.9 just now.
