### ISSUE TITLE
Add an option to hide the "Today: xyz" on the status bar

### ISSUE THREAD

**Issue by flesler** [wakatime/vscode-wakatime#99]
I noticed the Wakatime bit on the status bar is now larger, it shows the total time today.

Honestly, I find it distracting, I would personally prefer it wasn't there. I looked for a flag in the settings to hide it but nothing. Can you add a flag to hide it ?

**Comment by alanhamlett** [comment]
The setting to hide is named `WakaTime: Status Bar Coding Activity`. Setting that to `false` turns off coding activity in your status bar.

To find that setting, press `CMD + SHIFT + P` then type `wakatime`.

**Comment by gandarez** [comment]
To hide just type in the command pallet `WakaTime: Status Bar Coding Activity` and set to `false`

**Comment by flesler** [comment]
👍

**Comment by suryateja619** [comment]
I'm no longer seeing the `Total Time` if I enable the setting?

**Comment by gandarez** [comment]
Something is happening

`[WakaTime][ERROR] Error retrieving coding activity: TypeError: Cannot read property '0' of undefined`

**Comment by alanhamlett** [comment]
This was an api issue today, but it's fixed now and the time should show up again.
